### ISSUE TITLE
ecs-cli down requires --force flag

### ISSUE THREAD

**Issue by nathanleclaire** [aws/amazon-ecs-cli#10]
After issue in https://github.com/aws/amazon-ecs-cli/issues/9, I tried to `ecs-cli down`.  But, I got an error indicating that the `--force` flag is required.  If it's required, why make it a flag?  ;D

**Comment by frewsxcv** [comment]
Part of me is glad `ecs-cli down` by itself doesn't take down the whole system. Maybe `ecs-cli down` should prompt the user to type 'yes' or 'no' if they want to delete the cluster, and `ecs-cli down --force` should delete the cluster without input.
