### ISSUE TITLE
Please just stop this project and integrate it into aws(.ecs) cli, PLEASE?

### ISSUE THREAD

**Issue by smileatom** [aws/amazon-ecs-cli#1003]
This "project" is just a one off fork of the AWS ecs cli. It does no good and just causes harm without bringing any benefits.

**Comment by kohidave** [comment]
Howdy! Thanks for your feedback :) The ECS CLI is actually pretty different than what's in the AWS CLI. The AWS CLI is a great way to call ECS APIs, but won't help you with setting up resources (ECS service, monitor deployments), converting docker-compose files, replicating your services locally, etc. 

We've wondered about merging these features into the AWS CLI but there are some technical reasons that's difficult, and we just generally believe that it's ok to have some specific tools which can have a really focused use-case :) 

I'll close this issue now - but let me know if you need any help with the ECS CLI or AWS CLI.

**Comment by smileatom** [comment]
The problem I see with it is that its essentially unreliable and not particularly useful.  When I deploy to fargate using aws ecs it works every time.  This tool seems to be trying to be doing way too many things in the name of of convenience.  Its ok for one offs maybe.  But for automation it simply is unreliable.  What WOULD be better, is to simply provide a TaskDef generator (externally) to map from docker compose to a task def.  Its easy enough to do and doesnt have all the baggage of this toolset.
