### ISSUE TITLE
Updating a service

### ISSUE THREAD

**Issue by logxseven** [aws/amazon-ecs-cli#1008]
Hello there are many things that i don't know how to do with this tool. and i cannot find in the documentation. when of them is updating a container. after deploying a new container to docker hub for example. how do i update the services to use that new container without having any down time.

in addition, scaling of containers and tasks takes forever. how can i force drainage or deployment and speed it up ?

another thing is i have a selenium container that uses a lot of memory over time and i want it to recreate itself when the memory exceeds a certain limit. any idea on how i can do that ? 

thank you !

**Comment by sonofachamp** [comment]
Hey @logxseven please check out https://github.com/aws/amazon-ecs-cli/issues/136#issuecomment-233818082 regarding no downtime deployments.

> in addition, scaling of containers and tasks takes forever. how can i force drainage or deployment and speed it up ?

Can you provide an example command you're running where you're experiencing long waits?

> another thing is i have a selenium container that uses a lot of memory over time and i want it to recreate itself when the memory exceeds a certain limit. any idea on how i can do that ?

For this you might be able to subscribe to a CloudWatch/ContainerInsights alarm to run some action against your container on ECS, but I'd look into why your selenium container memory usage is unstable before going through too much trouble.

**Comment by SoManyHs** [comment]
Hi @logxseven ! Are you still having trouble finding documentation? Closing this issue for now due to staleness but feel free to re-open if you have more specific concerns!
