### ISSUE TITLE
Add support for EFS volume mounts

### ISSUE THREAD

**Issue by NikitaGl** [aws/amazon-ecs-cli#1009]
#### Context

Recently EFS mounts became generally available for ECS on EC2 and Fargate platforms. We are really looking forward to use it in our services, managed by `ecs-cli`

#### Alternatives

For now, several of our applications are designed to download certain data from S3 during startup. This step could be eliminated using EFS mounts.
#### Additional context

https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-ecs-aws-fargate-support-amazon-efs-filesystems-generally-available/

**Comment by bvtujo** [comment]
Thanks so much for reaching out about this and letting us know your use case. We'll update this issue with any ongoing developments in this area.

**Comment by docktermj** [comment]
Is this the same issue as https://github.com/aws/amazon-ecs-cli/issues/1043 ?

**Comment by NikitaGl** [comment]
As I see, [#1019](https://github.com/aws/amazon-ecs-cli/pull/1019) that enables requested feature is merged. Consider this issue to be resolved.

**Comment by NigelSwinson** [comment]
As per https://github.com/aws/amazon-ecs-cli/pull/1019, this should be closed.
