### ISSUE TITLE
SSM Parameter Hierarchy with ECS-Local

### ISSUE THREAD

**Issue by Aubtin** [aws/amazon-ecs-cli#1011]
Reopening issue #1010.

After further testing it appears the issue is not related to the prefix in the SSM parameter name. If the heirarchy is greater than the root it appears to issue the error outlined in the prior issue. The following is an example of what can cause the error:
```
resource "aws_ssm_parameter" "test" {
  name = "/test/test2/test3"
  type = "String"
  value = "TEST-TEST"
}
```

**Comment by bvtujo** [comment]
This problem is addressed in the fix for #1010. Closing this one, will continue discussing there.
