### ISSUE TITLE
Getting "is used but no declaration was found in the volumes section" on Windows

### ISSUE THREAD

**Issue by michaeluskov** [aws/amazon-ecs-cli#1017]
#### Summary

I'm trying to run `ecs-cli compose up` on Windows 10 to run docker-jitsi in the cloud.
Here is `docker-compose.yml` sample: https://github.com/jitsi/docker-jitsi-meet/blob/master/docker-compose.yml

When I run the command, I get this error:

```
[33mWARN[0m[0000] Skipping unsupported YAML option for service...  [33moption name[0m=expose [33mservice name[0m=prosody
[33mWARN[0m[0000] Skipping unsupported YAML option for service...  [33moption name[0m=networks [33mservice name[0m=prosody
[33mWARN[0m[0000] Skipping unsupported YAML option for service...  [33moption name[0m=restart [33mservice name[0m=prosody
[31mERRO[0m[0000] Unable to open ECS Compose Project            [31merror[0m="named volume [C:\\Users\\michaeluskov\\Documents\\.jitsi-meet-cfg\\prosody\\config] is used but no declaration was found in the volumes section"
[31mFATA[0m[0000] Unable to create and read ECS Compose Project  [31merror[0m="named volume [C:\\Users\\michaeluskov\\Documents\\.jitsi-meet-cfg\\prosody\\config] is used but no declaration was found in the volumes section"
```

`docker-compose up` works with this configuration.

#### Description
* Which version of the CLI you are using? ecs-cli version 1.18.1 (7e9df84)
* What platform are you using to run ECS CLI commands? Windows 10

#### Config files

* docker-compose.yml

https://github.com/jitsi/docker-jitsi-meet/blob/master/docker-compose.yml

* ecs-params.yml

None

* ~/.ecs/config

```
version: v1
default: livebar-jitsi
clusters:
  livebar-jitsi:
    cluster: livebar-jitsi
    region: eu-central-1
    default_launch_type: EC2
```

**Comment by allisaurus** [comment]
Hi @michaeluskov - it looks like you're compose file is using `expose`,`networks`, and `restart`, which are not currently supported by the ecs-cli. A list of supported fields can be found [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-parameters.html) (which is linked in our README, but admittedly not super discoverable).

I also looks like `$CONFIG` in your volumes field is referencing a file on your local machine, which would not be available to the ECS task running on EC2 or Fargate. (The validation message is b/c the tool is looking for a top-level volume with that name and not finding one.) Any files you want to include need to be included in one of your container images or pulled from an external source, such as S3 (by the container on start up) or AWS Sys Manager [param store](https://docs.aws.amazon.com/AmazonECS/latest/userguide/specifying-sensitive-data-parameters.html), as an env var.

**Comment by SoManyHs** [comment]
Closing for stalenesss.

**Comment by strizzwald** [comment]
Hi, I'd like to re-open this issue as I'm experiencing the exact same problem.

I've referenced a folder in my `docker-compose.yml` file that sits on my machine, according to the docs I should be able to bind mount this folder and deploy to Fargate.

https://docs.aws.amazon.com/AmazonECS/latest/userguide/using_data_volumes.html

To paraphrase: 

Amazon ECS on Fargate supports the following data volume options for containers.

- Amazon EFS volumes — Provides simple, scalable, and persistent file storage for use with your Amazon ECS tasks. With Amazon EFS, storage capacity is elastic, growing and shrinking automatically as you add and remove files. Your applications can have the storage they need, when they need it. For more information, see Amazon EFS volumes.
- Bind mounts — A file or directory on the host, such as AWS Fargate, is mounted into a container. For more information, see Bind mounts.
