### ISSUE TITLE
Unable to read parameters from parameter store in local environment

### ISSUE THREAD

**Issue by nilsdebruin** [aws/amazon-ecs-cli#1020]
#### Summary
An error occurs when starting a local task definition: Failed to decrypt secret due to ValidationError: Parameter name: can't be prefixed with "ssm"

#### Description
* Which specific command was run? `ecs-cli local create` followed by `ecs-cli local up`
* Which version of the CLI you are using? `1.18.1`
* Which version of Go are you using? `go1.14.2`
* What platform are you using to run ECS CLI commands? `macOS`

#### Config files
In the converted docker-compose file, I have these labels:
```
labels:
      ecs-local.secret.DB_HOST: arn:aws:ssm:eu-west-1:account_id:parameter/first_part/DB_HOST
```

#### Expected Behavior
A running environment where the secrets are injected and the containers are started.

#### Observed Behavior
```
FATA[0002] Failed to decrypt secret due to 
failed to retrieve decrypted secret from arn:aws:ssm:eu-west-1:<account_id>:parameter/first_part/DB_HOST due to ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
        status code: 400, request id: x: ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
        status code: 400, request id:x
```

Let me know if more information is needed!

**Comment by nilsdebruin** [comment]
I can see that this has been reported already with #1010 and #1011 (I couldn't find it earlier), so I will close this issue

**Comment by viltohmyst** [comment]
Hi @nilsdebruin, not sure if I should post a new issue or if its the same with this one. I am getting the same errors as the above, albeit a shorter error description :

```FATA[0002] Failed to decrypt secret due to 
failed to retrieve decrypted secret from arn:aws:ssm:<region>:<accountid>:parameter/ENV_VAR due to ParameterNotFound: : ParameterNotFound:
```

I also have these in the generated docker-compose file

```
labels:
      app: MyApp
      ecs-local.secret.ENV_VAR: arn:aws:ssm:<region>:<accountId>:parameter/ENV_VAR
```

My ecs-cli version is : ecs-cli version 1.21.0 (bb0b8f0)

I don't think its related to issue #1010 and #1011 since my parameters didn't have deeply nested paths.
