### ISSUE TITLE
Platform Version is not Null by default in release 1.19.0

### ISSUE THREAD

**Issue by minaeakhalil** [aws/amazon-ecs-cli#1040]
### Summary
Receiving an error `InvalidParameterException: The platform version must be null when specifying an EC2 launch type.` with the latest ECS CLI version (1.19.0) while deploying to an ECS cluster with EC2 instances (not Fargate).
Note: Reverting to version 1.18.1 fixed the issue.

#### Description
* `ecs-cli compose --file cicd.docker-compose.yml --ecs-params ecs-params.yml --cluster $AWS_ECS_CLUSTER_NAME service create --create-log-groups`
* Version 1.19.0
* Platform: Linux in Docker

#### Expected Behavior
To set the Platform Version to `null` in case of EC2 setup

#### Observed Behavior
Sets Platform Version to `latest`

**Comment by allisaurus** [comment]
Thanks for reporting this @minaeakhalil ! We're working on a fix for this.

**Comment by bmelanson** [comment]
I noticed this same issue today, as my automated builds suddenly stopped working.  Using similar `ecs-cli compose service create` which has begun to fail. 
 
Confirm rolling back to v1.18.1 restored prior behavior.

Thanks for the quick response @allisaurus

**Comment by bvtujo** [comment]
We've reverted the problematic behavior in our latest release ([v1.19.1](https://github.com/aws/amazon-ecs-cli/releases/tag/v1.19.1)) but in the course of this, identified another bug which affects users who rely on `ecs-cli compose up` and wish to add an EFS volume. We're tracking this related bug in #1043.

**Comment by bvtujo** [comment]
Please let us know if you're still seeing problems related to this issue by reopening or commenting here.

**Comment by minaeakhalil** [comment]
Thanks for fixing it that quickly.

I've tested the latest version (1.19.1) and confirmed that it's fixed.

Thanks again :)
