### ISSUE TITLE
`ecs-cli compose up` with Fargate and EFS sets the wrong platform version

### ISSUE THREAD

**Issue by bvtujo** [aws/amazon-ecs-cli#1043]
#### Summary

While resolving #1040, we discovered a bug in the implementation of `compose up` which will set the platform version incorrectly for Fargate launch types if an EFS volume is specified in ecs-params.yml. 

This affects all versions of the ECS CLI on all platforms after v1.18.1.

**Comment by docktermj** [comment]
@bvtujo I'm not sure how "hot" this issue is, but it is a blocker for the work I'm doing at https://github.com/Senzing/docker-compose-aws-ecscli-demo  Any progress would be appreciated.

**Comment by bvtujo** [comment]
@docktermj Thanks for letting us know! We're working on getting a fix out and should have it ready sometime soon pending some internal ops work. You may have seen the open external contributor PR #1056

**Comment by docktermj** [comment]
@bvtujo Thank you for responding.  I'm excited to get the fix!  

To help my plan my work, when you say "sometime soon",   is that a few days from now,  weeks, months?   Just let me know so I can plan my work accordingly.   Thank you!

**Comment by bvtujo** [comment]
Sorry about that, we're aiming to have a patch out in the next week and a half or so. I apologize for not being clear up front, but we do intend to have movement on this in our next patch release, which looks to be ready by the first week of July.

**Comment by docktermj** [comment]
@bvtujo Excellent news!  Thank you!

**Comment by docktermj** [comment]
Glad to see progress. Thank you!

**Comment by docktermj** [comment]
@bvtujo Any estimate of public availability?

**Comment by bvtujo** [comment]
Hi @docktermj, this is publicly available right now as of [v1.20.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v1.20.0). 

Please open an issue or PR for any bugs you might find in this release!

**Comment by docktermj** [comment]
Thank you, @bvtujo !
