### ISSUE TITLE
"Restart" all containers in a service

### ISSUE THREAD

**Issue by carlosrodf** [aws/amazon-ecs-cli#1054]
#### Context

The idea is to have a command that forces all containers in a service to be replaced without actually changing anything in the task definition. Just force a replacement of all currently running containers in a service.

Something like this
```
ecs-cli compose service <service> restart
```
#### Alternatives

We can acomplish this by creating a new task definition revision that is an exact copy of the current task definition and then updating the ecs service with this new task definition. Even though nothing changed ecs will replace all the containers currently running

**Comment by efekarakus** [comment]
Hi @carlosrodf, do you have a scenario in mind for when you'd use this command? for me to understand why it'd be needed.

Thanks!

**Comment by carlosrodf** [comment]
@efekarakus I know its a weird use case but i've had clients ask to do it several times, mostly as a debugging mecanism. Sometimes there is race condition and "restarting" the service helps get the app out of that error state while testing.

**Comment by allisaurus** [comment]
@carlosrodf  you can redeploy the tasks in your service w/o a new task definition by using the [`forceNewDeployment`](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html#ECS-UpdateService-request-forceNewDeployment) flag on UpdateService.

In the ecs-cli, this is supported by using the [`--force-deployment`](https://github.com/aws/amazon-ecs-cli/blob/mainline/ecs-cli/modules/commands/flags/flags.go#L136) flag on `ecs-cli compose service up`. 

Let me know if that works for you!

**Comment by allisaurus** [comment]
Closing since this capability it supported (per above), but feel free to reopen if there are additional questions.
