### ISSUE TITLE
make build ecs-cli/main.go:19:2: cannot find package "github.com/aws/amazon-ecs-cli/ecs-cli/license"

### ISSUE THREAD

**Issue by rakeshrc** [aws/amazon-ecs-cli#106]
I tried make build and i get the below error:

$ make build
. ./scripts/shared_env && ./scripts/build_binary.sh ./bin/local
ecs-cli/main.go:19:2: cannot find package "github.com/aws/amazon-ecs-cli/ecs-cli/license" in any of:
	/usr/lib/golang/src/github.com/aws/amazon-ecs-cli/ecs-cli/license (from $GOROOT)
	/root/amazon-ecs-cli/ecs-cli/vendor/src/github.com/aws/amazon-ecs-cli/ecs-cli/license (from $GOPATH)
ecs-cli/main.go:20:2: cannot find package "github.com/aws/amazon-ecs-cli/ecs-cli/modules/command" in any of:
	/usr/lib/golang/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/command (from $GOROOT)
	/root/amazon-ecs-cli/ecs-cli/vendor/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/command (from $GOPATH)
ecs-cli/main.go:21:2: cannot find package "github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app" in any of:
	/usr/lib/golang/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app (from $GOROOT)
	/root/amazon-ecs-cli/ecs-cli/vendor/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app (from $GOPATH)
ecs-cli/main.go:22:2: cannot find package "github.com/aws/amazon-ecs-cli/ecs-cli/modules/version" in any of:
	/usr/lib/golang/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/version (from $GOROOT)
	/root/amazon-ecs-cli/ecs-cli/vendor/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/version (from $GOPATH)
make: *** [bin/local/ecs-cli] Error 1

**Comment by uttarasridhar** [comment]
This issue was addressed with the go update in #119. Please get the latest commit and try build again. Note: It requires you to update to go1.5+
