### ISSUE TITLE
yaml env_file parsing preserves too much white space

### ISSUE THREAD

**Issue by markriggins** [aws/amazon-ecs-cli#107]
```
worker:
  env_file:
     - file1 
     - file2 

```
The trailing whitespace causes ecs_cli to try to open the file 'file1 '   (with a space in the name)

```docker-compose``` accepts and trims

**Comment by uttarasridhar** [comment]
Thanks for the bug report.
This is fixed in #121 and released in [v0.4.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v0.4.0).
