### ISSUE TITLE
Memory issue while deploying ELK stack on fargate using ecs-cli and docker-compose

### ISSUE THREAD

**Issue by mudassirshahzad** [aws/amazon-ecs-cli#1102]
#### Summary
When deploying the ELK stack on fargate, the service logs show "max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]" and  when run on fargate using docker-compose.yml

#### Description

Using the following ecs-cli  command

* Which specific command was run? (Example: `ecs-cli up --capability-iam --size 2 --launch-type EC2`)
> ecs-cli compose --project-name elk-service --file ./bff-elk-service/docker-compose-deploy.yml --ecs-params ./bff-elk-service/ecs-params.yml service up --target-group-arn arn:aws:elasticloadbalancing:us-east-1:266045683658:targetgroup/TG-ELK-Carbee-Staging/22aaa5b093d6a2b7 --container-name elk-service --container-port 5601 --create-log-groups --force-deployment --cluster-config carbee-staging-configuration --ecs-profile carbee-staging-profile

* Which version of the CLI you are using? 
**ecs-cli version 1.20.0 (7547c45)**

* Which version of Go are you using? 
**Not using Go**.

* What platform are you using to run ECS CLI commands? 
**macOS**

#### Config files

* docker-compose.yml

version: '3'
services:
  elk-service:
    image: 266045683658.dkr.ecr.us-east-1.amazonaws.com/bff-elk-service:latest
    ports:
      - "9200:9200"
      - "5601:5601"
      - "5044:5044"
    environment:
      - ES_JAVA_OPTS=-Xmx2g -Xms2g
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: awslogs
      options:
        awslogs-group: Carbee-Staging
        awslogs-region: us-east-1
        awslogs-stream-prefix: elk-service

* ecs-params.yml

version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 30GB
    cpu_limit: 4096
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-0f5c86ee2b5dafe43
        - subnet-0dd2ff33b2c17470e
      security_groups:
        - sg-0997c51ed1e91f6f8
      assign_public_ip: ENABLED

* ~/.ecs/config

#### Expected Behavior
ELK stack startsup and Kibana is accessible on port 5601

#### Observed Behavior

Fargate service and tasks start successfully but the ELK logs show the following two errors:
max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

**Comment by mudassirshahzad** [comment]
@SoManyHs Coud you please shed some light

**Comment by SoManyHs** [comment]
Hi @mudassirshahzad,
Unfortunately, the solutions for tweaking `vm.max_map_count` involves changing the `etc/sysctl.conf` file on the host or running docker exec, neither of which are supported in Fargate.

However, you may be able to disable the `mmap` setting in ElasticSearch, which gets rid of the `max_map_count` setting requirement. 

See: 
- https://www.elastic.co/guide/en/elasticsearch/reference/master/_maximum_map_count_check.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/index-modules-store.html#allow-mmap

Hope that helps!

**Comment by SoManyHs** [comment]
Also see previous issue: https://github.com/aws/amazon-ecs-cli/issues/425#issuecomment-366332542

**Comment by mudassirshahzad** [comment]
Thank you @SoManyHs. Yeah I had a look at the issue #425
