### ISSUE TITLE
Graviton2 instance type are detected as x86 instead of arm64

### ISSUE THREAD

**Issue by pingleig** [aws/amazon-ecs-cli#1113]
#### Summary

When creating cluster using ecs-cli, it gets AMI based on instance type. However the logic only supports a1 instances, but not [graviton2 instances](https://aws.amazon.com/ec2/instance-types/). I think the original code is from #695 (and hi @PettitWesley)

https://github.com/aws/amazon-ecs-cli/blob/mainline/ecs-cli/modules/clients/aws/amimetadata/client.go#L107

```go
func isARM64Instance(instanceType string) bool {
	r := regexp.MustCompile("a1\\.(medium|\\d*x?large)")
	if r.MatchString(instanceType) {
		return true
	}
	return false
}
```

#### Description

Command I run

```bash
ecs-cli up --capability-iam --size 2 --instance-type m6g.medium --cluster ecs-graviton2--region us-west-2
```

Version is 

```text
ecs-cli version 1.20.0 (7547c45)
```

#### Config files

N/A

#### Expected Behavior

The auto scale group contains 2 m6g.medium instances

#### Observed Behavior

Failed to launch EC2 instance because x86 AMI is used for arm64 instance

I can make a PR to fix that regex, but are there are any plan to publish [new releases](https://github.com/aws/amazon-ecs-cli/releases)?

**Comment by allisaurus** [comment]
@pingleig thanks for reporting this and offering to submit a PR! We can and will publish new releases, though the cadence is more more "as-needed" than regular/scheduled these days. Merging in a fix for this issue would def bump up the priority of a new release, so if you're still willing to submit a PR please do so and "@" me so I can review it sooner than not.
