### ISSUE TITLE
Configure profiles per directory and/or extract from ~/.aws/config file

### ISSUE THREAD

**Issue by Dudemullet** [aws/amazon-ecs-cli#112]
I thinks it's kind of bothersome to have to run `ecs-cli configure -p [profile] --cluster [cluster-name]` everytime I ump between project directories. Not only that but, why not save the `cluster` in the `~/.aws/config` profile, and just extract it from there when using `ecs-cli configure -p [profile]` ?

I don't know if I'm missing some sort of configuration shortcut or whatnot, but if anyone else has this issues and actually running `ecs-cli configure` is the only solution we have right now, I'd happily submit a PR for something like:
## Proposal 1

`ecs-cli configure -p [profile]` - Extracts all the needed variables in the `~/.aws/config` [profile] to set in `~/.ecs/config` like:
- cluster
- aws_profile
- region
- aws_access_key_id
- aws_secret_access_key
- compose-project-name-prefix
- compose-service-name-prefix
- cfn-stack-name-prefix
## Proposal 2

running `ecs-cli configure` on a directory will try to populate the configuration via a projects local `./.ecs/config` file.

**Comment by MaerF0x0** [comment]
# Proposal 3

`ecs-cli <command> --cluster [name]`

**Comment by skwp** [comment]
Huge 👍 having the cluster as a global config makes it impossible to deploy to multiple ecs clusters in a pipeline environment like jenkins because each job would overwrite the global config as it deploys.

**Comment by skwp** [comment]
Proposal 3 is the most sane to me. Each command should take --cluster as an arg and override the global.

**Comment by sveneh** [comment]
I'm also in favor of proposal 3, but it also needs a global `--region` parameter for full flexibility

**Comment by pjoe** [comment]
I vote for proposal 2 :)

It very much matches how eb-cli deals with this.

**Comment by fdeschenes** [comment]
I also vote for proposal 2.

**Comment by Dudemullet** [comment]
Hey all, I haven't given up on this issue. But after numerous attempts at trying to downgrade my go version (and not being able to get gvm running), understanding how Go's (and godep) dependency management work and most importantly trying to learn Go. It's proven pretty difficult for me to just jump in on this project and contribute. I will try on my christmas break to get back on board though.

But right now Go/godep has me like:

![jackie-chan-wtf](https://cloud.githubusercontent.com/assets/491242/21086057/80891190-bfde-11e6-8d7a-be5e864cb35e.jpg)

**Comment by kidanekal** [comment]
I also vote for proposal 2.

**Comment by yinshiua** [comment]
Added proposals to support multiple clusters configuration. Please give us some feedback. Thanks! https://github.com/aws/amazon-ecs-cli/issues/253

**Comment by yinshiua** [comment]
Released in v1.0.0
