### ISSUE TITLE
Support arm64 builds

### ISSUE THREAD

**Issue by SoManyHs** [aws/amazon-ecs-cli#1128]
#### Context

Currently, the ecs-cli is only being built for amd64 and windows. It would be helpful to support an arm64 binary as well, given that the ecs-cli is used in the [codebuild image](https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/2.0/Dockerfile#L123).

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by bvtujo** [comment]
Closing as we do have Arm releases in our pipeline.
