### ISSUE TITLE
ecs-cli sunsetting?

### ISSUE THREAD

**Issue by dfuentes77** [aws/amazon-ecs-cli#1129]
Just wondering if this project is no longer maintained and will it refer to copilot for all future use?

If so, I'm sad that so many features that this project supports is not yet supported in copilot.  So there will be this huge gap for some users.

One major feature that I'm waiting for is EC2 launch type, but there are a number of others.

**Comment by gshpychka** [comment]
This is sad indeed. `ecs-cli local` is so great for testing. If anyone know any alternatives that would create a docker-compose file from a task definition, I would be grateful.

**Comment by efekarakus** [comment]
Hi folks 👋   

Thanks for the issue! For the future of Compose+ECS, check out the [ECS plugin for Docker Compose](https://docs.docker.com/cloud/ecs-integration/) if you haven't seen it. I believe there are gaps there as well compared to the ECS CLI, but they also support newer features. Currently, we're mostly merging bug fixes or community contributions for the ECS CLI and are working towards closing these use case  gaps (such as local testing) for the AWS Copilot CLI and Docker Compose over time.   
Apologies for the inconvenience 🙇 , the ECS CLI repository isn't going away so the existing features will work as is, in the mean time we're  expanding the feature set for the [AWS Copilot CLI](https://aws.github.io/copilot-cli/), [Docker Compose](https://docs.docker.com/cloud/ecs-integration/), and [AWS CDK](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ecs-readme.html).

**Comment by gshpychka** [comment]
My only wish is for #1121 to be fixed :)

**Comment by keen99** [comment]
so https://docs.docker.com/cloud/ecs-integration/ is dead.  and the ecs-cli project is zombie, apparently.

```Cloud integrations
Docker Compose's integration for Amazon's Elastic Container Service and Azure Container Instances has retired. The integration documentation is no longer available through the Docker Docs site.

However, you can still access the relevant documentation in the [Compose CLI repository](https://github.com/docker/compose-cli/tree/main/docs).```


and copilot cli, as far as I can tell, doesnt bother to tackle the "run a TD locally" problem.  sad.
