### ISSUE TITLE
ecs-cli up does not support multiple security groups , seemingly incorrect error message on failure

### ISSUE THREAD

**Issue by MaerF0x0** [aws/amazon-ecs-cli#113]
I am trying to get my `ecs-cli up ...` command to work with multiple security groups. using the `--security-group` tag multiple times just means the last one is used.  Tried the comma separated list version like the subnets and it gave an odd error:

Command looks like:

```
ecs-cli up \
  --debug \
  --capability-iam \
  --size "1" \
  --instance-type "m4.large" \
  --keypair "${USE_KEY}" \
  --security-group "sg-<sg1>,sg-<sg2>" \
  --vpc "vpc-<vpc1>" \   #Note, not our default vpc
  --subnets "${USE_SUBNETS}"
```

And logs: 

```
DEBU[0214] Parsing event                                 id=EcsInstanceLc-CREATE_FAILED-2016-05-26T17:27:09.624Z reason=The security group 'sg-<sg1>,sg-<sg2>' does not exist in default VPC 'vpc-<vpc1>' resourceType=AWS::AutoScaling::LaunchConfiguration status=CREATE_FAILED
ERRO[0214] Failure event                                 reason=The security group 'sg-<1>,sg-<2>' does not exist in default VPC 'vpc-<vpc1>' resourceType=AWS::AutoScaling::LaunchConfiguration
ERRO[0214] Error executing 'up': Cloudformation failure waiting for 'CREATE_COMPLETE'. State is 'ROLLBACK_IN_PROGRESS'
```

It's complaining the security group does not exist in our default vpc, however we specified the correct vpc in the command.    At the very least there is an error involved in the error message because that was not the vpc we specified. 

Is there a way to get multiple security groups supported?

**Comment by ryohang** [comment]
Shouldn't it be as same as [--azs availability_zone_1,availability_zone_2] ,  [--subnets subnet_1,subnet_2] ?

**Comment by MaerF0x0** [comment]
@ryohang  yes that would be the desired functionality. However, as you can see in the error logs, it seems to treat the comma separated list of groups as a single string.

**Comment by Gontrum** [comment]
I have the same problem. When using default VPC multiple security-groups are working (with comma separated syntax). When using a VPC other than default it got the same error message like MaerF0x0
