### ISSUE TITLE
Parsing multiline compose files doesn't work

### ISSUE THREAD

**Issue by schickling** [aws/amazon-ecs-cli#114]
Consider the following `docker-compose.yml` file:

```yaml
backend-proxy:
  image: schickling/nginx-envtpl
  environment:
    NGINX_WORKER_RLIMIT_NOFILE: 96000
    NGINX_WORKER_CONNECTIONS: 10000
    NGINX_CONFIG_TEMPLATE: |
      worker_processes auto;
      worker_rlimit_nofile {{ NGINX_WORKER_RLIMIT_NOFILE }};
      error_log /dev/stdout info;

      events {
          worker_connections {{ NGINX_WORKER_CONNECTIONS }};
          use epoll;
          multi_accept on;
      }

      http {
          ...
      }
  ports:
    - "60000:60000"
```

The previous fails whereas the following works:

```yaml
backend-proxy:
  image: schickling/nginx-envtpl
  ports:
    - "60000:60000"
  environment:
    NGINX_WORKER_RLIMIT_NOFILE: 96000
    NGINX_WORKER_CONNECTIONS: 10000
    NGINX_CONFIG_TEMPLATE: |
      worker_processes auto;
      worker_rlimit_nofile {{ NGINX_WORKER_RLIMIT_NOFILE }};
      error_log /dev/stdout info;

      events {
          worker_connections {{ NGINX_WORKER_CONNECTIONS }};
          use epoll;
          multi_accept on;
      }

      http {
          ...
      }
```

I suppose this a problem in the YAML parsing part?

**Comment by uttarasridhar** [comment]
Thanks for reporting the bug.
This is addressed in #121 and released in [v0.4.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v0.4.0).

I tried it out and the task definition was correctly created with the following environment variables. Let us know if you still run into issues.
             "environment": [
                    {
                        "name": "NGINX_CONFIG_TEMPLATE", 
                        "value": "worker_processes auto;\nworker_rlimit_nofile {{ NGINX_WORKER_RLIMIT_NOFILE }};\nerror_log /dev/stdout info;\n\nevents {\n    worker_connections {{ NGINX_WORKER_CONNECTIONS }};\n    use epoll;\n    multi_accept on;\n}\n\nhttp {\n    ...\n}\n"
                    }, 
                    {
                        "name": "NGINX_WORKER_CONNECTIONS", 
                        "value": "10000"
                    }, 
                    {
                        "name": "NGINX_WORKER_RLIMIT_NOFILE", 
                        "value": "96000"
                    }
]
