### ISSUE TITLE
YAML parsing issues

### ISSUE THREAD

**Issue by jpetazzo** [aws/amazon-ecs-cli#13]
ECS CLI uses go-gypsy, which only supports a limited subset of YAML.

This causes a few issues:

- #3 (arrays specified as `[1,2,3]` don't work)
- #4 (single quotes around strings don't work)
- #12 multi-line arrays only work if there is extra indentation

Switching to e.g. http://gopkg.in/yaml.v2 (used by Compose) should address those issues.

**Comment by jpetazzo** [comment]
Note: I talked about this today with @uttarasridhar; and if I remember well, she mentioned a potential licensing issue with gopkg.in/yaml.v2. To be continued!

**Comment by errordeveloper** [comment]
It's just a complete non-sense, I know YAML has pretty complex syntax, but most features are in use widely.

**Comment by jdamick** [comment]
+1 indentation issues in port example bit me too..

**Comment by kapilt** [comment]
re gopkg.in/yaml.v2 license, its lpgl with an additional static linking clause such that a static binary does not run afoul of license conveyance issues.

**Comment by kapilt** [comment]
ibm and pivotal have been working on this as an apache2 licensed replacement. https://github.com/cloudfoundry-incubator/candiedyaml

**Comment by errordeveloper** [comment]
@kapilt +1

**Comment by errordeveloper** [comment]
Any takers? ...sounds like swapping the parser shouldn't be too hard, right?

**Comment by rprieto** [comment]
Swapping parsers sounds great. In the meantime, maybe the `ecs-cli` docs should clearly state the limitations of the current parser, i.e. it doesn't support regular `docker-compose.yml` files.

**Comment by sporokh** [comment]
still not fixed?

**Comment by jesucarr** [comment]
@sporokh I just run into this issue, so no, still not fixed :(

**Comment by sporokh** [comment]
@jesucarr Thanks for info. Don't know why AWS takes it so long.

**Comment by uttarasridhar** [comment]
Migrated to libcompose which uses cloudfoundry-incubator/candiedyaml parser for marshalling and unmarshalling YAML.
This issue was fixed in #121 and released in [v0.4.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v0.4.0).

**Comment by errordeveloper** [comment]
Excellent!
