### ISSUE TITLE
Lock down version numbers

### ISSUE THREAD

**Issue by joenap** [aws/amazon-ecs-cli#131]
Hi,

After the rollout of 0.4.0, we experienced problems with the normalization of the service name.  We noticed that the issue was fixed with 0.4.1.

Given this, we went to lock down the secs-cli version number.  It wasn't immediately obvious how to do that.

We use the suggested install method:
$ sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest

I attempted to change latest to the previous 0.3.0 version that worked:
$ sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-0.3.0

But that didn't work.  Is there a method to retrieve a specific version number of the cli?

Thanks

**Comment by samuelkarp** [comment]
The correct historical link to v0.3.0 is https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-v0.3.0 (and a md5 sum is available at https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-v0.3.0.md5 for integrity checking when you download).

**Comment by joenap** [comment]
Great, thanks for the prompt reply!
