### ISSUE TITLE
Error attempting to ecs-cli compose up with local images

### ISSUE THREAD

**Issue by ecejas** [aws/amazon-ecs-cli#132]
Hi @uttarasridhar . 

This is a question.
When I run $ecs-cli compose --file prod.yml up
I get this error:

> ERRO[0000] Error registering task definition             error=ClientException: Container.image should not be null or empty.
	status code: 400, request id: d848cf4a-4a09-11e6-bf3e-a3efd4753c7a family=ecscompose-axe
ERRO[0000] Create task definition failed                 error=ClientException: Container.image should not be null or empty.
	status code: 400, request id: d848cf4a-4a09-11e6-bf3e-a3efd4753c7a
FATA[0000] ClientException: Container.image should not be null or empty.

This is my compose file (prod.yml):

version: '2'
services:
  data:
    image: tianon/true
    volumes:
      - /var/lib/postgresql
  db:
    restart: always
    image: postgres
    volumes_from:
      - data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    depends_on:
      - data

  web:
    restart: always
    image: 4a52959fff90
    expose:
      - "8000"
    volumes:
      - ./axeproject:/code
    env_file:
      - ./env-vars/base.env
      - ./env-vars/base-secrets.env
      - ./env-vars/local.env
      - ./env-vars/local-secrets.env
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  nginx:
    restart: always
    image: c5a5c68ac04b
    volumes:
      - .:/usr/src/app
    ports:
      - "80:80"
    links:
      - web:web

web and nginx are local images. Can I use local images to deploy to aws?

Thanks!

**Comment by uttarasridhar** [comment]
Hello, @ecejas. Unfortunately we don't support local images as of v0.4.1 release.
You would have to upload the image to a repository (either private or public) and provide the repo url in the `image` option. The syntax for specifying the image can be found [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#standard_container_definition_params).

**Comment by ecejas** [comment]
Thanks for the quick response!
