### ISSUE TITLE
Feature request: allow to set minimum and maximum memory capacity for a container from a compose file

### ISSUE THREAD

**Issue by tallavi** [aws/amazon-ecs-cli#145]
Per @samuelkarp's request here: https://github.com/aws/amazon-ecs-agent/issues/155

I'm opening this issue.

I'm using **ecs-cli compose** to run my containers and it would be great if we could set memory reservation value that is different from the hard limit.

I believe that the compose spec doesn't include such a field, so it can either be a parameter to the command line (no hard limit - treat the memory value as soft limit instead) or just a deviation from the standard. Personally - I don't really mind. 

Thanks!

**Comment by andreykats** [comment]
+1

**Comment by bahjak1** [comment]
+1

**Comment by joeboyscout04** [comment]
Yep, just setting up our containers and this would be a great addition to the compose file syntax.
