### ISSUE TITLE
ERRO[0000] Error initializing: key-value delimiter not found: -

### ISSUE THREAD

**Issue by akarasev** [aws/amazon-ecs-cli#146]
Any `ecs-cli` command produces the error:

> ERRO[0000] Error initializing: key-value delimiter not found: -

For example,

> $ ecs-cli ps

**Comment by nvtkaszpir** [comment]
to workaround this issue download specific version - replace `latest` with the desired tag, for example `v0.4.1`, like this for linux:

https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-v0.4.1

**Comment by nvtkaszpir** [comment]
uh forgot to add, check out your ``~/.ecs/config`` file, it may have corrupted entries. Remove offending lines ore delete it completely.

**Comment by akarasev** [comment]
You are absolutely right. I have some junk text (the symbol "-") in the end of `~/.ecs/config`. I've removed it and it solved my problem. It's weird, because I've never edited that file manually.

Thank you, Michał!

**Comment by nvtkaszpir** [comment]
Well, we had exackly the same issue on centos 7. Config file newer was edites manually and apparetly some junk was added to it.

**Comment by jedi4ever** [comment]
same here - it was the ecs-cli configure (did not have any settings or aws variables)
it only asked for a clustername and saved the corrupt file.

**Comment by mtomas** [comment]
any plans to fix the latest version ? quite annoying bug, makes management of multiple clusters problematic during various automation scripts.

**Comment by danielgrigg** [comment]
Would be good to fix this, it's non-obvious what the root cause is when running commands.
