### ISSUE TITLE
complex commands when using `ecs-cli compose run [container] [command]`

### ISSUE THREAD

**Issue by pgeez** [aws/amazon-ecs-cli#148]
I cannot get the following command to run on ECS:

`ecs-cli compose run django_command python,manage.py,migrate`

because it is mis-parsed as the following

![image](https://cloud.githubusercontent.com/assets/1369475/17843547/1f7dc1a4-67e4-11e6-9e84-2c5bc8cca72f.png)

It should be parsed as an array, in accordance with the behavior of the ECS web interface.

Is there **any** way to run commands via `ecs-cli` without defining brand new tasks that can have multiple arguments?

**Comment by pgeez** [comment]
does something like this work?

see: https://github.com/aws/amazon-ecs-cli/blob/master/ecs-cli/modules/aws/clients/ecs/client.go#L405

replace
```
Command: aws.StringSlice([]string{command}),
```

with 
```
Command: aws.StringSlice(strings.Split(command, ",")),
```

**Comment by jsh2134** [comment]
you could try putting that command into a shell script and calling that

$ cat migrate.sh
```
#/bin/sh
python manage.py migrate
```

ECS Command: migrate.sh

**Comment by yinshiua** [comment]
The PR has been merged. Resolving...
