### ISSUE TITLE
Multiple docker-compose.*.yml files

### ISSUE THREAD

**Issue by sjbrown** [aws/amazon-ecs-cli#149]
As recommended here, https://docs.docker.com/compose/production/ , I've got multiple .yml files, but apparently `ecs-cli compose` doesn't mimic `docker-compose`'s behaviour in this use case.

**Feature Request**
I'd like to do this when running on my development machine
`docker-compose -f docker-compose.yml -f docker-compose.development.yml up`
And this to deploy to ECS:
`ecs-cli compose -f docker-compose.yml -f docker-compose.production.yml up`

**Current Workaround**
Instead, it looks like I'll have to duplicate all the docker-compose.yml file contents in my docker-compose.production.yml file.

**Comment by uttarasridhar** [comment]
Thanks for the feature request. This is currently being tracked in #57.
