### ISSUE TITLE
Support for networks / net param 

### ISSUE THREAD

**Issue by KrzysztofZalasa** [aws/amazon-ecs-cli#153]
Hi, 

Current version of ecs-cli doesn't support network model defined in docker-compose.yml. It means, that all tasks created by ecs-cli has to use brigde networking (default one) which cause performance issues under high load. 

ECS task definition supports Network Mode and it would be nice to implement it also in ecs-cli.

Regards,
Krzysiek

**Comment by lougreenwood** [comment]
+1

I'm trying to run two separate projects on one host, a search server and an app server, they're separated as the search server will need restarting much less frequently than app deployments.

So far, the only way I can get the projects to communicate each other is by defining a shared network for 2 containers to use, but it appears that ecs-cli doesn't support this.

I'm starting to wonder whether it's just easier to run docker swarm on an EC2 instance and forgo all of the hassle of ecs-cli...

**Comment by MichaelMackus** [comment]
:+1:  this was the deal breaker for me for ecs-cli. There's no point in using `links` since they are deprecated, not to mention proper network_mode support being much much easier to setup.

**Comment by panga** [comment]
+1

**Comment by jonydev** [comment]
I'm facing the same problem in my team. Network mode still not supported,  is there any other solution except "docker link"?

**Comment by SoManyHs** [comment]
This was addressed in #328 and released in ECS v.1.0.0. Network mode can now be specified in the `ecs-params.yml` file under `ecs_network_mode`. Please let us know if you have any further issues!
