### ISSUE TITLE
'esc-cli up' does not work with own security group

### ISSUE THREAD

**Issue by Pinny3** [aws/amazon-ecs-cli#154]
I am creating a container-security-group doing this:

aws ec2 create-security-group —no-dry-run --group-name docker-security-group --description "The docker security group providing port 22, 80, 8080, and 9117 to everyone" --vpc-id vpc-177fc77e

aws ec2 authorize-security-group-ingress --group-name docker-security-group --protocol tcp --port 8080 --cidr 0.0.0.0/0
aws ec2 authorize-security-group-ingress --group-name docker-security-group --protocol tcp --port 9117 --cidr 0.0.0.0/0
aws ec2 authorize-security-group-ingress --group-name docker-security-group --protocol tcp --port 22 --cidr 0.0.0.0/0
aws ec2 authorize-security-group-ingress --group-name docker-security-group --protocol tcp --port 80 --cidr 0.0.0.0/0

If I try to use this new created security-group for setting up a cluster with ecs-cli by issuing the command 

ecs-cli up --keypair awskey-frankfurt --capability-iam --size 2 --instance-type t2.medium  --security-group docker-security-group

I receive a timeout without any further warnings:

INFO[0000] Created cluster                               cluster=imprintservice-cluster
INFO[0000] Waiting for your cluster resources to be created 
INFO[0000] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
[...]
ERRO[1510] Error executing 'up': Timeout waiting for stack creation to complete 

The cluster has been setup, but without any instances. 

If I set up the cluster without mentioning the security-group the cluster is set up properly together with the required ec2-instances.

What am I doing wrong?

**Comment by meyerson** [comment]
have you tried specifying the vpc_id as well ?

**Comment by yinshiua** [comment]
If you wish security group  in the ecs-cli up command, you will also need to specify vpc and subnets.
We are working on better error messages.
