### ISSUE TITLE
env_file doesn't support empty environment variables

### ISSUE THREAD

**Issue by sixcorners** [aws/amazon-ecs-cli#156]
Setting environment variables to empty strings doesn't seem to work.
I'm using the env_file docker-compose.yml directive.
There is a line in the env_file that looks like this:

    SOME_SETTING=

**Comment by uttarasridhar** [comment]
Can you give us more information about
* which version of the ecs-cli are you using?
* https://docs.docker.com/compose/compose-file/#/environment : "Environment variables with only a key are resolved to their values on the machine Compose is running on." Did you want the variable resolved or left empty?

**Comment by sixcorners** [comment]
At the time I think I was using 0.3.0.
I want the variable resolved to an empty string.
I think environment: works differently then env_file: in this case. When I used docker-compose locally env_file creates an environment variable set to an empty string.
I haven't tested anything with the normal environment: setting.

**Comment by chafikhnini** [comment]
I've just had the same problem (ecs-cli version 0.4.3 (c6ea81e)). I have a envfile containing :

`MY_ENV_VARIABLE`

I have the equivalent env variable on my system that equals an empty string and when I execute the `ecs-cli` command I have the following WARN message : 

`WARN[0000] Skipping unresolved Environment variable...   key name=MY_ENV_VARIABLE`

Yet, my application expects this env variable to be resolved as empty, not ignored at all.
