### ISSUE TITLE
Allow providing User Data to `ecs up`

### ISSUE THREAD

**Issue by 2opremio** [aws/amazon-ecs-cli#16]
We (at http://weave.works) would like to have a new flag in `ecs up` for providing [User Data](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html)  so that we can customize the EC2 instances of the cluster.

Context:

In order to be able to deploy an ECS cluster talking to [Weave Scope as a cloud service](http://scope.weave.works) we need to [add custom User Data to the EC2 instances](https://github.com/weaveworks/guides/blob/d61828b8d60dadd033d971660676313b0fbe13a1/aws-ecs/setup.sh#L129).

**Comment by vultron81** [comment]
+1

**Comment by 2opremio** [comment]
@samuelkarp Would you be open for a PR implementing this?

**Comment by samuelkarp** [comment]
@2opremio, we're currently looking into how we'd like to support this use-case.  If you want to send a PR, we can definitely take a look, but we want to make sure we can support the different types of content that can be set as user data.

**Comment by 2opremio** [comment]
@samuelkarp My plan was just to append whatever was provided to a command line flag (e.g. `--extra-user-data`) to the [existing User Data script](https://github.com/aws/amazon-ecs-cli/blob/master/ecs-cli/modules/aws/clients/cloudformation/template.go#L414-L419). 

Since you have [bigger plans](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AmazonLinuxAMIBasics.html#supported-user-data-formats), I will just stay put on this one.

**Comment by kaihendry** [comment]
I'm looking for support for this feature since I don't see another way of setting up monitoring agents like http://docs.datadoghq.com/integrations/ecs/ & persistant mounts otherwise.

Else I guess I would have to create forks of amazon-ecs-optimized images, which is a little annoying to do.

**Comment by schickling** [comment]
+1

**Comment by kristianpaul** [comment]
+1

**Comment by danknittle** [comment]
+1 Any update on this?

**Comment by rms1000watt** [comment]
+1 Updates?

**Comment by deadanon** [comment]
This would save me from manually updating the CloudFormation template of the cluster each time I want to make a minor User-Data change.

**Comment by amit-bridg** [comment]
how do i add following to ecs.config for clusters created using ecs-cli up 

ECS_ENABLE_CONTAINER_METADATA=true
https://github.com/aws/amazon-ecs-agent/pull/709

It seems like simple use cases are not that easily supported and i have to keep hacking :(

**Comment by djones** [comment]
+1. Specifically need to run this:

```
echo vm.max_map_count=262144 >> /etc/sysctl.conf
```

on the host machine to make Elasticsearch happy. https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html

**Comment by codepushr** [comment]
+1 Need this for ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION :/

**Comment by komw** [comment]
+1

**Comment by PospolitaNV** [comment]
+1

**Comment by allisaurus** [comment]
Support for providing custom user data was added in [1.9.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v1.9.0). Resolving.

**Comment by PettitWesley** [comment]
@mailjunze yup that's correct. Do you think the README or command help text should be re-worded in any way? Was it unclear from those that a file argument is needed?

**Comment by mailjunze** [comment]
@PettitWesley It's mentioned in the README here but not in the official AWS docs: ecs-cli up - Specifying User Data - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-up.html#cmd-ecs-cli-up-userdata. I submitted a feedback to update it. 

I understand extra-user-data  can be shell scripts or cloud-init directives files. Shell scripts are straightforward, However, I am struggling with cloud-init directives files. May I know what should be the content and file extension for cloud-init directives files. An example file would be great.
