### ISSUE TITLE
Error on `ecs-cli up` when creating cloudformation - vPCZoneIdentifier

### ISSUE THREAD

**Issue by Dudemullet** [aws/amazon-ecs-cli#163]
When trying to create the cloudformation stack I get the error: 

```
Value '' at 'vPCZoneIdentifier' failed to satisfy constraint: Member must have length greater than or equal to 1 resourceType=AWS::AutoScaling::AutoScalingGroup
```

But I cant find in the documentation anything related to setting the `vPCZoneIdentifier`. I am setting:

`ecs-cli up --keypair *** --capability-iam --size 2 --instance-type t2.large --image-id ami-**** --vpc vpc-*** --azs us-west-2a,us-west-2c`

Full output:

```
INFO[0001] Created cluster                               cluster=devTools3
INFO[0001] Waiting for your cluster resources to be created 
INFO[0002] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
INFO[0063] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
INFO[0124] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
ERRO[0155] Failure event                                 reason=1 validation error detected: Value '' at 'vPCZoneIdentifier' failed to satisfy constraint: Member must have length greater than or equal to 1 resourceType=AWS::AutoScaling::AutoScalingGroup
```

**Comment by yinshiua** [comment]
`--azs` and `--vpc` cannot be specified together.
If you specify `--vpc`, you will also need to specify subnets.
If you specify `--azs`, the VPC will be created for you.
We are working on better error messages.

**Comment by VinceMD** [comment]
thanks. That works for me now: specifying the vpc and subnet
