### ISSUE TITLE
Unable to pull image hosted on ECR

### ISSUE THREAD

**Issue by ekimia** [aws/amazon-ecs-cli#169]
Using the preferred ecs Linux AMI image, latest rev. I did find instructions how to pull from private repos, but nothing on ECR.

**Comment by uttarasridhar** [comment]
Here are instructions to pull a Docker image available in Amazon ECR: http://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-pull-ecr-image.html

If you want to use it with ecs-cli compose, you can specify the image field as
```yml
image: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/<repository-name>[:<image-tag>]
```

**Comment by ekimia** [comment]
thanks!
