### ISSUE TITLE
Cant configure ecs-cli profile: Error initializing: Missing required argument 'cluster'

### ISSUE THREAD

**Issue by moskalyk** [aws/amazon-ecs-cli#171]
I've downloaded the most recent version of the ecs-cli. When I try to configure my profile, I get the following error.

`$ ecs-cli configure --region us-west-2 --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY --cluster devops-pipeline
ERRO[0000] Error initializing: Missing required argument 'cluster'`

I've also tried:

`$ ecs-cli configure --region us-west-2 --access-key $AWS_ACCESS_KEY_ID secret-key=$AWS_SECRET_ACCESS_KEY cluster=devops-pipeline
ERRO[0000] Error initializing: Missing required argument 'cluster'`

**Comment by yinshiua** [comment]
`$ ecs-cli configure --region us-west-2 --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY --cluster devops-pipeline` is the correct command.

I was able to repro this by setting AWS_ACCESS_KEY_ID and and leave AWS_SECRET_ACCESS_KEY as empty. Can you make sure both of the fields are set?

**Comment by moskalyk** [comment]
Thank you - I had overwritten my previous key.
