### ISSUE TITLE
Agent upgrade

### ISSUE THREAD

**Issue by kaihendry** [aws/amazon-ecs-cli#172]
Sorry, I am bit upset my cluster went down this morning due to lack of disk space.

Turns out I am not running the [latest agent 1.13.0 for automatic cleanup](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/automated_image_cleanup.html).

I spun up some new instances with ecs-cli version 0.4.4 (7e1376e) and they are exhibiting agent version **1.11.1**. Why is that possible? Why aren't we running the latest version on a new instance?

I do know there is a guide how to manually update:
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-update.html

But I am trying to orchestrate many several nodes here and this manual process is not suitable. A **new instance === the latest agent** is my expectation. So it would be good if `ecs-cli` somehow takes responsibility for Agent upgrades or shows the versions at the very least.

**Comment by kaihendry** [comment]
Also it's not clear to me how I update the **instance-type** to say 2016.09.a when creating new instances with `ecs-cli scale --size 3 --capability-iam` on an existing [upped](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-up.html) cluster.

http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container_agent_versions.html#ecs-optimized-ami-agent-versions

Do I need to bring down my cluster to update the **launch configuration**??

**Comment by kaihendry** [comment]
Blogged how I dealt with the situation. Update the agent via the console.

https://devops.spuul.com/2016-11-01/Updating_the_ECS_AMI/

Still would be nice if the ecs-cli could advertise the versions and help with this problem.

**Comment by russelldavies** [comment]
Currently, the AMI ID of the container instances are hardcoded into `amazon-ecs-cli/ecs-cli/modules/config/ami/ami.go`. This file was recently updated but is already out of date.

Ideally, the AMI chosen should be the current version, fetched from the EC2 API via the `DescribeImages` action.

**Comment by uttarasridhar** [comment]
@russelldavies: Yes, this would greatly help us automate our ami id updates.

**Comment by uttarasridhar** [comment]
@kaihendry: Thanks for your feedback.
You are right when a cluster is created using `ecs-cli up`, a launch configuration is created for that cluster with the ami id in the cli binary. And any successive `ecs-cli scale` operations spins up instances with that locked ami.

One workaround is to go to Cloudformation and update the template with the latest ami id.
But, the feature request here to have ecs-cli update the cluster to the latest ami.

**Comment by kaihendry** [comment]
I made a video to hopefully help others upgrade their cluster AMIs https://youtu.be/5YF3qJM3uHA

**Comment by SoManyHs** [comment]
Hi @kaihendry,
[Version 1.5](https://github.com/aws/amazon-ecs-cli/releases/tag/v1.5.0) of the ecs-cli now uses SSM to pull the latest AMI version when creating a cluster. (See the change [here](https://github.com/aws/amazon-ecs-cli/commit/a9d7a960dcd0ea2c57bb053a2fbe9fbbaf7f9886). Sorry about the previous frustration, and hope this helps!
