### ISSUE TITLE
Race Condition Prevents Continuous Integration tools like Jenkins from deploying to multiple clusters.

### ISSUE THREAD

**Issue by markriggins** [aws/amazon-ecs-cli#174]
By design ecs-cli can only operate against a single cluster. 

To use `ecs-cli compose create` for the hello-world on the hello-world--staging cluster, you must first run `ecs-cli configure —cluster hello-world—staging` to set the cluster.   All subsequent ecs-cli commands work against that cluster, until it is reconfigured to work on another cluster.

This is fine for individual developers, but not so good for Jenkins and other continuous integration builders, because ecs-cli stores its configuration in a **hard-coded location** ~/.ecs/config.

Simultaneous deployments they can thrash on the ~/.ecs/config file.   even worse, there is no file locking, so if the file can also get trashed afterwhich all deployments halt on all jenkins projects on the particular slave, until something fixes the file.

If the config file is trashed, then all further ecs-cli commands fail like this:

```
ecs-cli compose create
time="2016-10-26T16:20:34Z" level=error msg="Error loading config" error="key-value delimiter not found: up-\n" 
time="2016-10-26T16:20:34Z" level=fatal msg="Unable to create and read ECS Compose Project" error="key-value delimiter not found: up-\n"

```

Sensible solutions would be to honor a $ECS_CONFIG_FILE setting or —config-file flag.   Or just add a —cluster flag to the `ecs-cli` command.

**Comment by ambrons** [comment]
@markriggins Something else you could consider is building a docker image for ecs-cli and running the all your commands via the docker image.  It isn't ideal from a simplicity standpoint, but it would get you around the problem.

I've considered doing this myself.  You could even use a mounted volume for the various config files you might need and include that during the run of the command.

**Comment by markriggins** [comment]
**CONFIRMED IN PRODUCTION**   we found the wrong service running on of our production clusters dedicated to a single service.    This happened because two Jenkins builds were launched at the same time.  The first ran `ecs-cli configure --cluster service-A-production` then intended to update the service `ecs-cli compose service up`.  But in the meanwhile, the other Jenkins build ran  `ecs-cli configure --cluster service-B-production`,   so service-A wound up **running on the wrong cluster.**

Fortunately, this particular service was a webserver, and since the load balancer never expects to find it in the wrong place, it received no traffic.  But the results could have been MUCH MORE SIGNIFICANT, for example it could have placed an untested alpha release into production!!

**Comment by markriggins** [comment]
I've coded up a fix for this, (adding a --cluster flag) and will be submitting a pull request as soon as I'm done testing it.  Should be ready by no later than tomorrow.

**Comment by markriggins** [comment]
Also added a --region flag.   The --region and --cluster flags are available to compose commands such as `ecs-cli compose up`,  and also to the cluster related commands such as `ecs-cli ps`,  'up', 'down' and 'scale'.

These commands also react to $AWS_REGION and $ECS_CLUSTER variable from the environment.

[Pre-built binaries](https://github.com/markriggins/amazon-ecs-cli/releases/tag/v0.4.4-with--cluster-flag) are available for linux and OSX

**Comment by XaeroDegreaz** [comment]
Has there been any movement on this merge request? We're experiencing a similar issue in our production environment.

**Comment by markriggins** [comment]
I have a patch you can use.

**Comment by XaeroDegreaz** [comment]
I see the patch listed on your fork (0.4.4-with--cluster-flag) is that the one you mean? I was looking through the patch earlier to see if it was what I would be wanting long-term.

**Comment by XaeroDegreaz** [comment]
Actually, we just went ahead and circumvented the whole thing by changing the `HOME` environment variable before making the calls to both the `ecs-cli configure` and `ecs-cli compose` api:

In our Jenkins build script:

`env HOME=$(pwd) ecs-cli configure [......]`
`env HOME=$(pwd) ecs-cli compose [......]`

This sets the home directory (for the duration of the executed command) to the workspace for the project that is being built.

This gives us a config file for each project and avoids race conditions altogether.

**Comment by markriggins** [comment]
Yes.  We've been using it w/o issues.

**Comment by markriggins** [comment]
@XaeroDegreaz -- wondering, has this affected ecs-cli's reliance on  $HOME/.aws/credentials ?

**Comment by XaeroDegreaz** [comment]
I'm not sure -- we use roles on our instances so our Jenkins box just works without a credentials file.

**Comment by mattmccarty** [comment]
Using @XaeroDegreaz recommendation above,

`env HOME=$(pwd) ecs-cli configure [......]
env HOME=$(pwd) ecs-cli compose [......]`

I also had to copy the ~/.aws (aws-cli command line config directory) to the temporary ecs-cli home directory $(pwd).

**Comment by markriggins** [comment]
> also had to copy the ~/.aws (aws-cli command line config directory) to the temporary ecs-cli home directory $(pwd).

The problem with this is that the ~/.aws directory contains secrets that should never be copied into a GIT tree, or Jenkins WORKDIR,  where they could accidentally be leaked into Github or published as part of a Docker image due to an overly-broad COPY directive.    Yes you can use .gitignore and .dockerignore to circumvent that, but then you still have the issue of making sure that the copies have strict access control permissions.

But, if used with care, this is an acceptable workaround.   Make a separate directory for the copy, place it in the $HOME dir ~/.aws/tmp/$$ , where it will be safe from Git, Docker and other mistakes.    You can then periodically, safely run `rm -rf ~/.aws/tmp/`.    If the directory permissions on ~/.aws are set appropriately, the secrets will be as safely hidden as the other aws secrets

**Comment by XaeroDegreaz** [comment]
Jenkins has a plugin for setting AWS credentials during build time -- we don't use a credentials file.

**Comment by yinshiua** [comment]
Added proposals to support multiple clusters configuration. Please give us some feedback. Thanks! https://github.com/aws/amazon-ecs-cli/issues/253

**Comment by markriggins** [comment]
Done.  and Thankyou!!

**Comment by yinshiua** [comment]
@markriggins Thanks for providing your feedback.

There are 2 proposals, please also take a close look at the second one because we will be introducing backward incompatible changes. The second proposal is driven by the first proposal and the changes will be made together.

**Comment by markriggins** [comment]
awesome work.   Thank you Amazon for listening.

**Comment by PettitWesley** [comment]
Multiple clusters can now be configured with ECS CLI v1.0+
