### ISSUE TITLE
Version 2.0 not supported

### ISSUE THREAD

**Issue by VarunAgw** [aws/amazon-ecs-cli#179]
I am using `docker-compose config` to get rid of extends and then pass it to ecs-cli. But this command converts version from '2' to '2.0'. It would be nice if ecs cli accept it instead of throwing error.

**Comment by uttarasridhar** [comment]
We use [libcompose](https://github.com/docker/libcompose) to parse the compose yml file, and that library does a string comparison only with "2". [Reference](https://github.com/docker/libcompose/blob/3c40e1001a2646ec6f7a6613873cf5a30122a417/config/merge.go#L40).

**Comment by yinshiua** [comment]
Unsure if libcompose has plan supporting this.

Please create an issue under libcompose if you insist on having this flexability. Thanks!
