### ISSUE TITLE
Support assumed roles

### ISSUE THREAD

**Issue by Skuratau** [aws/amazon-ecs-cli#189]
A brief description of the current state. I have 2 properly configured accounts. One of them is a default (or  jump) account, the other is my test account with main environment. There is a part of _.aws/credentials_ file
```
[default]
output = json
region = eu-west-1
aws_access_key_id = "my-access-key-id"
aws_secret_access_key = "my-secret-key"

[test]
region = eu-west-1
role_arn = arn:aws:iam::my-main-account-id:role/AssumeRole-Administrator
source_profile = default
```
As i mentioned above, this configuration is working fine with AWS CLI without any issues. Not so far, I have tried to use ESC CLI. I installed and configured  ecs-cli. The command  and  _.ecs/config_ file is listed below.

**Command:**
`ecs-cli configure --region eu-west-1 -p test --cluster name-of-my-cluster`

**_.ecs/config_ file:**
```
[ecs]
cluster                     = name-of-my-cluster
aws_profile                 = test
region                      = eu-west-1
compose-project-name-prefix = ecscompose-
compose-service-name-prefix = ecscompose-service-
cfn-stack-name-prefix       = amazon-ecs-cli-setup-
aws_access_key_id           =
aws_secret_access_key       =
```

Then i tried to execute this command:
 `ecs-cli up -keypair my-keypair --capability-iam --size 1 --instance-type t2.large --port 80 --debug`
and got the response:
```
DEBU[0000] using config file: /root/.ecs/config
ERRO[0000] Error executing 'up': NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

I have the same response with other ecs-cli commands which are connected with usage of AWS credentials. Version is `ecs-cli version 0.4.5 (161017c)` which is the latest for the time being. 

Do you have any solution of this issue?

**Comment by uttarasridhar** [comment]
This was solved in the commit https://github.com/aws/amazon-ecs-cli/pull/191.
