### ISSUE TITLE
Allow specifying custom Instance Policy/Role in `ecs up`

### ISSUE THREAD

**Issue by 2opremio** [aws/amazon-ecs-cli#19]
`AmazonEC2ContainerServiceforEC2Role` may be too restrictive for certain cases.

In our (http://weave.works) particular case, we need to be able to obtain the IPs of the instances which are part of current the autoscaling group.

For context, see https://github.com/weaveworks/guides/blob/d1039713f6b65c21c59dac309e1b3ae962c478bb/aws-ecs/data/weave-ecs-policy.json#L16-L17 and https://github.com/weaveworks/integrations/blob/0cf225a9daa1c439b2e52a08198582775bb2f121/aws/ecs/packer/to-upload/peers.sh#L18-L27

**Comment by 2opremio** [comment]
@samuelkarp Would you be open for a PR implementing this?

**Comment by samuelkarp** [comment]
@2opremio, sure!

**Comment by 2opremio** [comment]
@samuelkarp I see two options here:

1. Allow changing the role to something other than [AmazonEC2ContainerServiceforEC2Role](https://github.com/aws/amazon-ecs-cli/blob/master/ecs-cli/modules/aws/clients/cloudformation/template.go#L368)
2. Allow overriding the [full instance policy](https://github.com/aws/amazon-ecs-cli/blob/master/ecs-cli/modules/aws/clients/cloudformation/template.go#L347-L371)

We could do both (1) and (2) but, if we assume we only want one option, I would go for (2) since (1) has the extra dependency of creating a managed policy in advance (if a preexisting managed policy is not good enough).

**Comment by samuelkarp** [comment]
A role can have multiple policies, so it is probably more flexible to allow additional policies.  See the [CloudFormation documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html) for information on associating multiple policies with a role.

**Comment by 2opremio** [comment]
@samuelkarp Sorry it took a while to answer. Even if we allow additional policies it would require the user to create those with a different tool (Console, AWS CLI etc ...) which can be inconvenient. In our usecase it would be more useful to allow defining the full role. Would this be OK?

I think I may find some time to do this in about a week (next week is going to be really busy for me)..

**Comment by andrew-allen** [comment]
Is there any chance of this issue getting addressed?

**Comment by SoManyHs** [comment]
We are planning on allowing a new flag, `--role`, which will allow customers to pass in the ARN of a custom IAM Role. At this time, the customer will still need to create this role outside of the ECS CLI (e.g. via Console, AWS CLI etc). We will also still attach the `AmazonEC2ContainerServiceforEC2Role` policy to this role, i.e. the customer will not be able to specify a custom IAM Policy.
