### ISSUE TITLE
 STOPPED (CannotCreateContainerError: API error (500): Untar)

### ISSUE THREAD

**Issue by hemanth7787** [aws/amazon-ecs-cli#194]
I m facing this issue from today.

![screenshot from 2017-01-25 14 01 12](https://cloud.githubusercontent.com/assets/2316704/22283322/90ab628e-e307-11e6-9fcd-b36caa849327.png)

**Comment by hemanth7787** [comment]
**Magically fixed itself.**  

![funny-amazed-cats](https://cloud.githubusercontent.com/assets/2316704/22283711/c9fe0eea-e309-11e6-90e8-dcb44317dc1c.jpg)

**Comment by simplycloud** [comment]
@hemanth7787 if you still have logs of this error and can share the compose yaml that you used to create the container, we can take a deeper look. otherwise, we will resolve and you can re-open if the issue re-occurs. thank you.

**Comment by yinshiua** [comment]
might be related to #141

**Comment by jspenc72** [comment]
<img width="629" alt="ecs-cli fail" src="https://user-images.githubusercontent.com/2913536/30969646-45952f16-a420-11e7-902b-330c9427df53.png">

**Comment by jspenc72** [comment]
<img width="1616" alt="aws-fail" src="https://user-images.githubusercontent.com/2913536/30969667-524db6b0-a420-11e7-9f0e-9fbb17ba8f8f.png">

**Comment by jspenc72** [comment]
Similar issue however when container fails to start ecs-cli never gets a response or times out so it just keeps Describing ECS Service Status Forever.

**Comment by jspenc72** [comment]
Should update it to check for failure conditions like this.

**Comment by NioTeX** [comment]
I just had the same error, it was because my Task Definition had a non existent log group set as the 'awslogs-group' parameter. Created the log group and the service started successfully.
