### ISSUE TITLE
install from homebrew

### ISSUE THREAD

**Issue by sibelius** [aws/amazon-ecs-cli#197]
we would be really nice to be able to install this cli from homebrew

`brew install aws-ecs-cli`

**Comment by uttarasridhar** [comment]
Yes you can. The command to install is `brew install amazon-ecs-cli`

**Comment by Ashtonian** [comment]
can we put this on the readme or https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI.html?

**Comment by anishpatel** [comment]
Bump for visibility.
