### ISSUE TITLE
ecs-cli cannot delete cluster resources? trying in us-west-1

### ISSUE THREAD

**Issue by GFite** [aws/amazon-ecs-cli#206]
I am following the documentation verbatim in the "Amazon ECS CLI tutorial" but my ecs-cli keeps hanging. It wants me to use --force even though I manually deleted the cluster using the console (as indicated somewhere else). 

trying ecs-cli up, down hangs on stackStatus="DELETE_IN_PROGRESS"

ERRO[0697] Error deleting cloudformation stack for cluster eventStatus-"DELETE FAILED" reason="The following resource(s) failed to delete: [Vpc]. " resource:"arn:aws:cloudformation:us-west-1:310959787714:stack/amazon-ecs-cli-setup-hydros/7bbeb140-f7a8-11e6-82d7-500c21fb2c35"

I need to use ecs-cli because I am hoping to deploy a docker-compose.yml

**Comment by yinshiua** [comment]
@GFite `ecs-cli up` uses CloudFormation to create resources (Vpc, Sg, subnet, etc). Deleting the cluster through ECS console will not help cleanup the CloudFormation stack that was created through ecs-cli. You will need to go to the CloudFormation console to delete the associate stack (amazon-ecs-cli-setup-hydros) or run `ecs-cli down --force`

As for the error, somehow CloudFormation was not able to delete the VPC that was created, you should be able to see a more detailed log in the CloudFormation console. Is the VPC used by any other resources?

**Comment by GFite** [comment]
Thank you, the was being used by an ec2 instance created through the console. I've cleaned it up and used ecs-cli down --force successfully.
