### ISSUE TITLE
monitor cluster is idle or not using cli

### ISSUE THREAD

**Issue by mkaja** [aws/amazon-ecs-cli#208]
can we monitor ecs-cluster is idle or not using cli ?

**Comment by yinshiua** [comment]
`ecs-cli ps` will allow you to look at whether there are tasks running on a cluster.

What information are you looking for to monitor the cluster? Do you just want to know if the cluster is being used? or are you asking for CPU and memory utilization? Please let me know so I can better answer your question. Thanks!

**Comment by mkaja** [comment]
thanks yinshiya- after spinning up the cluster if there is no running tasks - we want to monitor and alert that cluster is idle..

**Comment by yinshiua** [comment]
You will be able to get alert on clusters that are idle by setting alarms on Cluster Utilization. However, ecs-cli does not support creating CloudWatch Alarms today. The work around is to create alarms through AWS console or AWS CLI. For more details, click on this [link](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html) . Let me know if any other questions.

**Comment by mkaja** [comment]
can we find out the instances spinned up by ecs using aws-cli ?

**Comment by yinshiua** [comment]
Yes, `aws ecs list-container-instances` will give you the list of container instances, and by running `aws ecs describe-container-instances`, you can find out more details about the container instance including the instance ID. Here's the aws-cli [documentation](http://docs.aws.amazon.com/cli/latest/reference/ecs/).

**Comment by mkaja** [comment]
thank you
