### ISSUE TITLE
Support docker-compose v3

### ISSUE THREAD

**Issue by MichaelMackus** [aws/amazon-ecs-cli#218]
Has some nice features from v2 that would be nice to implement. Not to mention it seems to largely be becoming the new standard version.

Just a thought since its a little frustrating having to convert my v3 files to the v2 format (which is mostly just a version number change away, along with some network frustrations).

**Comment by yinshiua** [comment]
Thanks for the request.

libcompose has an open issue for this https://github.com/docker/libcompose/issues/421

**Comment by andreabenfatto** [comment]
+1

**Comment by ingo** [comment]
It doesn't seem like libcompose is moving quickly on this. The suggestion in the linked ticket was for people to use https://github.com/aanand/compose-file for v3 support. Thoughts?

**Comment by lechen26** [comment]
any progress on the support of V3?
as ingo asked, is there any attempt to use https://github.com/aanand/compose-file  instead of libcompose?

secrets cannot be used as its V3 related :\

**Comment by barbarosalp** [comment]
Any progress about version: "3" support?

**Comment by SoManyHs** [comment]
We are actively working on supporting composeV3. You can follow changes in the `compose3` branch.

In the meantime,  @MichaelMackus it appears docker compose has introduced a `--compatibility` flag to convert V3 files to V2 (https://github.com/docker/compose/pull/5684).

We would actually be interested in what specific features of v3 you are most interested in seeing integrated for your ECS tasks/services, as several of the new fields in v3 are specific to docker swarm only.

Any feedback would be greatly appreciated! 
/c @ingo @lechen26 @barbarosalp

**Comment by allisaurus** [comment]
Adding on to @SoManyHs 's comment - we have a proposal up re: how we intend to handle container-level resources for Compose 3 (since v3 moves them to the swarm-specific `deploy` field). We welcome any comments/thoughts : https://github.com/aws/amazon-ecs-cli/pull/505

**Comment by allisaurus** [comment]
Compose 3 is supported as of release 1.6.0:
https://github.com/aws/amazon-ecs-cli/releases/tag/v1.6.0

Closing.

**Comment by SoManyHs** [comment]
Hi @FernandoMiguel,
Yes, 3.0. We currently only support the x.0 major versions of docker compose.
