### ISSUE TITLE
Privileged option is not supported

### ISSUE THREAD

**Issue by vultron81** [aws/amazon-ecs-cli#22]
```WARN[0000] Skipping unsupported YAML option...           option name=privileged```

This option is critical so that containers can mount volumes backed by EBS: https://github.com/aws/amazon-ecs-agent/issues/68

**Comment by kylejmcintyre** [comment]
+1

**Comment by bblonski** [comment]
+1

**Comment by tulay** [comment]
+1

**Comment by ctchen** [comment]
+1

**Comment by jas99** [comment]
+1

**Comment by 2opremio** [comment]
+1

**Comment by jas99** [comment]
+1
