### ISSUE TITLE
use existing task definitions

### ISSUE THREAD

**Issue by ptdel** [aws/amazon-ecs-cli#226]
Hello, I was wondering if it was possible to implement the ability to use existing task definitions with ecs-cli?  Not sure what the feasibility of this is or what constraints there would be.

**Comment by yinshiua** [comment]
What are your use cases?
Do you just want to run an existing task definition? Or Are you looking at pulling down the existing task definition into a compose file and make modifications from there?

If you just want to start a task or a service on ECS, you can use the AWS CLI `aws ecs run-task` or `aws ecs create-service` commands.

**Comment by yinshiua** [comment]
Related to https://github.com/aws/amazon-ecs-cli/issues/20

Closing this issue since haven't get a response for awhile. Feel free to reopen this if the related issue does not fit your use case.
