### ISSUE TITLE
ecs-cli ps [signal SIGSEGV: segmentation violation code=0x1 addr=0xe8 pc=0x9f5918]

### ISSUE THREAD

**Issue by ricardson** [aws/amazon-ecs-cli#231]
When I run **ecs-cli ps** in one of my ECS Clusters I get the error, to the others ECS Clusters works just fine.

[signal SIGSEGV: segmentation violation code=0x1 addr=0xe8 pc=0x9f5918]

goroutine 1 [running]:
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.getContainersForTasks(0x11e78e0, 0xc4201ac930, 0xc4201abf40, 0x6, 0x8, 0x8, 0x0, 0x0, 0x0, 0xc420260b20)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/entity.go:195 +0x498
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.collectContainers(0x11e78e0, 0xc4201ac930, 0xc4201e8100, 0x0, 0x2, 0xc4204979d0, 0x40f348, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/entity.go:113 +0xc2
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.info(0x11e78e0, 0xc4201ac930, 0x9f9800, 0xbc7c40, 0x1232e18, 0xc4201ac930, 0xc420260b20, 0x11dffa0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/entity.go:98 +0x42
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.(*Task).Info(0xc4201ac930, 0x11e7800, 0xc4201ac930, 0xc42019fb60, 0x0, 0x0, 0x40f348)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/task.go:101 +0x40
github.com/aws/amazon-ecs-cli/ecs-cli/modules/command.clusterPS(0xc4200d3b80, 0x11e44c0, 0xc4201b6c00, 0x11e7fa0, 0xc42019fb60, 0xcd088d, 0x5, 0x4, 0xc4201b2be8, 0x5)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/command/cluster_app.go:374 +0x187
github.com/aws/amazon-ecs-cli/ecs-cli/modules/command.ClusterPS(0xc4200d3b80)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/command/cluster_app.go:109 +0x199
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli.HandleAction(0xb3f7c0, 0xd2da90, 0xc4200d3b80, 0xc420057200, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli/app.go:487 +0x7c
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli.Command.Run(0xccf8f4, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xcf2454, 0x37, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli/command.go:207 +0xb72
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli.(*App).Run(0xc42011b520, 0xc42000a260, 0x2, 0x2, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/main.go:53 +0x1291

**Comment by yinshiua** [comment]
I believe this is a code bug, but I haven't been able to reproduce this.

Did this just happen once? or does it continue to happen?
