### ISSUE TITLE
Failed to lookup ecs.ap-southeest-1.amazonaws.com

### ISSUE THREAD

**Issue by RaphaelMui** [aws/amazon-ecs-cli#232]
My acs-cli request always return 'no such host' error.

$ ecs-cli ps 
ERRO[0001] Error executing 'ps RequestError: send request failed
caused by: Post https://ecs.ap-southeest-1.amazonaws.com/: dial tcp: lookup ecs.ap-southeest-1.amazonaws.com on 8.8.8.8:53: no such host 

I can successfully ping ecs.ap-southeest-1.amazonaws.com

PING ecs.ap-southeast-1.amazonaws.com (52.95.35.7): 56 data bytes
64 bytes from 52.95.35.7: icmp_seq=0 ttl=237 time=83.782 ms
64 bytes from 52.95.35.7: icmp_seq=1 ttl=237 time=215.714 ms
64 bytes from 52.95.35.7: icmp_seq=2 ttl=237 time=108.952 ms
64 bytes from 52.95.35.7: icmp_seq=3 ttl=237 time=156.533 ms
64 bytes from 52.9....

I am running on MacOS and  my ecs-cli version is 0.5.0

**Comment by yinshiua** [comment]
Looks like there's a typo in "ecs.ap-south**eest**-1.amazonaws.com", the correct endpoint is "ecs.ap-south**east**-1.amazonaws.com"

**Comment by RaphaelMui** [comment]
Yes.  I just figured it out that this is my typo.  

Thank you very much.

**Comment by stephanebruckert** [comment]
Same for me, wrote eu-center-1 instead of eu-central-1...
