### ISSUE TITLE
public IP is always assigned, regardless of subnet settings

### ISSUE THREAD

**Issue by adimarco** [aws/amazon-ecs-cli#233]
When running `ecs-cli up` and specifying existing subnets and VPC with `--subnets`, the EC2 instances created always have a public IP assigned, regardless of the "Auto-assign Public IP" setting for the subnets they're launched in.

The practical effect of this is that if I launch a new ECS cluster with `ecs-cli` in the private subnets of my existing VPC, all the new instances have a useless public IP address associated with them.

**Comment by james-gardner** [comment]
Any update on this? Facing a similar issue.

**Comment by yinshiua** [comment]
Thanks for reporting the issue.

You will need to setup your VPC and subnets correctly for the ECS agent to connect to the instance. See PR https://github.com/aws/amazon-ecs-cli/pull/244 for more details
