### ISSUE TITLE
Problem with creating a cluster with ECS cli

### ISSUE THREAD

**Issue by helloravi** [aws/amazon-ecs-cli#236]
I am following the ecs cli tutorial: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_tutorial.html

When I run the first command: ecs-cli up --keypair xxxxx.pem --capability-iam --size 2 --instance-type t2.medium

I get the following error: ERRO[0040] Failure event reason="Parameter validation failed: parameter value transin-ravi-west-1.pem for parameter name KeyName does not exist. Rollback requested by user." resourceType="AWS::CloudFormation::Stack" ERRO[0040] Error executing 'up': Cloudformation failure waiting for 'CREATE_COMPLETE'. State is 'ROLLBACK_COMPLETE'

I made sure the regions are set up properly. It still does not work. (as suggested here https://forums.manning.com/posts/list/37336.page)

**Comment by yinshiua** [comment]
Your `--keypair` should be a **keypair name** that exists in the region.

**Comment by helloravi** [comment]
@yinshiua Thank you very much. It worked :)

**Comment by yinshiua** [comment]
Cool, feel free to reopen this issue if you run into other similar issues.

**Comment by swaggervalidator** [comment]
Failure event                                 reason="Parameter validation failed: parameter value privatekey.pem for parameter name KeyName does not exist. Rollback requested by user." resourceType="AWS::CloudFormation::Stack"

http://www.amazonwebservicesforum.com/2017/08/error-executing-up-cloudformation.html

**Comment by swaggervalidator** [comment]
same issue reported here
http://www.amazonwebservicesforum.com/2017/08/error-executing-up-cloudformation.html
