### ISSUE TITLE
ecs-cli push doesn't allow tags containing dashes

### ISSUE THREAD

**Issue by ab0ndar** [aws/amazon-ecs-cli#238]
ecs-cli push myimagename:0.0.1-alpha15-BOTS-11-ge426894-b18 fails with:

ERRO[0000] Error executing 'push': Please specify the image name in the correct format [ECR_REPOSITORY[:TAG]]

**Comment by ab0ndar** [comment]
Looks like you have an issue in regexp at ecs-cli/modules/command/image_app.go
splitImageName line 314
`re := regexp.MustCompile("^(?:([0-9A-Za-z.-]+)/)?([0-9a-z-_/]+)(?:" + seperatorRegExp + "([0-9A-Za-z_.-:]+))?$")`

here, ".-:" considered as range from . to :
PLease, consider escape dash character "\-"

**Comment by dbenhur** [comment]
Also in that regexp is an ambiguous construct `[0-9a-z-_/]`.  Most RE engines don't make strong statements about the left/right associativity of character class ranges, and the interpretation of `[a-c-e]` as `[a-c\-e]` vs `[a\-c-e]` will be entirely an accident of implementation;  this appears true of Go's regexp engine [re2](https://github.com/google/re2/wiki/Syntax).

As @ab0ndar recommends, it's safest to always escape `-` in character classes when they are intended literally; do not rely on associativity or start/end of class semantics.

**Comment by garthk** [comment]
I literally just ran into this. Thanks, @dbenhur and @yinshiua! Take that, #90!
