### ISSUE TITLE
support for update-service command from aws cli

### ISSUE THREAD

**Issue by chintans** [aws/amazon-ecs-cli#255]
With AWS CLI, I can do aws ecs update-service to redeploy latest docker image. While using ecs-cli, I have to stop service, remove it and then start it again. It would be nice to have an update command which could redeploy latest image without going through this.

This is how I am doing right now.

`ecs-cli compose --file dev.yml service stop

ecs-cli compose --file dev.yml service rm; sleep 35

ecs-cli compose --file dev.yml service up`

**Comment by yinshiua** [comment]
@chintans You should be able to update the service with the ECS CLI today.`ecs-cli compose --file dev.yml service up` will Create a Service if it does not exist, and will Update the Service if the service already exist. Am I missing something here?

**Comment by chintans** [comment]
No, You are not missing anything. Thanks for clearing that out. It works as expected. Thanks

**Comment by voeetech** [comment]
Using `ecs-cli compose --file dev.yml service up` will indeed create or update the service, but it will also start it. It seems there's no way of just creating/updating WITHOUT starting. Am I missing something?
