### ISSUE TITLE
SIGSEGV: segmentation violation with ecs-cli ps or ecs-cli compose -f compose.yml ps

### ISSUE THREAD

**Issue by c-goosen** [aws/amazon-ecs-cli#259]
Basic info:
ECS cluster of 2 EC2 instances
Using compose with aws style compose file
After compose up, I try to use the compose ps command and get a SIGSEGV.

Full cli output:
DEBU[0000] Parsing the compose yaml...                  
DEBU[0000] Opening compose files: docker-compose-amazon.yml 
DEBU[0000] [0/1] [logstash-two]: Adding                 
DEBU[0000] [0/1] [nginx]: Adding                        
DEBU[0000] [0/3] [logstash-four]: Adding                
DEBU[0000] [0/3] [logstash-one]: Adding                 
DEBU[0000] [0/5] [logstash-three]: Adding               
DEBU[0000] [0/5] [default]: EventType: 32               
DEBU[0000] [0/5] [default]: EventType: 32               
DEBU[0000] [0/5] [default]: EventType: 32               
DEBU[0000] [0/5] [default]: EventType: 32               
DEBU[0000] [0/5] [default]: EventType: 32               
DEBU[0000] Transforming yaml to task definition...      
WARN[0000] Skipping unsupported YAML option...           option name=networks
WARN[0000] Skipping unsupported YAML option for service...  option name=expose service name=logstash-two
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=logstash-two
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=nginx
WARN[0000] Skipping unsupported YAML option for service...  option name=expose service name=logstash-four
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=logstash-four
WARN[0000] Skipping unsupported YAML option for service...  option name=expose service name=logstash-one
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=logstash-one
WARN[0000] Skipping unsupported YAML option for service...  option name=expose service name=logstash-three
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=logstash-three
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe8 pc=0x9f5918]

goroutine 1 [running]:
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.getContainersForTasks(0x11e78e0, 0xc4201b5e30, 0xc420471800, 0x6, 0x6, 0x6, 0x0, 0x0, 0xc4202ab010, 0xb41dc0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/entity.go:195 +0x498
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.collectContainers(0x11e78e0, 0xc4201b5e30, 0xc4201c6f01, 0xc4201da000, 0xc4201d8860, 0xc4201c6f30, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/entity.go:113 +0xc2
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.info(0x11e78e0, 0xc4201b5e30, 0xc4202aaf01, 0xc420192b38, 0x9f65d4, 0xc4201da0f0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/entity.go:98 +0x42
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.(*Task).Info(0xc4201b5e30, 0x1, 0x0, 0xc42012e620, 0x0, 0x0, 0xc420192bc0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/task.go:101 +0x40
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.(*ecsProject).Info(0xc4201da0f0, 0x0, 0x0, 0x11e7660, 0xc4201da0f0, 0xc4201da000)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/project.go:155 +0x3f
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.ProjectPs(0x11e7660, 0xc4201da0f0, 0xc4200e1cc0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app/app.go:81 +0x3b
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.WithProject.func1(0xc4200e1cc0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app/app.go:51 +0xac
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli.HandleAction(0xb3f7c0, 0xc4201b5110, 0xc4200e1cc0, 0xc42000f300, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli/app.go:487 +0x7c
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli.Command.Run(0xccf8f4, 0x2, 0x0, 0x0, 0xc4201ba940, 0x1, 0x1, 0xcf5f4d, 0x52, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli/command.go:207 +0xb72
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc4201256c0, 0xc4200e1a40, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli/app.go:374 +0xacc
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli.Command.startApp(0xcd1923, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xcf2d71, 0x39, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli/command.go:293 +0x8a3
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli.Command.Run(0xcd1923, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xcf2d71, 0x39, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli/command.go:93 +0x14c7
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli.(*App).Run(0xc420125520, 0xc42000e180, 0x6, 0x6, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/main.go:53 +0x1291

**Comment by yinshiua** [comment]
Thanks for reporting this bug, we already have a fix for this. See PR https://github.com/aws/amazon-ecs-cli/pull/234.

**Comment by yinshiua** [comment]
Released in version 0.6.0
