### ISSUE TITLE
Allow cfn Userdata parameter to be read from a file

### ISSUE THREAD

**Issue by kristianpaul** [aws/amazon-ecs-cli#265]
This should not be embedded in the code but instead be part of a file or parameter so you can  add volumes as EFS resource or anything else custom that could supported by cloud-init..

**Comment by yinshiua** [comment]
Already has an issue tracking this. https://github.com/aws/amazon-ecs-cli/issues/16

**Comment by kristianpaul** [comment]
cool, thanks !

**Comment by yinshiua** [comment]
Closing this issue since we are tracking in #16
