### ISSUE TITLE
Add configurable timeouts or retries for `ecs-cli compose service up`

### ISSUE THREAD

**Issue by kevinlester** [aws/amazon-ecs-cli#269]
We have an issue with the `ecs-cli compose service up` command where it times out and returns an error waiting for the # of running instances to equal the # of desired instances, even though the ecs cluster eventually succeeds with the deployment.   This is a bummer since the client is telling us it failed, but in reality it succeeds.  There are no configurable timeouts or retry counts that I see in the documentation that we can use to overcome this issue :(

A potential solution is to enable clients to specify the retryCounts or tasksWaitDelay values.  At the moment, it seems like they are hardcoded [here](https://github.com/aws/amazon-ecs-cli/blob/744a682035833d2415abee4cbd255865bae539ce/ecs-cli/modules/utils/waiters/waiters.go).

**Comment by webdevwilson** [comment]
+1

**Comment by kevinlester** [comment]
Upon further reflection, it seems like this isnt really a timeout issue as much as a logic issue.  It seems that the retry count for describeInstance is hard coded, which means that deployments of services with large number of instances are much more likely to error during deployment, depending on their maxInstance count.  I think the timeout/retry logic should reset for each change of the running instance count to accommodate larger deployments.

**Comment by yinshiua** [comment]
Thanks for your feedback. The same problem also occurs when UpdateService succeeded but somehow ECS is not able get the number of running tasks to the desired count (https://github.com/aws/amazon-ecs-cli/issues/257), and I don't thinking adding retry counts or increase the wait time is really solving the problem here.

There are two things that needs to be done to fix this:
1. Give a warning that the Update service succeeded but the service is not at a stable state. The current timeout error message delivers the wrong message.
2. Show event logs so users can get more information why it times out.

**Comment by kevinlester** [comment]
The behavior we experience is that the service update is proceeding just fine, but the ecs-cli command gives up and returns an error.  The reason for the error is because the ecs-cli command has (what appears to be) a hard-coded number of retries, and if you have a large number of instances to spin up/drain, then you exceed the number of retries and it throws an error.

Solving this by adding more info to the error message is not ideal.  That means that I cannot rely on the ecs-cli to tell me if my deployment actually succeeded because I now have to inspect every error it throws to see if there was an actual error, or if it just failed because there were a large number of instances to spin up/down.  Any library that can't reliably tell me whether it actually did what it is supposed to do is not a library that I can use.  When devs are paged for deployment failures, for example, then a library that errors during long deployments (that actually succeed) makes for very unhappy devs.

So IMHO, the issue here is indeed related to retries. [Note that I am not a golang dev, so my apologies if I misunderstand what is going on here]. The logic, as I understand it, is to fail after X calls to describeInstance where the desiredCount <> runningCount.  But I believe the correct logic should be to fail after X calls to describeInstance where the desiredCount <> runningCount AND the cluster hasn't changed state since the last X calls.  In my case, the cluster was indeed proceeding to the correct state (things were spinning up and draining), but the ecs-cli just gave up after watching it for a while.  It should continue to monitor until the cluster gets stuck, or it succeeds.  Large container deployments are unfairly hit by this logic, and I don't believe it is correct.

One more point is that to you it might make sense to just have a max number of retries, but to me (and likely others) it does not.  I have large number of containers, and if there isn't a logic change to accommodate my large deployments then I can't use ecs-cli for deployment, and that would be a shame.  When placed in a position like this, it is often useful to give the consumer (me) a choice in how they would like the library to operate.  If a default logic change is not something you guys are comfortable with for some reason, then giving me the ability to specify alternative logic via a flag might be good path.  Perhaps something like `--retries-per-cluster-state-change=<val>` where the default is 0, indicating that this flag should be ignored.  When set to a positive value, then that ecs-cli will poll <val> times on each state change before giving up.

**Comment by webdevwilson** [comment]
A somewhat ugly demonstration of using a global flag to handle this:

https://github.com/webdevwilson/amazon-ecs-cli/commit/7970332484da5345b370076bf369012dd3710f58

**Comment by yinshiua** [comment]
Today, the `service up` command does several things to try make sure the deployment succeeded. First, it calls ECS `CreateService` API or `UpdateServic`e API, and if the call succeeded, we call `DescribeService` API for X number of times to ensure that the deployment has succeeded by looking at the `Deployment` response from the API and make sure the only the primary tasks are running. However, the current logic breaks when doing a large deployment or when the deployment fails, and there is no easy way to get the deployment status directly from the API today. 

The reason why I suggested to improve the error messages was that the current timeout error message is misleading and does not provide any helpful information to the users. The correct behavior is to only throw an error when the API calls failed or when the deployments failed. And, by showing event, we can better understand the current state of deployment. However, this just removes the confusion for timeout and maybe solves the problem for customers who have smaller deployments.

I understand that you need to be able to know the status for your large deployments and we think this is a valid use case. We will look into adding this as a capability. I'm happy to hear more feedback.

**Comment by webdevwilson** [comment]
Here is the solution I came up with. COUNT is the number of instances in service when the up command is issued. It could be queried for but in our case it is known.

```
RETRY=0
MAX_RETRIES=10
until [ $RETRY -ge $MAX_RETRIES ]
do
    $ECS_CLI compose \
        --cluster $CLUSTER \
        --region $REGION \
        --project-name $SVC \
        --file $FILE \
        service scale $COUNT
    if [ $? -eq 0 ]; then
        break
    else
        RETRY=$[$RETRY+1]
    fi
done
```

**Comment by PettitWesley** [comment]
@webdevwilson, @kevinlester, please see pull request #288. I have written code that adds a new _smarter, configurable_ timeout. Instead of simply calling describe service for a set period of time-
 the CLI now times out when the running count is not equal to the pending count, and the running count has been stuck at the same value. With `--timeout` you can specify a value in minutes for this timeout- but it defaults to 5 minutes which is likely to be sufficient for most people. Because the timeout is the time since the last task was started (ie it constantly resets every time a new task is started successfully)- the timeout will work well for large and small deployments. 

Here is the help text description of the new flag:
```
$ ecs-cli compose service up --timeout -h
--timeout value [Optional] Specifies the floating point value timeout in minutes to wait for the running task count to change. If the running task count has not changed for the specified period of time then the CLI will return an error. Setting timeout to 0 will cause the command to return without checking for success. (default: 5)
```

And here is an example. (Note that we also now print the Service events- so more useful error messages):

```
$ ecs-cli compose service up --timeout 5
INFO[0000] Using ECS task definition                     TaskDefinition="ecscompose-test2:8"
INFO[0000] ECS Service is already running                desiredCount=1 serviceName=ecscompose-service-test2                
INFO[0000] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-test2
INFO[0000] (service ecscompose-service-test2) has started 1 tasks: (task ae4c2af5-bc96-477f-a17e-577ff1252b8c).  timestamp=2017-07-31 15:43:25 +0000 UTC
INFO[0000] (service ecscompose-service-test2) has reached a steady state.  timestamp=2017-07-31 15:43:37 +0000 UTC
INFO[0000] (service ecscompose-service-test2) was unable to place a task because no container instance met all of its requirements. The closest matching (container-instance 2656b713-3dc3-4f30-8294-717a9e2d346d) is already using a port required by your task. For more information, see the Troubleshooting section of the Amazon ECS Developer Guide.  timestamp=2017-08-01 15:54:33 +0000 UTC
FATA[0060] Deployment has not completed: Running count has not changed for 5.00 minutes 
```

**Comment by kevinlester** [comment]
Thank you for the change.  

Just FYI that the official documentation for this timeout option is incorrect.  It says, "The default timeout value is 5 seconds.", when in reality it defaults to 5 minutes.   The incorrect text is on this page: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-service.html

**Comment by PettitWesley** [comment]
@kevinlester Good catch! We will fix that documentation ASAP!

**Comment by icj217** [comment]
Noticed an interesting bug with this `--timeout` option. Assuming that a new task comes up, fails, and is replaced w/another new task within the window that you set, the timeout counter will keep resetting to 0 and never be reached, and the deployment will basically loop over and over without ever finishing. 

It seems more appropriate for the CLI to raise an error if the `--timeout` value is reached before the deployment completes. 

Open to other suggestions to avoid this "bug"

**Comment by juliandgon** [comment]
Hey 

> Noticed an interesting bug with this `--timeout` option. Assuming that a new task comes up, fails, and is replaced w/another new task within the window that you set, the timeout counter will keep resetting to 0 and never be reached, and the deployment will basically loop over and over without ever finishing.
> 
> It seems more appropriate for the CLI to raise an error if the `--timeout` value is reached before the deployment completes.
> 
> Open to other suggestions to avoid this "bug"

Hey @icj217 found this messy bug too... Did you (or anyone) find a solution for this?

Thanks

**Comment by icj217** [comment]
@juliandgon Unfortunately have not found a solution (though I have not actively looked for one since I raised this bug). I was hoping that the [ECS deployment circuit breaker feature](https://aws.amazon.com/blogs/containers/announcing-amazon-ecs-deployment-circuit-breaker/) would be incorporated into the CLI since it looks like it solves this exact issue, but I have not yet seen that happen (I created #1115 but not much traction on it)
