### ISSUE TITLE
ecs-cli configure -p profile does not copy envs from ~/.aws/credentials

### ISSUE THREAD

**Issue by MrAtheist** [aws/amazon-ecs-cli#27]
This command ```ecs-cli configure -p profile -c cluster``` fails to copy the existing envs from ```~/.aws/credentials``` (with 'profile' being fully populated). Here's a cat of ```~/.ecs/config``` after configured.

```
[ecs]
cluster = cluster
aws_profile = profile
region = 
aws_access_key_id = 
aws_secret_access_key = 
```
Is'nt the cli supposed to copy the remaining envs from ```~/.aws/credentials```?

Of course I can copy the envs manually, but am I missing something that's obvious?

**Comment by uttarasridhar** [comment]
You don’t have to copy the credentials manually. We persist the profile name in ~/.ecs/config with the key as aws_profile. We use that while calling the AWS SDK (which fetches the credentials from the profile at that time). Please let us know if you have any other questions.

**Comment by MrAtheist** [comment]
Fair enough. But apparently you need those set in config when trying to up a cluster.
```
$> ecs-cli up --keypair ~/.ssh/id_rsa --capability-iam --size 2 --instance-type t2.medium

ERRO[0000] Error executing 'up': Set a region with the --region flag or AWS_REGION environment variable
```

With everything set in config, I got another error:
```
INFO[0000] Created cluster                               cluster=cluster
INFO[0001] Waiting for your cluster resources to be created 
INFO[0001] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
ERRO[0031] Failure event                                 reason= resourceType=AWS::CloudFormation::Stack
ERRO[0031] Error executing 'up': Cloudformation failure waiting for 'CREATE_COMPLETE'. State is 'ROLLBACK_COMPLETE'
```
Not sure where to go from there...

**Comment by uttarasridhar** [comment]
Ah! AWS region doesn't get copied from aws cli profile.
As for the error message, I have a pull request that will show a more descriptive reason for failure.

For now, you can go to the Cloudformation console and look for the stack with name amazon-ecs-cli-setup-<cluster-name> and look for an error message there. Apologies for the inconvenience.

**Comment by dtest** [comment]
Ran into this today. Could the region be copied from the profile on `ecs configure`?

**Comment by iwootten** [comment]
Hmm I got the same issue as @MrAtheist - the error being that the tutorial in the docs here: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_tutorial.html misses out where to get the 'keypair' parameter from (it's definitely not id_rsa as in the example). 

After following these steps: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/get-set-up-for-amazon-ecs.html#create-an-iam-role, I've created mine - but be aware you connect using the name of the pair you generate, not the .pem file you download (you'll use that to connect to instances).
