### ISSUE TITLE
ecs-cli compose service create --cluster option ignored?

### ISSUE THREAD

**Issue by bver** [aws/amazon-ecs-cli#270]
Hello,

It seems to me that --cluster option is ignored when using "ecs-cli compose service" command, respecting only the ecs.cluster value configured in the ~/.ecs/config file.

When used without previous ecs-cli configure command (i.e. the cluster value in config is empty) the command fails with "cluster not found" message. If some cluster is defined in the ~/.ecs/config file and the --configure option value differs the command works with the cluster name specified in the config file.

```
ecs-cli --version
ecs-cli version 0.6.0 (1053c82)
```

Possible bug?
Pavel

**Comment by yinshiua** [comment]
@bver Thanks for reporting the bug. We are working on the fix.

**Comment by yinshiua** [comment]
The bug is fixed and will be included in the next release.
