### ISSUE TITLE
running `ecs-cli up` a 2nd time runs out of memory

### ISSUE THREAD

**Issue by matthewmueller** [aws/amazon-ecs-cli#274]
I'm running into an issue where I can successfully create a service on ECS, but when I run `ecs-cli up` a second time with no configuration changes, I get the following:

```
INFO[0002] Using ECS task definition                     TaskDefinition="ecscompose-prometheus:13"
INFO[0002] Updated the ECS service with a new task definition. Old containers will be stopped automatically, and replaced with new ones  desiredCount=1 serviceName=ecscompose-service-prometheus taskDefinition="ecscompose-prometheus:13"
INFO[0003] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-prometheus
```

This will timeout after about 10 minutes. Looking at the events I'm seeing:

```
service ecscompose-service-prometheus was unable to place a task because no container instance met all of its requirements. The closest matching container-instance 04bf0ffc-cd9f-49b4-bf29-6c64a19c86bb has insufficient memory available. For more information, see the Troubleshooting section.
```

In my docker-compose.yml file, I've set `mem_limit` for each of the containers so that it's under the machine's memory threshold by `3 MiB`. I'm only running 1 micro instance.

Is it trying to spawn new containers before shutting down old ones? If that's the case, is there anyway to disable that or have softer memory limits? This service I'm running doesn't need HA and I'd rather utilize as much memory as I'm paying for.

Lastly, thanks a lot for creating this library! I found the ECS service very difficult to use before this CLI came around 😄

**Comment by PettitWesley** [comment]
@matthewmueller, thanks for reaching out- I am working on reproducing your problem. 

Can you please clarify how you encountered this? `ecs-cli up` creates clusters. Given the terminal output that you pasted, I am assuming that you ran 'ecs-cli compose service up` to create a service and then changed your docker compose file and ran the command again- is that correct? Also, I'm curious if you see an OutofMemory error on the container instance.

**Comment by yinshiua** [comment]
@matthewmueller I am very glad that you find the library makes your experience with ECS simple. We are actively working on making improvements on the CLI, any feedback is helpful. :)

In additional to @PettitWesley's comment.

> Is it trying to spawn new containers before shutting down old ones? If that's the case, is there anyway to disable that or have softer memory limits? This service I'm running doesn't need HA and I'd rather utilize as much memory as I'm paying for.

Yes, ECS tries to run new tasks before stopping the old tasks. You can get around with it by setting `--deployment-min-healthy-percent` to zero

**Comment by matthewmueller** [comment]
> Yes, ECS tries to run new tasks before stopping the old tasks. You can get around with it by setting --deployment-min-healthy-percent to 0 if you do not care to have downtime to your service.

Yep, that's perfect and exactly what I was looking for!

>  any feedback is helpful. :)

Wrote a few quick things that tripped me up as I was first familiarizing myself with ECS and the ECS-CLI. These were the things I had to google around for.

1. docker-compose.yml fails without (non-standard) `mem_limit`'s set.

Since I'm guessing most folks will use a micro instance as they're first testing ECS-CLI (in fact that's the default), failing a bit more gracefully if you're trying to deploy more than 2 containers would be awesome.

2. Couldn't figure out how to load images from ECR

I think it'd be great for ECS first check ECR before going to docker hub. I think it would make things a bit more coherent and then you wouldn't have to have these long, ugly `ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/prometheus:latest` urls in your docker-compose file.

3. Better errors about memory limits

Obviously a bit more pointed error for this issue would be much appreciated. I do really like that it handles zero-downtime for you, I just wish I knew the order of operations better (starting this container, shutting down this container, etc.)

---

Hope this helps!

**Comment by PettitWesley** [comment]
@matthewmueller, thanks so much for providing feedback on your experience with the ECS CLI! We will try to incorporate your feedback in our planning and vision for the future of the ECS CLI. If you ever have any other suggestions, please do not hesitate to submit an issue on GitHub.
