### ISSUE TITLE
release 0.6.0 do not obey --cluster flag

### ISSUE THREAD

**Issue by fogfish** [aws/amazon-ecs-cli#275]
The command line
```
ecs-cli compose --cluster test2 --project-name echo --file ./echo.yaml service up
```

fails with
```
ERRO[0000] Error creating service                        error="ClusterNotFoundException: The referenced cluster was inactive.
```

The config file has other cluster name as default one
```
[ecs]
cluster                     = othername
```

The command above works fine when config file is changed.

**Comment by PettitWesley** [comment]
This looks like a duplicate of #270, and a fix has been committed to master.

**Comment by fogfish** [comment]
True! This is why I was not able to find an issue in source code!

**Comment by yinshiua** [comment]
Sorry for the inconvenience. We are planning to do a release to roll out the fix by this week.

**Comment by fogfish** [comment]
No problem! Please, Let me know when release is out.

**Comment by PettitWesley** [comment]
The release is out now! (0.6.1 went out last Thursday- apologies for the delay in response!).
