### ISSUE TITLE
volume.name string in Dockerrun resolved as error

### ISSUE THREAD

**Issue by linwalth** [aws/amazon-ecs-cli#277]
Hello folks,

I am getting the same error message in deployment over and over when I run eb deploy:

ERROR: Service:AmazonECS, Code:ClientException, Message:volume.name contains invalid characters., Class:com.amazonaws.services.ecs.model.ClientException
ERROR: Failed to deploy application.                                
                                                                      
ERROR: Failed to deploy application.

It seems to be a problem with the ECS API, since this is what my volume.name string seems to be valid, adhering to the rules (<255 chars, Numbers, hyphens, underscores).

   "AWSEBDockerrunVersion":2,
   "volumes": [
      {
         "name": "varlogapp",
         "host": {
            "sourcePath": "/var/log/app"
         }
      },
      {
         "name": "varlogweb",
         "host": {
            "sourcePath": "/var/log/web"
         }
      },
      {
         "name": "varlogdb",
         "host": {
            "sourcePath": "/var/log/db"
         }
      },
      {
         "name": "dbdata",
         "host": {
            "sourcePath": "/var/app/current/my_app_name/database"
         }
      },
      {
         "name": "varwww",
         "host": {
            "sourcePath": "/var/app/current/my_app_name"
         }
      }

I am a bit at a loss here. Hopefully this is the right issue forum to post this.

Best wishes.

**Comment by PettitWesley** [comment]
Hey @linwalth, unfortunately, this is the ECS CLI repository. We understand the confusion because the error is ECS related. We are looking into the issue, and we will get back to you as soon as possible. However, for future reference you can submit Elastic Beanstalk related issues to the  [Elastic Beanstalk forum](https://forums.aws.amazon.com/forum.jspa?forumID=86&start=0).

**Comment by linwalth** [comment]
Thank you for the attention. 
I have resolved the issue by re-examining my code line by line and then realizing that I did not completely adhere to the sensibilities of the EB CLI. I.e.: I lacked some definitions further down the JSON.
Thank you for answering so promptly. I am a beginner at AWS, so this made me feel very appreciated.
Have a productive and fulfilling week,
LW
