### ISSUE TITLE
Tests fail if ran on an EC2 instance with an IAM instance profile

### ISSUE THREAD

**Issue by hasPeterr** [aws/amazon-ecs-cli#279]
Currently when running `make test` on an EC2 instance that has an attached instance profile, they fail because of a test that incorrectly succeeds in getting credentials.

```
=== RUN   TestCredentialsWhenNoneSpecified
--
--- FAIL: TestCredentialsWhenNoneSpecified (0.00s)
assertions.go:226:
Error Trace:	config_test.go:399
Error:      	An error is expected but got nil.
Messages:   	Expected error getting credentials
```

After poking around the SDK code I thought of setting [AWS_CONTAINER_CREDENTIALS_RELATIVE_URI](https://github.com/aws/amazon-ecs-cli/blob/master/ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/defaults/defaults.go#L103) to a bad value in order to make the credential request fail, but it appears the test calls `os.Clearenv()` which wipes that out.

It should be possible to run the ecs-cli tests in any reasonable environment which I would think includes an EC2 instance w/ instance profile.

**Comment by yinshiua** [comment]
Thanks for reporting the bug. Can you submit a PR if you have a fix? Thanks!

**Comment by hasPeterr** [comment]
I verified that setting that value after the environment is cleared works. It also looks like you committed a fix yourself, so I'll close this out.
Thanks!
