### ISSUE TITLE
version number fragility: _cannot unmarshal !!str `2.0`_

### ISSUE THREAD

**Issue by abuckenheimer** [aws/amazon-ecs-cli#305]
Hey folks,

I'm having a small issue with ecs-cli [0.6.4 (5b0fd9c)] where it can't seem to read the compose file if the version is "2.0" instead of "2". A simple reproduction would be running `ecs-cli compose --verbose -p my_service -f compose-example.yml -f - create` where compose-example.yml looks like

```
version: '2.0'
services:
 my_service:
    image: busybox
    command: ['echo', 'hello world']
```
the stack trace looks like:
```
DEBU[0000] Parsing the compose yaml...                  
DEBU[0000] Opening compose files: compose-example.yml   
ERRO[0000] Could not parse config for project myservice : yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `2.0` into config.RawService 
ERRO[0000] Unable to open ECS Compose Project            error="yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `2.0` into config.RawService"
FATA[0000] Unable to create and read ECS Compose Project  error="yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `2.0` into config.RawService"
```

I'm not quite sure if this is an issue with ecs-cli or an underlying library (this looks like its tied to yaml parsing?). The reason this came up is because while I usually use `version: '2'` but I was trying to feed ecs-cli `docker-compose -f <file.yml> config` output and compose actually outputs the more specific version number "2.0" instead of "2" which breaks the ecs-cli parser.

This obviously isn't a showstopper as anyone can write their compose files to use "2" instead of "2.0" but it's useful to be able to to use docker-compose to validate compose files before deployment and archive their fully denormalized version.

Thanks in advance

**Comment by yinshiua** [comment]
@abuckenheimer This is due to the Libcompose dependency. We will look into this and see if there's an easy way to get around this.

**Comment by abuckenheimer** [comment]
@yinshiua sorry about the confusion, I have reproduced using libcompose, will open a ticket there
```
./libcompose-cli config                                                                                                                                                                                                                                    
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
ERRO[0000] Could not parse config for project bundles : yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `2.0` into config.RawService 
FATA[0000] Failed to read project: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `2.0` into config.RawService
```

thanks!

**Comment by johnjelinek** [comment]
This looks to be related; I get:
```
$ ecs-cli compose --ecs-params docker-compose.yml up

ERRO[0000] Could not parse config for project svcselfsvc : yaml: unmarshal errors:
  line 1: cannot unmarshal !!int `1` into config.RawService
ERRO[0000] Unable to open ECS Compose Project            error="yaml: unmarshal errors:\n  line 1: cannot unmarshal !!int `1` into config.RawService"
FATA[0000] Unable to create and read ECS Compose Project  error="yaml: unmarshal errors:\n  line 1: cannot unmarshal !!int `1` into config.RawService"
```

**Comment by johnjelinek** [comment]
@PettitWesley: want me to open a new issue for this?

**Comment by PettitWesley** [comment]
@johnjelinek in order to use the ECS CLI with Fargate you need 2 files; a Docker Compose file and an ECS Params file. To me, it looks like your problem is caused because you only have one of them. Our readme has information on both files; and if you can launch a task with them like this:

```
ecs-cli compose --file <Your Docker Compose file> --ecs-params <Your ECS Params file> up
```
