### ISSUE TITLE
ecs-cli returns successful exit codes even when an error occurs

### ISSUE THREAD

**Issue by vitorbaptista** [aws/amazon-ecs-cli#306]
I'm running version 0.6.4 (5b0fd9c). See:

```
$ ecs-cli up
ERRO[0000] Error executing 'up': You must either specify a custom role with the '--instance-role' flag or set the '--capability-iam' flag 
$ echo $?
0
$ ecs-cli --invalid-arg compose service up
Incorrect Usage. flag provided but not defined: -invalid-arg
(...)
$ echo $?
0
```

Some commands return the expected error exit code, like:

```
$ ecs-cli foobar
No help topic for 'foobar'
$ echo $?
3
```

A similar issue was reported on https://github.com/aws/amazon-ecs-cli/issues/116.

**Comment by PettitWesley** [comment]
@vitorbaptista, thanks for calling this out. Pull request #302 will fix this problem; if you have any comments or thoughts on it please feel free to comment there.
