### ISSUE TITLE
ecs-cli compose run should support multiple arguments for one container

### ISSUE THREAD

**Issue by arthurpsmith** [aws/amazon-ecs-cli#32]
ecs-cli compose doesn't appear to provide any way to run a complex command-line on a single container through the 'ecs-cli compose run' functionality. With 'docker-compose run' all the arguments after the container name are supplied to the (one) container to override the normal command run - from the documentation for that:

`docker-compose run --no-deps SERVICE COMMAND [ARGS...]`.

whereas ecs-cli compose run --help allows just a single argument per container:

compose run - ecs-cli compose run [containerName] [command] [containerName] [command] ...

If you try to quote the command to supply it as a single string, for example something like:

ecs-cli compose run container '/bin/echo test'

then it tries to run a file named '/bin/echo test' on the container rather than passing that string to a shell to run. I don't see any solution other than to completely place all such commands into a file in the docker image or a mounted volume that can then be called as a single string.

**Comment by arthurpsmith** [comment]
See related issue #2 which is I think the same problem in the case of a command specified in the docker-compose yaml file rather than with arguments to 'run'.

**Comment by yinshiua** [comment]
This was resolved in #2 and https://github.com/aws/amazon-ecs-cli/pull/235
