### ISSUE TITLE
Issue running make on a fork

### ISSUE THREAD

**Issue by emcfins** [aws/amazon-ecs-cli#321]
Quick question - I've forked the repo for some experimentation. However, I'm having an issue running make when I fork the repo.
```
../../../<MY CODE LOCATION>/amazon-ecs-cli/ecs-cli/main.go:19:2: cannot find package "github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/compose/factory" in any of:
	/<MY CODE LOCATION>/amazon-ecs-cli/ecs-cli/vendor/github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/compose/factory (vendor tree)
```
Does AWS prefer contributes to fork the repo? Are there any recommendations or documentation on how to do this?

Thank you

**Comment by nmeyerhans** [comment]
This is a side-effect of the way golang handles imports. You'll need to clone your fork such that you maintain the `github.com/aws/amazon-ecs-cli` directory structure.

When I work on the amazon-ecs-agent, I clone my personal fork in the location expected by golang. I also add both the "primary" repository and my personal fork as git remotes so I can easily pull changes from the primary repo for the purpose of merging, rebasing, etc:
```
$ pwd
/home/noahm/go/src/github.com/aws/amazon-ecs-agent
$ git remote -v
nmeyerhans      git@github.com:nmeyerhans/amazon-ecs-agent.git (fetch)
nmeyerhans      git@github.com:nmeyerhans/amazon-ecs-agent.git (push)
origin  git@github.com:aws/amazon-ecs-agent.git (fetch)
origin  git@github.com:aws/amazon-ecs-agent.git (push)
```

This lets me easily work on my fork by pulling and pushing from the `nmeyerhans` remote, while also letting me pull changes from the primary repo by pulling from `origin`.

Others may be able to suggest good documentation or other work flows for dealing with this situation, but hopefully this is enough to get you unblocked.
