### ISSUE TITLE
ECR `Network Restricted` error

### ISSUE THREAD

**Issue by tpitale** [aws/amazon-ecs-cli#322]
`Error executing 'push': unable to push image: Get https://[private]ecr.eu-west-1.amazonaws.com/v2/: Restricted Network`

Trying to do `ecs-cli push …`.

There is no documentation provided by amazon that explains what this error is or means or what causes it.

Any help would be appreciated so that I can try to improve this error message handling.

**Comment by SoManyHs** [comment]
Hi @tpitale, I'm looking into your issue and it'd be helpful if you could you provide a little more information. Are you getting the same error when you run `docker push` on that image to your ECR repository? Also, were you on any kind of VPN when you tried to run this?

**Comment by tpitale** [comment]
I tried on two different VPNs and without a VPN.

I was able to get it to push over a phone. Seems to be a strange issue with the wifi/network I was on at the time.

I'll try to use `docker push` directly. I'll have to look up how to do that with AWS credentials as I've never tried before.

Thanks for your help!

**Comment by SoManyHs** [comment]
Hi @tpitale,

Glad that it seems to be a temporary network issue. 

Regarding your AWS creds, you should be able to set up your CLI to push to a given ECR repository by running `aws ecr get-login --no-include-email` (See the [docs](http://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_on_ECS.html) for more information). However once you have your credentials properly configured, running `ecs-cli push` should create a new repository for you, saving you from having to create the ECR repository yourself through the CLI or console.

Let me know if you have further questions!

**Comment by tpitale** [comment]
Thanks so much for your help!
