### ISSUE TITLE
https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest download can be slow from Singapore

### ISSUE THREAD

**Issue by kaihendry** [aws/amazon-ecs-cli#326]
Could it please be hosted on a CDN? I heard AWS has such a product. ;)

**Comment by PettitWesley** [comment]
@kaihendry Sorry you are having trouble downloading the ECS CLI. Can you let us know how slow it is for you in Singapore? Is your download failing or is it just slow?

**Comment by PettitWesley** [comment]
We are committed to ensuring that the ECS CLI is easily downloadable by any customer in any region. However, closing this issue due to lack of response. If @kaihendry or anyone else continues to have this problem, feel free to re-open it.
