### ISSUE TITLE
unable to use compose command even after asserting my credentials are correct

### ISSUE THREAD

**Issue by therealjessesanford** [aws/amazon-ecs-cli#33]
I have tried adding the creds directly to the .ecs/config file as well. However this should work?!:
```
(default)jessesanford@JesseMacbook ~/workspace/stn_proxymail_docker (master)$ ecs-cli configure --region us-east-1 -p ~/.aws/credentials --cluster proxymail                                                                                                            [2.2.3]
INFO[0000] Saved ECS CLI configuration for cluster (proxymail)
(default)jessesanford@JesseMacbook ~/workspace/stn_proxymail_docker (master)$ ecs-cli compose --file docker-compose.yml up                                                                                                                                              [2.2.3]
ERRO[0120] Unable to create an instance of ECSParams given the cli context  error=NoCredentialProviders: no valid providers in chain
FATA[0120] Unable to create and read ECS Compose Project  error=NoCredentialProviders: no valid providers in chain
(default)jessesanford@JesseMacbook ~/workspace/stn_proxymail_docker (master)$ cat ~/.ecs/config                                                                                                                                                                         [2.2.3]
[ecs]
cluster = proxymail
aws_profile = /Users/jessesanford/.aws/credentials
region = us-east-1
aws_access_key_id =
aws_secret_access_key =
```

Any ideas? I checked the access key is correct in iam on this account.

**Comment by uttarasridhar** [comment]
ecs-cli configure expects a named profile (for AWS credentials) rather than the path.
You can configure your aws cli profile using aws configure --profile <name> (or following the steps in http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html) By default the profile name is called `default`.

You can try:
ecs-cli configure --region us-east-1 --cluster proxymail -p default
or ecs-cli configure --region us-east-1 --cluster proxymail --access-key <aws-access-key> --secret-key <aws-secret>

Hope that helps

**Comment by therealjessesanford** [comment]
That did it! Unrecognizable error message through me off. Any idea how I can pass in environment variable overrides? In the Run Task wizard in the ECS control panel there is the "Container Overids" under "Advanced Options". Is it possible to pass these along with the call to compose? Should I open another issue?

**Comment by uttarasridhar** [comment]
It doesn't support it yet. A new issue would help.

The workaround is to edit the docker-compose.yml file with the new environment variables and execute ecs-cli compose run.
