### ISSUE TITLE
Keypair parameter should be optional

### ISSUE THREAD

**Issue by et304383** [aws/amazon-ecs-cli#344]
We don't use key pairs anymore and rely on more sophisticated ways to gain SSH access if it happens to be required by utilizing SSM.

Please make keypair an optional parameter.

**Comment by SoManyHs** [comment]
Hi @et304383,

Great feedback. We've addressed this in #347. Please let us know if you have any further questions.

**Comment by SoManyHs** [comment]
This has been included in the v1 release. Resolving.
