### ISSUE TITLE
Updating Service Fails - Port in Use - ecs-cli compose service up

### ISSUE THREAD

**Issue by GetchaDEAGLE** [aws/amazon-ecs-cli#353]
We are moving our Docker images over to ECS and integrating everything with our CICD pipeline. We are using Jenkins to automatically deploy services to ECS. It's my understanding that running the command **ecs-cli compose service up** will automatically take care of service deployments and updates for us so long as we provide a good Docker Compose file.

On the first run via Jenkins, running the above command works great. Below are the logs.

```bash
23:44:20 [spring-boot-demo] Running shell script
23:44:21 + ecs-cli compose --file docker-compose-dev-ecs.yml --project-name Spring-Boot-Demo service up
23:44:21 time="2017-10-27T04:44:20Z" level=warning msg="Skipping unsupported YAML option..." option name=networks 
23:44:21 time="2017-10-27T04:44:20Z" level=warning msg="Skipping unsupported YAML option for service..." option name=networks service name=spring-boot-demo 
23:44:21 time="2017-10-27T04:44:21Z" level=info msg="Using ECS task definition" TaskDefinition="ecscompose-Spring-Boot-Demo:8" 
23:44:21 time="2017-10-27T04:44:21Z" level=info msg="Created an ECS service" service=ecscompose-service-Spring-Boot-Demo taskDefinition="ecscompose-Spring-Boot-Demo:8" 
23:44:21 time="2017-10-27T04:44:21Z" level=info msg="Updated ECS service successfully" desiredCount=1 serviceName=ecscompose-service-Spring-Boot-Demo 
23:44:36 time="2017-10-27T04:44:36Z" level=info msg="Service status" desiredCount=1 runningCount=1 serviceName=ecscompose-service-Spring-Boot-Demo 
23:44:36 time="2017-10-27T04:44:36Z" level=info msg="(service ecscompose-service-Spring-Boot-Demo) has started 1 tasks: (task 3094799a-e766-4f2b-b54c-f9700ef45c1d)." timestamp=2017-10-27 04:44:25 +0000 UTC 
23:44:36 time="2017-10-27T04:44:36Z" level=info msg="ECS Service has reached a stable state" desiredCount=1 runningCount=1 serviceName=ecscompose-service-Spring-Boot-Demo 
```

However, if code is updated, a new Docker image pushed, and then the same **ecs-cli compose service up** command executed after, the following occurs:

```bash
23:45:49 [spring-boot-demo] Running shell script
23:45:49 + ecs-cli compose --file docker-compose-dev-ecs.yml --project-name Spring-Boot-Demo service up
23:45:49 time="2017-10-27T04:45:49Z" level=warning msg="Skipping unsupported YAML option..." option name=networks 
23:45:49 time="2017-10-27T04:45:49Z" level=warning msg="Skipping unsupported YAML option for service..." option name=networks service name=spring-boot-demo 
23:45:49 time="2017-10-27T04:45:49Z" level=info msg="Using ECS task definition" TaskDefinition="ecscompose-Spring-Boot-Demo:9" 
23:45:49 time="2017-10-27T04:45:49Z" level=info msg="Updated the ECS service with a new task definition. Old containers will be stopped automatically, and replaced with new ones" desiredCount=1 serviceName=ecscompose-service-Spring-Boot-Demo taskDefinition="ecscompose-Spring-Boot-Demo:9" 
23:45:50 time="2017-10-27T04:45:49Z" level=info msg="Service status" desiredCount=1 runningCount=1 serviceName=ecscompose-service-Spring-Boot-Demo 
23:46:22 time="2017-10-27T04:46:20Z" level=info msg="(service ecscompose-service-Spring-Boot-Demo) was unable to place a task because no container instance met all of its requirements. The closest matching (container-instance c82f6535-2e7e-47ab-90ce-08fd9c71110d) is already using a port required by your task. For more information, see the Troubleshooting section of the Amazon ECS Developer Guide." timestamp=2017-10-27 04:46:15 +0000 UTC 
23:50:59 time="2017-10-27T04:50:50Z" level=fatal msg="Deployment has not completed: Running count has not changed for 5.00 minutes" 
```

Here's my Docker Compose file:

```bash
version: '2'
services:
  spring-boot-demo:
    image: <redacted>.amazonaws.com/cicd-demos/spring-boot:latest
    ports:
      - '8090:8090'
```

What am I missing here? Everything I read states this should work fine. I'm quite perplexed. Your assistance would greatly be appreciated.

**Comment by GetchaDEAGLE** [comment]
Just to add something that might be relevant. I'm not sure whether or not the ECS CLI stores state of any kind but it's important to note that each time the **ecs-cli compose service up** command is executed, it's done so in a different instance of the container. The only state that persists is in the volume created for the config data (e.g. ~/.ecs and ~/.aws).

**Comment by SoManyHs** [comment]
Hi @GetchaDEAGLE,

Thanks for the clarification. This probably has to do with your minimum healthy deployment settings.  Your service configs are probably preventing the old task from shutting down properly before launching the new one, and so the port in question is still being used by the old task. Try  setting `--deployment-min-healthy-percent` to 0, if your service can tolerate some downtime.

See: #274 

Let me know if that helps!

**Comment by GetchaDEAGLE** [comment]
@SoManyHs, I can confirm that has fixed the problem. Would you be able to elaborate exactly how we can control the number of container instances (or from the Docker Swarm world, replicas) using the same command? All I could find is running the scale command after the up command which isn't desired.

**Comment by GetchaDEAGLE** [comment]
@SoManyHs, I was able to get around my last question by adding some interesting logic to my Jenkinsfile but feel this is more of a hack. Perhaps the AWS tooling team could look into properly managing instance count using the ECS CLI. Perhaps having instance count as a flag or option passed to the CLI.
