### ISSUE TITLE
STOPPED status reason not present

### ISSUE THREAD

**Issue by exp0nge** [aws/amazon-ecs-cli#367]
All my containers stop at some point. I've tested using `docker-machine`. I can't find the status reason as shown here - http://docs.aws.amazon.com/AmazonECS/latest/developerguide/stopped-task-errors.html

The CLI also doesn't show anything.

**Comment by PettitWesley** [comment]
@exp0nge, I'd recommend logging into one of your instances and following the recommendations [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-diags.html).

If that doesn't help you figure out why your tasks are stopping, you can also try looking at the [ECS Agent](https://github.com/aws/amazon-ecs-agent) logs at `/var/log/ecs`.

Hope that helps!

**Comment by exp0nge** [comment]
@PettitWesley i see the issue now with `docker ps -a` then `docker img-id logs`
