### ISSUE TITLE
ClientException: Family contains invalid characters when using ecs-cli compose

### ISSUE THREAD

**Issue by wjimenez5271** [aws/amazon-ecs-cli#37]
Trying to launch a docker-compose file that works locally with compose, and I get the following errors:
```
ecs-cli compose --file docker-compose.yml up
ERRO[0000] Error registering task definition             error=ClientException: Family contains invalid characters.
	status code: 400, request id: 81108bb6-840b-11e5-a881-4de8415be30c family=0xc208036440
ERRO[0000] Create task definition failed                 error=ClientException: Family contains invalid characters.
	status code: 400, request id: 81108bb6-840b-11e5-a881-4de8415be30c
FATA[0000] ClientException: Family contains invalid characters.
	status code: 400, request id: 81108bb6-840b-11e5-a881-4de8415be30c
```

Its unclear to me what "Family" its referring to

**Comment by uttarasridhar** [comment]
Thanks for reporting, we will add better error messaging.

Family refers to the name of the ECS Task Definition that this tool creates by translating the docker compose yml.
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#family

We autogenerate the family name using the --project-name flag that is passed to ecs-cli compose, which defaults to the directory name you are running this command from. Acceptable characters for the project-name are letters (uppercase and lowercase), numbers, hyphens, and underscores.

**Comment by wjimenez5271** [comment]
@uttarasridhar thanks, that's helpful, I was able to get around the issue by specifying a the project name manually (with a valid name).

**Comment by shivamlync** [comment]
I am following the naming convention for the `family` key in the task definition json when I am using aws-cli. But I am still getting this error
```bash
An error occurred (ClientException) when calling the DescribeTaskDefinition operation: Family contains invalid characters.
```

**Comment by shivamlync** [comment]
```bash
 aws ecs describe-task-definition --task-definition .aws/task-definition.json --debug
```
Using this command.
