### ISSUE TITLE
Interacting with old Services and Task Definitions using the v1.0 ECS CLI

### ISSUE THREAD

**Issue by rajanski** [aws/amazon-ecs-cli#374]
Dito in title.

It would be really helpful to be able to freely name the service and task definition that is to be created or updated.

Reason:
Before 1.0.0, the services / task definitions where either named by the directory or by a project-name variable, that was obligatory prefixed by ecscompose- / ecscompose-service-.
Now with the changes made in 1.0.0, I can't figure how to name my services in order to update existing ones (created with ecs-cli < 1.0.0) without having to recreate them.

**Comment by PettitWesley** [comment]
@rajanski, please see the information in the AWS Docs about migrating the old config files to the new v1.0 format: [Migrating Config Files](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_migrating_config_files.html).

##### Service Names
- The name used for creating a service is: `<compose_service_name_prefix> + <project_name>`
- `compose_service_name_prefix` can still be configured in the v1.0 ECS CLI. It now defaults to empty, but you can still configure it. 
- Project name can be set using the `--project-name` flag. 


##### Task Definition Names
- The name used for creating a Task Definition is: `<compose_project_name_prefix> + <project_name>`
- `compose_profect_name_prefix` has been removed; the v1.0 ECS CLI can still read it in old configuration files, but the new format does not support this field.
- Project name can be set using the `--project-name` flag. So by setting this you can name your Task Definition!

**Comment by rajanski** [comment]
@PettitWesley Thanks , I saw those.
nevertheless, also with this information, I am not able to ecs-cli compose service in order to update an existing service with a task definition that's named differently from the service name

**Comment by PettitWesley** [comment]
@rajanski, I went through the workflow of starting a service with an old version of the ECS CLI (v0.6.6) and then upgrading to v1.0. 

##### Starting a Service with v0.6.6 CLI

Here's what my config file looks like:
```
[ecs]
cluster                     = Test
aws_profile                 = 
region                      = us-east-2
aws_access_key_id           = ****
aws_secret_access_key       = ****
compose-project-name-prefix = ecscompose-
compose-service-name-prefix = ecscompose-service-
cfn-stack-name-prefix       = amazon-ecs-cli-setup-
```

I then started a service:
```
$ ./ecs-cli-v6 compose service up
INFO[0000] Using ECS task definition                     TaskDefinition="ecscompose-v6oldcli:1"
INFO[0000] Created an ECS service                        service=ecscompose-service-v6oldcli taskDefinition="ecscompose-v6oldcli:1"
INFO[0000] Updated ECS service successfully              desiredCount=1 serviceName=ecscompose-service-v6oldcli
INFO[0015] (service ecscompose-service-v6oldcli) has started 1 tasks: (task e7015beb-108f-4d0f-b086-1d550fc3884c).  timestamp=2017-11-14 18:38:31 +0000 UTC
INFO[0046] Service status                                desiredCount=1 runningCount=1 serviceName=ecscompose-service-v6oldcli
INFO[0046] ECS Service has reached a stable state        desiredCount=1 runningCount=1 serviceName=ecscompose-service-v6oldcli
```

##### Interacting with the service with the v1.0.0 ECS CLI

Notes:
- The v1.0.0 ECS CLI can still read the old configuration files with all the prefixes specified.
- I used the migrate command and updated to the new format, but note that you can also use the normal configure commands to create the same set of configuration files. 

Migrating to the new format:
`$ ecs-cli configure migrate`

The new cluster config file:
```
version: v1
default: default
clusters:
  default:
    cluster: Test
    region: us-east-2
    compose-service-name-prefix: ecscompose-service-
```

In the same directory (the project name is set by the directory name by default) I am still able to interact with the service:
```
$ ecs-cli compose service scale 2
INFO[0000] Updated ECS service successfully              desiredCount=2 serviceName=ecscompose-service-v6oldcli
INFO[0000] Service status                                desiredCount=2 runningCount=1 serviceName=ecscompose-service-v6oldcli
INFO[0030] (service ecscompose-service-v6oldcli) has started 1 tasks: (task 6b6b1669-1626-411c-bf26-12ab87a77f95).  timestamp=2017-11-14 18:53:25 +0000 UTC
INFO[0060] Service status                                desiredCount=2 runningCount=2 serviceName=ecscompose-service-v6oldcli
INFO[0060] ECS Service has reached a stable state        desiredCount=2 runningCount=2 serviceName=ecscompose-service-v6oldcli
```

I then changed to a new directory, and changed the compose file that I was using. I then updated the service- doing this required manually setting the project name with `--project-name`.

```
$ ecs-cli compose --project-name v6oldcli service up
INFO[0000] Using ECS task definition                     TaskDefinition="v6oldcli:1"
INFO[0000] Updated the ECS service with a new task definition. Old containers will be stopped automatically, and replaced with new ones  desiredCount=1 serviceName=ecscompose-service-v6oldcli taskDefinition="v6oldcli:1"
INFO[0000] Service status                                desiredCount=1 runningCount=1 serviceName=ecscompose-service-v6oldcli
INFO[0015] (service ecscompose-service-v6oldcli) has started 1 tasks: (task ea7990b6-b7b2-49e5-bcf3-9c778809cdbc).  timestamp=2017-11-14 18:58:42 +0000 UTC
INFO[0015] (service ecscompose-service-v6oldcli) has stopped 1 running tasks: (task 6b6b1669-1626-411c-bf26-12ab87a77f95).  timestamp=2017-11-14 18:58:53 +0000 UTC
INFO[0030] ECS Service has reached a stable state        desiredCount=1 runningCount=1 serviceName=ecscompose-service-v6oldcli
```

Note that the name of the task definition did change; however, this did not prevent me from being able to update my existing service.

Let me know if you have any additional questions, or are still unable to access your existing service!

**Comment by yinshiua** [comment]
@rajanski Hope @PettitWesley's comment was able to solve your issue. Feel free to reopen this if you still have issue with this.
