### ISSUE TITLE
Cluster scale fails with 'ValidationError: No updates are to be performed'

### ISSUE THREAD

**Issue by bee-keeper** [aws/amazon-ecs-cli#376]
Hi there,

I have an auto scaling group with min, max and desired all set to 0.  I run the following:

`export AWS_DEFAULT_REGION=eu-west-1 && ecs-cli scale --capability-iam --size 5 --cluster my-cluster`

The result of which is:

`ERRO[0001] Error executing 'scale': ValidationError: No updates are to be performed.
	status code: 400, request id: c81d5a96-c9e5-11e7-9c26-8dc31412887d`

Any ideas why this might happen and is there any other information I can provide to help debug?

Thanks in advance,

**Comment by PettitWesley** [comment]
Hey @bee-keeper, the error message you got is from the CloudFormation API. Can you check the values of all of the parameters for your CloudFormation template in the CloudFormation Console? This error message is returned when you try to update a template, and the new template is the same as the old template. 

Did you use the ECS CLI to scale down your cluster to 0? If you modified the auto scaling group directly (without going through CloudFormation) then the `AsgMaxSize` parameter in the template will not be 0. Consequently, CloudFormation (and the ECS CLI) doesn't know that your cluster does not have any instances in it. I suspect this is what caused that error message.

**Comment by bee-keeper** [comment]
Hi, 

Thanks for the quick response - I can't be sure I did scale down with ECS CLI but the `AsgMaxSize` is currently at 1.  I've since switched to aws-cli for this as it seems a bit more robust.  Appreciate that makes this a bit harder to debug, but it does seem clear that there are issues with the ECS CLI `scale` command.

For anyone looking for a workaround for scaling, I'll leave this here.

`aws autoscaling update-auto-scaling-group --auto-scaling-group-name my-scaling-name --min-size 0 --max-size 0 --desired 0`

**Comment by yinshiua** [comment]
@bee-keeper This was a bug in ECS CLI and we had a fix https://github.com/aws/amazon-ecs-cli/issues/335 to allow you to scale down to 0 in the CloudFormation template.

However, we will not be able update the existing clusters using the old CloudFormation template that was created prior to this fix. Another workaround is to manually update your CloudFormation template `MinSize: 0`, you will be able to continue to use ECS CLI to scale up and down after the manual fix. Let me know if this doesn't fix your problem. Thanks!
