### ISSUE TITLE
Probable parsing issue

### ISSUE THREAD

**Issue by prozac631** [aws/amazon-ecs-cli#378]
Hi.

I'm trying to do some configuration with the following command:
`ecs-cli configure --access-key KEY_ID --secret-key TOP_SECRET_KEY --region REGION --cluster CLUSTER`

but it returns me an error:
`Incorrect Usage. flag provided but not defined: -access-key`

Am I doing something wrong or it is an issue?

upd: ecs-cli version is 1.0.0

**Comment by SoManyHs** [comment]
Hi @prozac631,

Did you mean to try `ecs-cli configure profile --access-key KEY_ID etc`? 

See the help text:
```
$ ecs-cli configure profile --help
NAME:
   ecs-cli configure profile - Stores a single profile.

USAGE:
   ecs-cli configure profile command [command options] [arguments...]

COMMANDS:
     default  Sets the default profile.

OPTIONS:
   --access-key value    Specifies the AWS access key to use. The ECS CLI uses the value of your $AWS_ACCESS_KEY_ID environment variable if it is set. [$AWS_ACCESS_KEY_ID]
   --secret-key value    Specifies the AWS secret key to use. The ECS CLI uses the value of your $AWS_SECRET_ACCESS_KEY environment variable if it is set. [$AWS_SECRET_ACCESS_KEY]
   --profile-name value  Specifies the profile name to use for this configuration. (default: "default")
   --help, -h            show help

```

**Comment by prozac631** [comment]
Hi!

Thank you a lot for the response - it helped me. There was an issue in the guide that I used.
