### ISSUE TITLE
ecs-cli compose create looks for task definition in default region

### ISSUE THREAD

**Issue by mattmcclean** [aws/amazon-ecs-cli#38]
Hi,

The ecs-cli compose create and up commands seem to have a bug whereby they check if a task definition exists in the default region instead of the region configured for the ecs cli config file: ~/.ecs/config. This seems to happen if you try and change the configured AWS region using the same compose file and cluster name.

I found this issue by performing the following:

1. Ran the following command to setup the ecs cli: ``ecs-cli configure --region eu-west-1 --cluster jenkins``
2. Setup the ECS cluster instances with the command: ``ecs-cli up --keypair <keypair> --capability-iam --size 2 --instance-type t2.medium``
3. Deployed the compose file with the command: ``ecs-cli compose --file jenkins-master.yml up``
4. Changed the region by running the command: ``ecs-cli configure --region us-east-1 --cluster jenkins``
5. Setup the ECS cluster instances with the command: ``ecs-cli up --keypair <keypair> --capability-iam --size 2 --instance-type t2.medium``
6. Ran the command to create the ECS task: ``ecs-cli compose --file jenkins-master.yml up``

The output I got was the following:

INFO[0000] Using ECS task definition                     TaskDefinition=ecscompose-jenkins-ecs:1
ERRO[0000] Error running tasks                           error=InvalidParameterException: Invalid Region in ARN
	status code: 400, request id: 3d8a1cb2-848b-11e5-83d9-b34077ba1855 task definition=arn:aws:ecs:eu-west-1:934676248949:task-definition/ecscompose-jenkins-ecs:1
FATA[0000] InvalidParameterException: Invalid Region in ARN
	status code: 400, request id: 3d8a1cb2-848b-11e5-83d9-b34077ba1855

If I run the create command: ``ecs-cli compose create --file jenkins-master.yml`` it does not check the task definition in the target region, only the default region.

Output:
INFO[0000] Using ECS task definition                     TaskDefinition=ecscompose-jenkins-ecs:1

Also, if the task definition is deregistered in the default region it still gives the same message and will not create a new task definition in the configured region.

**Comment by uttarasridhar** [comment]
Thanks for reporting!!
