### ISSUE TITLE
Allow for scaling clusters created in WebGUI

### ISSUE THREAD

**Issue by rajanski** [aws/amazon-ecs-cli#388]
ATM it doesn't seem to be possible to use the `ecs-cli scale` command on clusters that have not also been created using ecs-cli. It fails  with `Error executing 'scale': "CloudFormation stack not found for cluster`.
Reason is that ecs-cli does only look for a CFN prepended by "amazon-ecs-cli-setup-" and suffixed by cluster name. 
It doesnt seem to be possible to specify a different CFN stack name.

Also see https://github.com/aws/amazon-ecs-cli/issues/230#issuecomment-293349599

**Comment by PettitWesley** [comment]
@rajanski:

> ATM it doesn't seem to be possible to use the ecs-cli scale command on clusters that have not also been created using ecs-cli

In the current release of the ECS CLI (v1.1.0), you likely won't be able to use scale on a cluster created with another tool. However, the fix in #390 will go out in the next release of the ECS CLI and then `ecs-cli scale` should work with any CloudFormation templates that has a parameter named `AsgMaxSize` which defines the size of the cluster. This covers all CloudFormation templates created by the ECS CLI and ECS Console (Web UI).

**Comment by SoManyHs** [comment]
This fix for this (#390) was released yesterday. Please let us know if you have any further issues!
