### ISSUE TITLE
Creating cluster after update to 1.1.0

### ISSUE THREAD

**Issue by bee-keeper** [aws/amazon-ecs-cli#394]
Hi there,

I was using the following command to create a cluster with ecs-cli version 0.6.4:

`
ecs-cli up --cluster my-cluster --region=us-east-1 --keypair my-key --size 1 --instance-type t2.medium
--instance-role ecsInstanceRole --security-group xxx,xxx,xxx --vpc vpc-xxx --subnets xxx,xxx
`

Now with 1.1.0, I get the following error with the exact same command:

`
INFO[0001] Created cluster                               cluster=my-cluster region=us-east-1
FATA[0002] Error executing 'up': ValidationError: Template format error: Unresolved resource dependencies [EcsInstanceProfile] in the Resources block of the template
	status code: 400, request id: 8561398c-e001-11e7-83c6-d92b9ccd9b3c 
`

I've tried running this with verbose but it results in the same output and there's nothing in cloudformation - any idea how I can troubleshoot this please?

**Comment by SoManyHs** [comment]
Hi @bee-keeper,

Thanks so much for bringing up this issue. We've put up a fix for this bug in #395 and it should go out in the release planned for next Tuesday. Let me know if you have any other questions!

**Comment by bee-keeper** [comment]
Fantastic, would you like me to build a binary off your feature branch and verify?

**Comment by chrisdag** [comment]
Experiencing same issue on a client VPC. Can't create ECS EC2 cluster from CLI within a private VPC using similar settings as issue reporter -- see same error.  Is there a method to pull the fix and test it locally before the approved release? Trying to accelerate my testing before people vanish for the holiday :)

**Comment by SoManyHs** [comment]
Hi @chrisdag and @bee-keeper,

Sorry for the inconvenience! Yes, the easiest thing to do if you need to test this ahead of our release (scheduled for later this week) is to build the binary off the feature branch. Let me know if you have any questions about how to do this.

**Comment by chrisdag** [comment]
Have not built via 'go' before, the build_binary.sh script looks pretty straightforward. However if you had a cheat sheet for building off of the feature branch I'd appreciate it!  This client runs a "no internet access allowed" VPC so I'll be doing the build on a personal laptop rather than from an EC2 host. Thanks!
