### ISSUE TITLE
Support Spot instances for ECS 

### ISSUE THREAD

**Issue by vyncentk** [aws/amazon-ecs-cli#396]
Hi, 
since 6 months now, ECS cluster support EC2 Spot instances : https://aws.amazon.com/blogs/compute/powering-your-amazon-ecs-cluster-with-amazon-ec2-spot-instances/

It would be great if ecs-cli support this also :)

**Comment by yinshiua** [comment]
Thanks for the feedback. We will try to prioritize this. We are also open to contributions :)

**Comment by apophenist** [comment]
Hi there

Is this possible yet? It'd be great to be able to specify these parameters when creating a cluster, otherwise it's not possible to use spot pricing, and significantly increases the cost of using the ecs-cli for creating clusters (which is awesome, as it significantly decreases the cost of time)!

**Comment by apophenist** [comment]
Hi all

Something I was unaware of previously when posting (and really helpful here), is that you can create the cluster using the ecs-cli, and then adjust the CloudFormation Stack to switch to spot instances. This is as per: https://stackoverflow.com/questions/44637225/how-to-change-instance-type-in-aws-ecs-cluster 

Some notes:
- you'll need the IAM role for AWSServiceRoleForEC2SpotFleet, and the associated ARN
- you'll need to change the parameter for using spot instances to "true"
- you'll need to indicate the price

Note you can also change instance types here.

Really cool!

**Comment by vyncentk** [comment]
Hi @here,  just created a PR for this :) https://github.com/aws/amazon-ecs-cli/pull/626

**Comment by apophenist** [comment]
Going to save me some time with this one :)

**Comment by SoManyHs** [comment]
This is now available in 1.9.0!
