### ISSUE TITLE
Single quotes around strings don't work

### ISSUE THREAD

**Issue by euank** [aws/amazon-ecs-cli#4]
single quotes are valid around strings in YAML and often useful for avoiding escaping quotes.
The following task definition works with `docker-compose` but results in wrong behavior with `ecs-cli compose`.

```yaml
web:
    image: nginx
    ports: 
        - '80:80'
```

Running `ecs-cli compose up` results in the following error:
`ERRO[0000] Unable to open ECS Compose Project            error=Could not convert port into integer in portmappings: strconv.ParseInt: parsing "80'": invalid syntax`

This can also lead to incorrect behavior at runtime, such as with extraneous quotes in commands.

**Comment by uttarasridhar** [comment]
fixed in #121 and released in [v0.4.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v0.4.0).
