### ISSUE TITLE
ecs-cli writes access key and secret key to config file

### ISSUE THREAD

**Issue by lox** [aws/amazon-ecs-cli#40]
It looks like `ecs-cli configure` always writes `aws_access_key_id` and `aws_secret_access_key` to `~/.ecs/config`. This is terrible practice, as it creates another spot where credentials can be leaked to malware or attackers. It also makes using short-lived credentials annoyingly difficult. 

It seems the workaround is to delete the properties and rely on ENV variables.

The standard `aws cli` authentication mechanisms should be used, namely `~/.aws/config` and `~/.aws/credentials`. If credentials can't be found by the standard credential discovery mechanism for aws cli tools, `ecs-cli` should fail with "Can't find credentials".

**Comment by uttarasridhar** [comment]
`ecs-cli configure` supports `--profile` option that lets you specify an existing named profile from AWS cli (which is persisted at ~/.aws/credentials). You can also set AWS_PROFILE environment variable before running ecs-cli configure. In this case, we **do not** persist the credentials in ~/.ecs/config, but only the profile name.
You can find more information about configure in the [docs](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-configure.html)

--access-key and --secret-key options are there as a fall back mechanism in case you don't have aws cli installed and just want to specify keys directly to this tool.

Hope that addresses your concern. Feel free to reopen the issue anytime.

**Comment by lox** [comment]
Thanks, although you did persist the creds to `~/.ecs/config` when I filed the bug.
