### ISSUE TITLE
Support "desired-status" filter on [ecs-cli ps] to filter out stopped tasks

### ISSUE THREAD

**Issue by allisaurus** [aws/amazon-ecs-cli#400]
If you have a lot of recently stopped tasks it can be a pain to hone in on what's running when you run "ps", since these are inlcuded by default. Supporting "--desired-status" on ps would let you see all or just running tasks depending on what you need. 

Example output attached.
![tasks_ps](https://user-images.githubusercontent.com/34254888/34270544-647db4fc-e63d-11e7-98ee-b011cf139cdd.PNG)

**Comment by SoManyHs** [comment]
Reference: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_life_cycle.html

**Comment by allisaurus** [comment]
We released support for this in release [1.13.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v1.13.0)
