### ISSUE TITLE
FATA[0381] Deployment has not completed: Running count has not changed for 5.00 minutes

### ISSUE THREAD

**Issue by kaihendry** [aws/amazon-ecs-cli#401]
ecs-cli version 1.2.0 (8d555ea)

<img width="957" alt="screen shot 2017-12-22 at 12 22 08 pm" src="https://user-images.githubusercontent.com/765871/34285208-c9990ff0-e712-11e7-9c1f-629f901233fd.png">

I have a deploy script that uses ecs-cli to deploy with. It seems like the deployment process takes just over 5 minutes for me. 
```
mbp:frontend kaihendry$ ./deploy.sh
INFO[0000] Saved ECS CLI cluster configuration default.
WARN[0000] Skipping unsupported YAML option...           option name=networks
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=meteor
INFO[0005] Using ECS task definition                     TaskDefinition="meteor:12"
INFO[0005] Updated the ECS service with a new task definition. Old containers will be stopped automatically, and replaced with new ones  desiredCount=1 serviceName=ecscompose-service-meteor taskDefinition="meteor:12"
INFO[0005] Service status                                desiredCount=1 runningCount=1 serviceName=ecscompose-service-meteor
INFO[0035] (service ecscompose-service-meteor) has started 1 tasks: (task 75ff0189-446b-48be-9b05-78e128cd20b9).  timestamp=2017-12-22 03:55:24 +0000 UTC
INFO[0080] Service status                                desiredCount=1 runningCount=2 serviceName=ecscompose-service-meteor
INFO[0080] (service ecscompose-service-meteor) registered 1 targets in (target-group arn:aws:elasticloadbalancing:ap-southeast-1:812644853088:targetgroup/meteor/0617ca622a59e7e2)  timestamp=2017-12-22 03:56:16 +0000 UTC
INFO[0110] (service ecscompose-service-meteor) has begun draining connections on 1 tasks.  timestamp=2017-12-22 03:56:36 +0000 UTC
INFO[0110] (service ecscompose-service-meteor) deregistered 1 targets in (target-group arn:aws:elasticloadbalancing:ap-southeast-1:812644853088:targetgroup/meteor/0617ca622a59e7e2)  timestamp=2017-12-22 03:56:36 +0000 UTC


FATA[0381] Deployment has not completed: Running count has not changed for 5.00 minutes
```

First can I suggest your log lines output a timestamp?

Secondly, is my deployment atypically slow to result with this "FATAL" message? Despite in reality succeeding after 6 minutes?

End goal is to have an automated CLI deployment script where I know something successfully deployed.

**Comment by PettitWesley** [comment]
@kaihendry,

> Secondly, is my deployment atypically slow to result with this "FATAL" message? Despite in reality succeeding after 6 minutes?

All deployments are different, some take longer and some are faster. Because of the way the ECS APIs work, there's no way to tell when a deployment has failed, so we use a timeout. 5 minutes is the default, but you can configure it to serve your needs. Use `--timeout` to configure it:

```
   --timeout value                         Specifies the timeout value in minutes (decimals supported) to wait for the running task count to change. If the running task count has not changed for the specified period of time, then the CLI times out and returns an error. Setting the timeout to 0 will cause the command to return without checking for success. (default: 5)
```

Example:
`ecs-cli compose service up --timeout 6.5`

> First can I suggest your log lines output a timestamp?

This is a decent idea; I'll mark it down as a feature request!
