### ISSUE TITLE
Task transparency

### ISSUE THREAD

**Issue by kaihendry** [aws/amazon-ecs-cli#402]
Hi, often a task is based on a specific version of a Docker image.

But when ultimately when you interrogate your ECS cluster, you have an output like:

```
mytask:16
mytask:16
```

How do people figure out that `mytask:16` is actually running the image `ubuntu@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2` or something like that? A switch to aws cli?

Be good if you could review:
* https://github.com/kaihendry/frontend/blob/ecs/deploy.sh
* https://travis-ci.org/kaihendry/frontend/builds/321320870

**Comment by PettitWesley** [comment]
@kaihendry, I'm interested in understanding your use case. Are you asking to see the sha256 digest of the image in the`ecs-cli ps` command?

**Comment by PettitWesley** [comment]
Closing due to lack of response, feel free to re-open.
