### ISSUE TITLE
Allow for MFA in .ecs/credentials

### ISSUE THREAD

**Issue by djstein** [aws/amazon-ecs-cli#409]
I know the issue is currently open to prompt for MFA token (which would be awesome too) #284

As described by the [ecs-cli configure profile page ](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-configure-profile.html) we are allowed to add `aws_access_key_id` and `aws_secret_access_key`. can we add support for `aws_session_token` in the .ecs/credentials YAML file to mirror .aws credentials files?

**Comment by PettitWesley** [comment]
@djstein, we can add support for `aws_session_token` in `.ecs/credentials`; I'm marking this as a feature request.

**Comment by PettitWesley** [comment]
@djstein We have added support for `aws_session_token` in ECS Profiles with ECS CLI v1.4.0, released today!
