### ISSUE TITLE
cache gets in the way sometimes.

### ISSUE THREAD

**Issue by hutchic** [aws/amazon-ecs-cli#41]
Ran into problems where I created a task in one AWS account. Switched to a different AWS account and kept getting cache hits.

Additionally deleting tasks doesn't refresh the cache and it just keeps hitting the cache as well. Solution turned out to be `rm -rf ~/.cache` which I don't think is acceptable.

**Comment by uttarasridhar** [comment]
related to #38

**Comment by samuelkarp** [comment]
This was fixed by #45.
