### ISSUE TITLE
Task Deployment Never Ending

### ISSUE THREAD

**Issue by alihalabyah** [aws/amazon-ecs-cli#427]
Hi AWS Team,

I'm experiencing a weird behavior in which the below command either keep repeating the process of creating tasks or it will fail with the below error:

```
ecs-cli compose --project-name swagger-ui-service --file docker-compose.yml service up
```

```
WARN[0000] Skipping unsupported YAML option...           option name=networks
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=swagger-ui
INFO[0001] Using ECS task definition                     TaskDefinition="swagger-ui-service:6"
INFO[0002] Updated the ECS service with a new task definition. Old containers will be stopped automatically, and replaced with new ones  desiredCount=1 serviceName=swagger-ui-service taskDefinition="swagger-ui-service:6"
INFO[0003] Service status                                desiredCount=1 runningCount=1 serviceName=swagger-ui-service
INFO[0048] (service swagger-ui-service) has started 1 tasks: (task 2d578c89-3c18-41f9-89b8-6983238b95b8).  timestamp=2018-02-15 12:43:25 +0000 UTC
INFO[0155] Service status                                desiredCount=1 runningCount=2 serviceName=swagger-ui-service
INFO[0171] (service swagger-ui-service) registered 1 targets in (target-group arn:aws:elasticloadbalancing:us-east-1:218629194539:targetgroup/TG2/e1868c2f57e43733)  timestamp=2018-02-15 12:45:25 +0000 UTC
INFO[0186] (service swagger-ui-service) deregistered 1 targets in (target-group arn:aws:elasticloadbalancing:us-east-1:218629194539:targetgroup/TG2/e1868c2f57e43733)  timestamp=2018-02-15 12:45:47 +0000 UTC
INFO[0186] (service swagger-ui-service) has begun draining connections on 1 tasks.  timestamp=2018-02-15 12:45:47 +0000 UTC
FATA[0460] Deployment has not completed: Running count has not changed for 5.00 minutes
```

**Comment by SoManyHs** [comment]
Hi @alihalabyah,

Could you please provide the `docker-compose.yml` file you used for this command? Thanks!

**Comment by eisho** [comment]
Hi @alihalabyah,

I got same failure. In my case, my cluster needs 7 minutes to complete deployment. 

You may try adding timeout flag to change default timeout min.

`ecs-cli compose  service up --timeout 10`

**Comment by SoManyHs** [comment]
Hi @alihalabyah, were you able to reproduce this issue? To add to the previous comment, you can also set the `--timeout` to 0 in order to not check that the service successfully deployed within any time window. You can also run `aws ecs list-services` on your cluster to verify that the service was started.

**Comment by SoManyHs** [comment]
Hi @alihalabyah,
Please let us know if you're still experiencing issues. I'll close this for now but feel free to re-open.

**Comment by kuongknight** [comment]
@SoManyHs I set --timeout 10 but I still got this error:

> FATA[0460] Deployment has not completed: Running count has not changed for 5.00 minutes

**Comment by SoManyHs** [comment]
Hi @kuongknight,

Could you possibly try describing your service to see what events are associated with its deployment?

`aws ecs describe-services --service <your_service> --cluster <your_cluster>`

**Comment by SoManyHs** [comment]
@kuongknight Great, do you need further assistance?

**Comment by kuongknight** [comment]
@SoManyHs No! But It is better if you check that case: ecs-cli compose service up with both options —force-deployment and —timeout, seems timeout is not working!!
