### ISSUE TITLE
ExitCode: 0 on data-only container

### ISSUE THREAD

**Issue by bdart** [aws/amazon-ecs-cli#43]
I have multiple data-only containers that shall provide persistent data to multiple other containers. It is quite easy to set everything up. But when pushing it with `ecs-cli compose up` and than check what happened with `ps` it prompts:
`ExitCode: 0`

I assume that the problem is that data-only containers do not keep running. Could this be the problem?

**Comment by uttarasridhar** [comment]
Would it help to use persistent data volumes for your use case? You can read more about it in [our docs](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_data_volumes.html).

**Comment by davibe** [comment]
I got the same issue. I think the "nonpersistent empty data volumes" explained in the docs does not cover this case. I want to use data-only containers to provide a ready to use volume that is preloaded with some specific data. In this case the volume is not empty. It contains data from the image, and the data-only container does not actually run anything.

**Comment by tobowers** [comment]
Also, using data-only containers gives you a volume with the correct permissions, etc.
