### ISSUE TITLE
cannot create cluster if VPC ID is long

### ISSUE THREAD

**Issue by sharuzzaman** [aws/amazon-ecs-cli#430]
I recently opted for long VPC ID, and when doing test, the cluster with long VPC ID fail to start with error message, but cluster with short VPC ID can start successfully.

error message:
[ec2-user@ip-172-31-10-149 ~]$ ecs-cli up --cluster long-id-test --keypair ec2-key --capability-iam --size 2 --instance-type t2.medium --vpc vpc-06da6846b38178d68 --subnets subnet-00323b0c70337b637,subnet-09b663c22fe54645f
INFO[0000] Created cluster                               cluster=long-id-test region=ap-southeast-2
FATA[0000] Error executing 'up': ValidationError: Parameter VpcId failed to satisfy constraint: VPC Id must begin with 'vpc-' or leave blank to have a new VPC created
        status code: 400, request id: f7f9842d-15f7-11e8-93ca-9dfceff5ca52

success message:
[ec2-user@ip-172-31-10-149 ~]$ ecs-cli up --keypair ec2-key --capability-iam --size 2 --instance-type t2.medium --vpc vpc-2605db41 --subnets subnet-32ddb955,subnet-fedfbb99
INFO[0000] Created cluster                               cluster=test-cluster region=ap-southeast-2
INFO[0000] Waiting for your cluster resources to be created...
INFO[0000] Cloudformation stack status                   stackStatus="CREATE_IN_PROGRESS"
INFO[0060] Cloudformation stack status                   stackStatus="CREATE_IN_PROGRESS"
INFO[0121] Cloudformation stack status                   stackStatus="CREATE_IN_PROGRESS"
Security Group created: sg-1110dc68
Cluster creation succeeded.

thanks

**Comment by sharuzzaman** [comment]
Created SIM report. PM me for the case number

**Comment by sharuzzaman** [comment]
Not an issue with CloudFormation verification.

The template created by ecs-cli have hard coded 8 character limit.

 "VpcId": {
      "Type": "String",
      "Description": "Optional - VPC Id of existing VPC. Leave blank to have a new VPC created",
      "Default": "",
      "AllowedPattern": "^(?:vpc-[0-9a-f]{8}|)$",
      "ConstraintDescription": "VPC Id must begin with 'vpc-' or leave blank to have a new VPC created"
    },

Long VPC ID is 17 hex character.

**Comment by sharuzzaman** [comment]
created pull request #431 to fix this issue

**Comment by sharuzzaman** [comment]
new pull request #433 created

**Comment by SoManyHs** [comment]
Hi @sharuzzaman, we'd love to resolve this issue if you address the comment regarding the commit message in #433. Thanks!

**Comment by SoManyHs** [comment]
Addressed by #447, pending release later this week.
