### ISSUE TITLE
Fargate metadata URL

### ISSUE THREAD

**Issue by dulimitta** [aws/amazon-ecs-cli#434]
Will the fargate instances have metadata url? 
Spring Cloud Netflix will rely on metadata url to get the host details of the server. It is working with EC2 type but for fargate type, the code is failing to get the host details.

**Comment by SoManyHs** [comment]
Hi @dulimitta,

Since AWS Fargate manages the underlying infrastructure for you, you cannot access the instance metadata when using the `FARGATE` launch type, unfortunately. If you need the instance metadata, you may want to stick to the classic `EC2` launch type.

**Comment by dulimitta** [comment]
Hi @SoManyHs , thanks for the reply. I am not trying to access the Fargate instance from outside network. I am trying to deploy micro-services using the Spring Cloud Eureka. The services need the private/public IP addresses to get registered in the service registry. Is there any other way that the service can get the fargate instance private IP information?

**Comment by SoManyHs** [comment]
Hi @dulimitta,

Could you provide the `docker-compose.yml` and `ecs-params.yml` file you are using to launch your service?  Thanks!

**Comment by dulimitta** [comment]
I am launching Fargate instance using the ECS from the console.
I am nost sure where can I get docker-compose.yml and ecs-params.yml Here is my task definition. 

``


{
  "executionRoleArn": "arn:aws:iam::xxxxxxxx:role/ecsTaskExecutionRole",
  "containerDefinitions": [
    {
      "dnsSearchDomains": null,
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "/ecs/xxxx-service",
          "awslogs-region": "us-east-1",
          "awslogs-stream-prefix": "ecs"
        }
      },
      "entryPoint": null,
      "portMappings": [
        {
          "hostPort": 8006,
          "protocol": "tcp",
          "containerPort": 8006
        }
      ],
      "command": null,
      "linuxParameters": null,
      "cpu": 20,
      "environment": [
        {
          "name": "spring.profiles.active",
          "value": "qa"
        }
      ],
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "dockerSecurityOptions": null,
      "memory": null,
      "memoryReservation": 300,
      "volumesFrom": [],
      "image": "xxxxxx.dkr.ecr.us-east-1.amazonaws.com/xxxxxx-service",
      "disableNetworking": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "privileged": null,
      "name": "xxxxx-service"
    }
  ],
  "placementConstraints": [],
  "memory": "1024",
  "taskRoleArn": "arn:aws:iam::xxxxxx:role/ecsTaskExecutionRole",
  "compatibilities": [
    "EC2",
    "FARGATE"
  ],
  "taskDefinitionArn": "arn:aws:ecs:us-east-1:xxxxxx:task-definition/fargate-file-service:4",
  "family": "xxxxxx-service",
  "requiresAttributes": [
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-ecr-pull"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.task-eni"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.ecr-auth"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.task-iam-role"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.21"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
    }
  ],
  "requiresCompatibilities": [
    "FARGATE"
  ],
  "networkMode": "awsvpc",
  "cpu": "512",
  "revision": 4,
  "status": "ACTIVE",
  "volumes": []
}


``

**Comment by SoManyHs** [comment]
Hi @dulimitta,

This GitHub repository is for the ECS CLI. You can refer to this [tutorial](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_tutorial_fargate.html) for creating a Fargate task or service using the CLI. Otherwise, please feel free to contact our [support team ](https://aws.amazon.com/contact-us/)for questions about using ECS via the console.

Regardless of whether you use the console or the CLI, instance metadata cannot be accessed whe using Fargate.

**Comment by dulimitta** [comment]
Sure, thanks @SoManyHs
