### ISSUE TITLE
ecs-cli compose service up fails with the "create the service first"

### ISSUE THREAD

**Issue by pmoosh** [aws/amazon-ecs-cli#436]
I have see on multiple occasions - recently but almost exclusively in the us-east-1 region
"ecs-cli compose service up" failed with the following error:

time="2018-02-12T16:59:10Z" level=info msg="Created an ECS service" service=nanana taskDefinition="nanana:1" 
time="2018-02-12T16:59:10Z" level=fatal msg="Please use 'create' command to create the service 'nanana' first" 

According to the documentation this seems to be wrong - ecs-cli compose service up should show the following behavior:
Creates an ECS service from your compose file (if it does not already exist) and runs one instance of that task on your cluster (a combination of create and start).
ECS Cluster Name: None specific
Service Name or Task Definition Name: None specific

When I simple rerun the command it completes successfully.

Using ecs-cli 1.3.0 docker-compose file Version 2

**Comment by SoManyHs** [comment]
HI @pmoosh,

Could you please provide your `~/.ecs/config`, your `docker-compose.yml` and `ecs-params.yml` file (if one exists)? Thanks!

**Comment by pmoosh** [comment]
Sure. No ecs-params.yml...
Here is an example:
+ cat /var/lib/jenkins/.ecs/config
version: v1
default: portal
clusters:
  default:
    cluster: testbg
    region: us-east-2
    default_launch_type: EC2
  portal:
    cluster: ecseast1
    region: us-east-1
    default_launch_type: EC2

docker-compose file:
version: '2'
services:
  portal-web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: ${WEB_IMAGE}
    depends_on:
      - portal-app
    links:
      - portal-app
    ports:
      - "${WEBPORT}:80"
    logging:
      driver: awslogs
      options:
        awslogs-region: ${REGION}
        awslogs-group: ${AWSLOGS}
        awslogs-stream-prefix: ${NAME}
    # calculated using 1.25 * MEM USAGE from docker stats
#    mem_limit:   14800000
  portal-app:
    build:
      context: .
    image: ${APP_IMAGE}
    expose:
      - "3001"
    environment:
      - API_ADDRESS=${API_ADDRESS}
      - REDIS_SERVER=${REDIS_SERVER}
      - RAILS_ENV=${RAILS_ENV}
    logging:
      driver: awslogs
      options:
        awslogs-region: ${REGION}
        awslogs-group: ${AWSLOGS}
        awslogs-stream-prefix: ${NAME}
    # calculated using 1.25 * MEM USAGE from docker stats
    # mem_limit: 319250000

Hope this helps

**Comment by SoManyHs** [comment]
@pmoosh I'm not seeing anything unusual. You mentioned that you were able to retry your command (`ecs-cli compose service up`) and it completed successfully, correct? Were you able to reproduce the error consistently?

**Comment by pmoosh** [comment]
Not consistently. I would guess that there is some kind of race condition when the command is run the 1st time. The service is being created but the command end before that or so. 
I will check if it happens again.

**Comment by SoManyHs** [comment]
@pmoosh If you're able to reproduce this, could you provide the full stack trace that's output, including the request ID? Thanks!

**Comment by pmoosh** [comment]
I will if I see that again. Lately it didn't reoccur - thx @SoManyHs

**Comment by pmoosh** [comment]
Well it still occurs

**Comment by SoManyHs** [comment]
@pmoosh Could you provide the full stack trace that's output, including the request ID? Thanks!

**Comment by pmoosh** [comment]
I think this is a duplicate of:
https://github.com/aws/amazon-ecs-cli/issues/79
didn't see that before
So this can be closed
