### ISSUE TITLE
ecs-cli up fails if stack already exists for the cluster

### ISSUE THREAD

**Issue by danehammer** [aws/amazon-ecs-cli#44]
... but the doc indicates it will handle this. When you go through [this tutorial](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_tutorial.html) you fail a few times as you find out what permissions are required. It shouldn't require deleting a stack (with no instances running) to re-run the up command.

**Comment by dtest** [comment]
+1

**Comment by autopulated** [comment]
+1 still an issue.

**Comment by canzhiye** [comment]
+1

**Comment by schickling** [comment]
+1 via cloudformation
