### ISSUE TITLE
Any ecs-cli compatibility for compose version 2.1?

### ISSUE THREAD

**Issue by calvinkw1** [aws/amazon-ecs-cli#467]
### Summary
Trying to use a `docker-compose.yml` file specifying version 2.1 which includes a `healthcheck` feature as well as some syntax changes to `depends_on`, however, it seems like `libcompose` doesn't support version 2.1 yet, so running `ecs-cli compose service up` errors out.

Is there a workaround? Do you plan to support compose 2.1? Or am I doing something wrong here?

### Description
Provide detailed information about this issue, including:
* Which specific command was run (Example: `ecs-cli up --capability-iam --size 2 --launch-type EC2`

        $ ecs-cli compose service up

* Which version of the CLI you are using (Run: `ecs-cli --version`)

        $ ecs-cli --version
        ecs-cli version 1.4.2 (006f51f)

### Expected Behavior
Expected something similar to...

    $ docker-compose up -d
    Starting service1    ... done
    Starting service2 ... done
    Starting service3 ... done
    Starting service4  ... done
    Starting service5  ... done

### Observed Behavior

    $ ecs-cli compose service up
    ERRO[0000] Could not parse config for project cryptospike : yaml: unmarshal errors:
    line 1: cannot unmarshal !!str `2.1` into config.RawService
    ERRO[0000] Unable to open ECS Compose Project            error="yaml: unmarshal errors:\n  line 1: 
    cannot unmarshal !!str `2.1` into config.RawService"
    FATA[0000] Unable to create and read ECS Compose Project  error="yaml: unmarshal errors:\n  
    line 1: cannot unmarshal !!str `2.1` into config.RawService"

### Config files

* [docker-compose.yml](https://github.com/bigchaindb/bigchaindb/blob/master/docker-compose.yml)
* ecs-params.yml
```version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 4GB
    cpu_limit: 2048
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-1"
        - "subnet-2"
      security_groups:
        - "sg-1"
      assign_public_ip: ENABLED

**Comment by allisaurus** [comment]
Unfortunately, we don't currently have a good work around for supporting minor versions of Compose 2, due to the libcompose limitation you pointed out. However, we are working on adding support for Compose 3, which includes the `healthcheck` feature you're using - would support for 3 solve your problem or are there specific 2.1-4 features you rely on that lose support in 3?

See previous issue re: version  - https://github.com/aws/amazon-ecs-cli/issues/305

**Comment by calvinkw1** [comment]
@allisaurus thanks for the reply. Support for v3 would solve the issue, but there's no immediate need for it. Was just surprised to find out that the Compose compatibility differed between AWS/Docker.

I ended up abandoning ECS and just ran `docker-compose` on an EC2 instance.
