### ISSUE TITLE
Failure event: The availability zones of the specified subnets and the AutoScalingGroup do not match

### ISSUE THREAD

**Issue by PLEEROCK** [aws/amazon-ecs-cli#47]
When Im calling ecs-cli up with vpc and subnets parameters it gives me error:
```ERRO[0192] Failure event                                 reason=The availability zones of the specified subnets and the AutoScalingGroup do not match resourceType=AWS::AutoScaling::AutoScalingGroup```

same as here http://serverfault.com/questions/732220/docker-project-on-aws-ecs

**Comment by PLEEROCK** [comment]
could resolve it only with specifying --azs manually too. However documentation doesnt say that its required

**Comment by dtest** [comment]
Could this be re-opened so that the AZs aren't random if supplying a subnet list?
