### ISSUE TITLE
ecscompose-service Prefix

### ISSUE THREAD

**Issue by alexw23** [aws/amazon-ecs-cli#51]
What is the purpose of this prefix?

https://github.com/aws/amazon-ecs-cli/blob/968c864e7088da1e25a1b2e3d55e3d4668161907/ecs-cli/modules/compose/ecs/utils/name.go#L27

I think it clutters things in the UI and adds an unnecessary ecscompose-service to all services? Can this be something that is toggled off via command line?

**Comment by uttarasridhar** [comment]
released in [v0.3.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v0.3.0).

Its usage and some examples can be found in [our docs](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-configure.html).
