### ISSUE TITLE
docker-compose question

### ISSUE THREAD

**Issue by bruno-ab** [aws/amazon-ecs-cli#525]
Q quick question about my docker-compose  

version: "2"
services:

    webserver:
      image: nginx:alpine
      container_name: crow-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "4000:80"

    php-fpm:
      build: docker/php-fpm
      container_name: crow-php-fpm
      working_dir: /application
      volumes:
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini 
        - .:/application
        
    composer:
      restart: 'no'
      container_name: crow-composer
      working_dir: /application
      image: prooph/composer:7.2
      command: install
      volumes:
        - .:/application

Quick question, what is the problem with this docker-compose? not working to use with cli-compose on Ec2 or Fargate

**Comment by allisaurus** [comment]
Hi @bruno-ab - the ecs-cli does not currently support the "build" key, which you're using in the "php-fpm" service (see supported opens in our [docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-service.html)). It should work if you can swap this out for a pre-built image (using the "image" key).

**Comment by allisaurus** [comment]
Closing due to lack of response; please feel free to re-open if you have further questions.
