### ISSUE TITLE
Support environment variables in ecs-params.yml

### ISSUE THREAD

**Issue by seanson** [aws/amazon-ecs-cli#530]
### Summary
Support environment variables in ecs-params.yml:

As part of our deployments we're looking to specify task parameters per-environment but maintain the ease of a single `ecs-params.yml`. libcompose already provides environment variable support for `docker-compose.yml` and it would be great to have this supported for ECS parameters as well.

### Description

I have a basic implementation with `os.ExpandEnv` that covers our use cases but does not support some of the more complicated `envsubst` style expansion ( such as default values with `${CPU_LIMIT:-50}`). This could be achieved with an external library like https://github.com/drone/envsubst. There is also the possibility of using the libcompose functions like `Interpolate` but at first investigation this would require some changes around how we handle data in `ReadECSParams`.

### Config files
* ecs-params.yml
```
version: 1
task_definition:
  task_size:
    cpu_limit: ${CPU_LIMIT}
    mem_limit: ${MEM_LIMIT}
```

**Comment by seanson** [comment]
All merged, thanks for the support :)

**Comment by maxpearl** [comment]
This is great - but it doesn't support variables in an .env file, which is standard for docker. Any chance of this?

**Comment by seanson** [comment]
> This is great - but it doesn't support variables in an .env file, which is standard for docker. Any chance of this?

Feel free to open a new issue and raise a PR.
