### ISSUE TITLE
Unsupported YAML Option

### ISSUE THREAD

**Issue by syphon7** [aws/amazon-ecs-cli#54]
When I try and run ecs-cli compose with a docker compose file I get the following error:

WARN[0000] Skipping unsupported YAML option...           option name=hostname

**Comment by uttarasridhar** [comment]
This commit 82b379a6226f15d2fdeab0a393ac2105bb12f89f added support for hostname option. Pending release.

**Comment by uttarasridhar** [comment]
released in [v0.2.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v0.2.0)
