### ISSUE TITLE
Expose schedulingStrategy parameter via ecs-cli

### ISSUE THREAD

**Issue by SergK** [aws/amazon-ecs-cli#540]
### Expose schedulingStrategy via ecs-cli
schedulingStrategy should be exposed via ecs-cli

### Description
As ecs-cli user I want to have an ability to run ecs service with different **service scheduler strategies**:

- REPLICA
- DAEMON

either using `ecs-cli` or getting options from `docker-compose`.

Please check documentation [[1]](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_services.html#service_scheduler_daemon)

By default **REPLICA** is used, but switching to **DAEMON** will allow us to run task on each container instance without additional effort (e.g. see https://github.com/aws/amazon-ecs-agent/issues/748)

Option can be:
`--ServiceSchedulingStrategy replica`
or
`--ServiceSchedulingStrategy daemon`

The same parameter name can be used in docker-compose file

**Comment by allisaurus** [comment]
Hi all, we released support for this in release [1.13.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v1.13.0) !
