### ISSUE TITLE
Unable to use ec2 iam instance role

### ISSUE THREAD

**Issue by jmarcos-cano** [aws/amazon-ecs-cli#548]
### Summary
Im unable to use EC2 instance role (metadata)

aws cli works fine.

```
aws configure --profile default list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                  default           manual    --profile
access_key     ****************JFDQ         iam-role
secret_key     ****************4fBH         iam-role
    region                us-west-2      config-file    ~/.aws/config
```

### Description

I ran `ecs-cli configure profile  --profile-name ec2-tutorial` and it fails with:

```
[centos@ip-10-20-3-28 ~]$ ecs-cli configure profile  --profile-name ec2-tutorial
FATA[0000] secret-key can not be empty
```
version:
```
 ecs-cli --version
ecs-cli version 1.6.0 (95406b1)
```

### Config files
not using any config file, but EC2 instance role
however:

* ~/.aws/config: 
```cat ~/.aws/config
[default]
output = json
region = us-west-2
```

### Expected Behavior
configure profile using ec2 instance profile

### Observed Behavior
```
[centos@ip-10-20-3-28 ~]$ ecs-cli configure profile  --profile-name ec2-tutorial
FATA[0000] secret-key can not be empty
```

**Comment by PettitWesley** [comment]
@jmarcos-cano the ecs-cli configure command is for storing AWS Access Key and AWS Secret Key. If you're using an instance role, you should not need to use the configure command. If you run the ECS CLI on an EC2 instance, then the ECS CLI will use the instance role if it is available. Please note that for the CLI, EC2 instance role has the lowest priority in our [order of resolution for credentials](https://github.com/aws/amazon-ecs-cli#configuring-defaults).
