### ISSUE TITLE
`ecs-cli ps` throws "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by awood45** [aws/amazon-ecs-cli#55]
When attempting to run `ecs-cli ps`, consistently seeing a nil pointer error.

Output:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xe0 pc=0xe3698]

goroutine 1 [running]:
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.getContainersForTasks(0x8820d2f260, 0x820f98480, 0x820e8e000, 0x95, 0xa0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /private/tmp/amazon-ecs-cli20151017-49504-1xj8wtw/amazon-ecs-cli-0.1.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/entity.go:194 +0x498
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.collectContainers(0x8820d2f260, 0x820f98480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /private/tmp/amazon-ecs-cli20151017-49504-1xj8wtw/amazon-ecs-cli-0.1.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/entity.go:112 +0x101
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.info(0x8820d2f260, 0x820f98480, 0x8820d2f200, 0x0, 0x0, 0x0, 0x0, 0x0)
    /private/tmp/amazon-ecs-cli20151017-49504-1xj8wtw/amazon-ecs-cli-0.1.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/entity.go:97 +0x67
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.(_Task).Info(0x820f98480, 0x8820d2f200, 0x0, 0x0, 0x0, 0x0, 0x0)
    /private/tmp/amazon-ecs-cli20151017-49504-1xj8wtw/amazon-ecs-cli-0.1.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/task.go:95 +0x7b
github.com/aws/amazon-ecs-cli/ecs-cli/modules/command.clusterPS(0x820bd01e0, 0x8820cf0b50, 0x820b4bd40, 0x8820cf0aa0, 0x820b45980, 0x0, 0x0, 0x0, 0x0, 0x0)
    /private/tmp/amazon-ecs-cli20151017-49504-1xj8wtw/amazon-ecs-cli-0.1.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/command/cluster_app.go:264 +0x244
github.com/aws/amazon-ecs-cli/ecs-cli/modules/command.ClusterPS(0x820bd01e0)
    /private/tmp/amazon-ecs-cli20151017-49504-1xj8wtw/amazon-ecs-cli-0.1.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/command/cluster_app.go:103 +0x2ac
github.com/codegangsta/cli.Command.Run(0x6a7550, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7987e0, 0x37, 0x0, ...)
    /private/tmp/amazon-ecs-cli20151017-49504-1xj8wtw/amazon-ecs-cli-0.1.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/codegangsta/cli/command.go:127 +0x1052
github.com/codegangsta/cli.(_App).Run(0x820bcc400, 0x820b44260, 0x2, 0x2, 0x0, 0x0)
    /private/tmp/amazon-ecs-cli20151017-49504-1xj8wtw/amazon-ecs-cli-0.1.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/codegangsta/cli/app.go:159 +0xc2f
main.main()
    /private/tmp/amazon-ecs-cli20151017-49504-1xj8wtw/amazon-ecs-cli-0.1.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/main.go:43 +0x96c

goroutine 15 [IO wait]:
net.runtime_pollWait(0x8820cf1f48, 0x72, 0x820b4a160)
    /usr/local/Cellar/go/1.5.1/libexec/src/runtime/netpoll.go:157 +0x60
net.(_pollDesc).Wait(0x820c48140, 0x72, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(_pollDesc).WaitRead(0x820c48140, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(_netFD).Read(0x820c480e0, 0x820c94000, 0x8000, 0x8000, 0x0, 0x8820cec050, 0x820b4a160)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_unix.go:232 +0x23a
net.(_conn).Read(0x820c4a010, 0x820c94000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/net.go:172 +0xe4
crypto/tls.(_block).readFromUntil(0x820c464e0, 0x8820d2c2b0, 0x820c4a010, 0x5, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(_Conn).readRecord(0x820c5a000, 0x7f9517, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(_Conn).Read(0x820c5a000, 0x820b53000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x8820cfbc48, 0x820c5a000, 0x820bf23c8, 0x820b53000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:1370 +0x67
net/http.(_noteEOFReader).Read(0x820fd9fe0, 0x820b53000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(_Reader).fill(0x820def020)
    /usr/local/Cellar/go/1.5.1/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(_Reader).Peek(0x820def020, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/bufio/bufio.go:132 +0xcc
net/http.(_persistConn).readLoop(0x820bf2370)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:876 +0xf7
created by net/http.(_Transport).dialConn
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:685 +0xc78

goroutine 16 [select]:
net/http.(_persistConn).writeLoop(0x820bf2370)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:1009 +0x40c
created by net/http.(_Transport).dialConn
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:686 +0xc9d

goroutine 24 [IO wait]:
net.runtime_pollWait(0x8820cf1dc8, 0x72, 0x820b4a160)
    /usr/local/Cellar/go/1.5.1/libexec/src/runtime/netpoll.go:157 +0x60
net.(_pollDesc).Wait(0x820d8f3a0, 0x72, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(_pollDesc).WaitRead(0x820d8f3a0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(_netFD).Read(0x820d8f340, 0x820f71000, 0x800, 0x800, 0x0, 0x8820cec050, 0x820b4a160)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_unix.go:232 +0x23a
net.(_conn).Read(0x820b64088, 0x820f71000, 0x800, 0x800, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/net.go:172 +0xe4
crypto/tls.(_block).readFromUntil(0x8210bd5f0, 0x8820d2c2b0, 0x820b64088, 0x5, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(_Conn).readRecord(0x820c5a2c0, 0x7f9517, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(_Conn).Read(0x820c5a2c0, 0x8210d4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x8820cfbc48, 0x820c5a2c0, 0x820eb6058, 0x8210d4000, 0x1000, 0x1000, 0x82101ed00, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:1370 +0x67
net/http.(_noteEOFReader).Read(0x820f439e0, 0x8210d4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(_Reader).fill(0x8210bfaa0)
    /usr/local/Cellar/go/1.5.1/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(_Reader).Peek(0x8210bfaa0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/bufio/bufio.go:132 +0xcc
net/http.(_persistConn).readLoop(0x820eb6000)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:876 +0xf7
created by net/http.(_Transport).dialConn
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:685 +0xc78

goroutine 25 [select]:
net/http.(_persistConn).writeLoop(0x820eb6000)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:1009 +0x40c
created by net/http.(_Transport).dialConn
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:686 +0xc9d

**Comment by jeremymills** [comment]
getting the same issue, happens right after I do a `ecs-cli compose up` and then `ecs-cli ps`

**Comment by jeremymills** [comment]
"Temporary fix" is to ssh into the instance and remove all stopped docker containers and restart `ecs`, this got it working again for me

**Comment by bbakersmith** [comment]
Seeing this as well.

**Comment by klindklind** [comment]
I also have this problem with the latest ecs-cli 0.3.0. 

When I was running ECS on the same account I'm logging in with ecs-cli I had no problem calling ecs-cli commands. But when I'm assuming cross-account role using `--profile` argument with `ecs-cli configure` command and trying to run ecs-cli commands I get:

`$ ecs-cli ps
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x384050]

goroutine 1 [running]:
panic(0x66ca40, 0xc8200100e0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).GetMetadata(0x0, 0x8176a0, 0x19, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/amazon-ecs-cli-20160519-4261-1vszurp/amazon-ecs-cli-0.3.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:24 +0x1b0
github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.requestCredList(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/amazon-ecs-cli-20160519-4261-1vszurp/amazon-ecs-cli-0.3.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:133 +0x74
github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.(*EC2RoleProvider).Retrieve(0xc8200f2480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/amazon-ecs-cli-20160519-4261-1vszurp/amazon-ecs-cli-0.3.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:89 +0x8b
github.com/aws/aws-sdk-go/aws/credentials.(*ChainProvider).Retrieve(0xc8200f24b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/amazon-ecs-cli-20160519-4261-1vszurp/amazon-ecs-cli-0.3.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/aws/aws-sdk-go/aws/credentials/chain_provider.go:75 +0x122
github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).Get(0xc82005a6c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/amazon-ecs-cli-20160519-4261-1vszurp/amazon-ecs-cli-0.3.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/aws/aws-sdk-go/aws/credentials/credentials.go:185 +0x121
github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.(*CliConfig).ToServiceConfig(0xc82002c0a8, 0x788f70, 0x0, 0x0)
	/private/tmp/amazon-ecs-cli-20160519-4261-1vszurp/amazon-ecs-cli-0.3.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/config.go:68 +0x8a7
github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.NewCliParams(0xc8201000f0, 0xd04be0, 0xc8200116d0, 0xd04be0, 0x0, 0x0)
	/private/tmp/amazon-ecs-cli-20160519-4261-1vszurp/amazon-ecs-cli-0.3.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/params.go:63 +0x3b7
github.com/aws/amazon-ecs-cli/ecs-cli/modules/command.glob.func1(0xc8201000f0, 0xd04be0, 0xc8200116d0, 0x10, 0x0, 0x0)
	/private/tmp/amazon-ecs-cli-20160519-4261-1vszurp/amazon-ecs-cli-0.3.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/command/cluster_app.go:174 +0x41
github.com/aws/amazon-ecs-cli/ecs-cli/modules/command.clusterPS(0xc8201000f0, 0xd04be0, 0xc8200116d0, 0xd04b30, 0xc8200b9b40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/amazon-ecs-cli-20160519-4261-1vszurp/amazon-ecs-cli-0.3.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/command/cluster_app.go:265 +0x7d
github.com/aws/amazon-ecs-cli/ecs-cli/modules/command.ClusterPS(0xc8201000f0)
	/private/tmp/amazon-ecs-cli-20160519-4261-1vszurp/amazon-ecs-cli-0.3.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/command/cluster_app.go:104 +0x2ac
github.com/codegangsta/cli.Command.Run(0x788bf8, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x87e740, 0x37, 0x0, ...)
	/private/tmp/amazon-ecs-cli-20160519-4261-1vszurp/amazon-ecs-cli-0.3.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/codegangsta/cli/command.go:127 +0x1055
github.com/codegangsta/cli.(*App).Run(0xc8200ba300, 0xc82000a200, 0x2, 0x2, 0x0, 0x0)
	/private/tmp/amazon-ecs-cli-20160519-4261-1vszurp/amazon-ecs-cli-0.3.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/codegangsta/cli/app.go:159 +0xc34
main.main()
	/private/tmp/amazon-ecs-cli-20160519-4261-1vszurp/amazon-ecs-cli-0.3.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/main.go:45 +0xa50`

**Comment by w4-sglim** [comment]
I also have the same problem.

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xe0 pc=0xc4f6b]

goroutine 1 [running]:
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.getContainersForTasks(0xb28648, 0xc20800bdd0, 0xc208315260, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/entity.go:195 +0x4db
...

There are two cases that I found to reproduce this.

Precondition: A program in docker needs memory almost the memory limitation in runtime.
1. Run 'ecs-cli compose ps' just after 'ecs-cli compose up' (Almost everytime)
2. Run 'ecs-cli compose ps' after running process consuming enough memory (Not sure..?)

**Comment by w4-sglim** [comment]
I solved the problem to change instance and memory limitation from docker compose. Lack of memory may cause the memory corruption.

**Comment by klindklind** [comment]
I get this problem every time I'm trying execute ```docker ps``` using assumed profile. But when I use my default AWS account there is no problem.

For instance configure ecs-cli to use some non-existing cluster and run ```ecs-cli ps```. If you're not using cross-account profile you'll get valid error message complaining about missing cluster:

`$ ecs-cli ps`
`ERRO[0000] Error executing 'ps Cluster 'not-existing-cluster' is not active. Ensure that it exists `

But if you use profile like my "cross-account-ecs-admin" profile defined in ~/.aws/config:
`[default]`
`output = json`
`region = eu-west-1`

`[profile cross-account-ecs-admin]`
`role_arn = arn:aws:iam::xxxxxxxxx:role/ECSAdmin`
`source_profile = default`

You'll end up with that `panic: runtime error: invalid memory address or nil pointer dereference`
