### ISSUE TITLE
Specify block-level storage volume size (EBS volume size)

### ISSUE THREAD

**Issue by bee-keeper** [aws/amazon-ecs-cli#554]
Hello,

I can't see that this is currently possible - is there any interest in providing support for this use case?

**Comment by JasonChinsen** [comment]
Yes this would be a great feature to have, esp seeing that you can update the EBS size in the web gui

**Comment by bee-keeper** [comment]
I'm going to close because I think if you need this level of configuration it's easier to just replace ecs-cli with Terraform/Cloudformation and set things up exactly as you want anyway.

**Comment by JasonChinsen** [comment]
This is required if you are spinning up the windows nodes. The default 50gig is not enough esp if a docker image size is anywhere between 5gig to 19gig
