### ISSUE TITLE
EC2 Container Registry Support

### ISSUE THREAD

**Issue by sentientmonkey** [aws/amazon-ecs-cli#56]
Currently, the AMI in the ecs-cli is 2015.03.b, which is the ECS Agent 1.1.0
https://github.com/aws/amazon-ecs-cli/blob/cff682c389b5d863a44f8e38972fd039f4517f9b/ecs-cli/modules/config/ami/ami.go#L29

ECR requires that the ECS Agent 1.7.0 or greater, so we should update for the latest AMI of 2015.03.g.
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container_agent_versions.html

Upgrading this will allow ECR images to be used with clusters created by the ecs-cli.

**Comment by samuelkarp** [comment]
Correction: currently 2015.09.b, should update to 2015.09.c.

**Comment by skion** [comment]
I updated the ID's, but there are also [two new regions](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html). Can add those too of course if it is safe to do so...
