### ISSUE TITLE
In Cluster  does not appear ec2 instances

### ISSUE THREAD

**Issue by hendrixroa** [aws/amazon-ecs-cli#596]
### Summary
I had created a cluster with ecs-cli with this cmd: 

`ecs-cli up --cluster mycluster --vpc vpc-123456 --instance-role myrole --subnets mysubnet1,mysubnet2,mysubnet3 --security-group mysecuritygroup --instance-type m5.xlarge --launch-type EC2 --region us-east-2 --aws-profile myprofile --size 3 --no-associate-public-ip-address`

### Description
The instances are created on aws ec2, but on the cluster, dashboard appear 0 instances.

The version is ecs-cli version 1.7.0 (61f83b2e)

**Comment by SoManyHs** [comment]
Hi @hendrixroa,

Could you please provide the output of running your `ecs-cli up` command? Also, are you able to verify in that there was a  Cloudformation stack created for that cluster? It should be named `amazon-ecs-cli-setup-mycluster`. Thanks!

**Comment by hendrixroa** [comment]
Hi, thanks for the answer, it was a malformed configuration from security groups, i was fixing inbound and outbound rules and fix it.
