### ISSUE TITLE
CreateService and UpdateService Error

### ISSUE THREAD

**Issue by haruharuharuby** [aws/amazon-ecs-cli#616]
### Summary
ecs-cli compose service up and down can not execute. CreateService and UpdateService which function called in the ecs-cli compose service up and down can not execute.
### Config files
* docker-compose.yml
```
version: '3'
services:
  xxxxxxx:
    image: xxxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/xxxxx/xxxxxxx:prod
    ports:
      - "80:80"
    env_file:
      - xxxxx.docker-compose.env
    logging:
      driver: awslogs
      options:
        awslogs-group: xxxxxx/prod
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: xxxxxxx
```

* ecs-params.yml
```
version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 8GB
    cpu_limit: 4096
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-xxxxx"
        - "subnet-yyyyy"
      security_groups:
        - sg-xxxxxxx
      assign_public_ip: ENABLED
```

* ~/.ecs/config
```
version: v1
default: default
clusters:
  default:
    cluster: --region
    region: us-east-1
    default_launch_type: ""
  aaaaaaaa:
    cluster: aaaaaaaaa
    region: ap-northeast-1
    default_launch_type: FARGATE
  bbbbbbbb:
    cluster: bbbbbbbb
    region: ap-northeast-1
    default_launch_type: FARGATE
```

### Expected Behavior
compose service up and down can execute correctly.

### Observed Behavior

```
+ ecs-cli compose --file xxxx.yml --ecs-params ./deploy/xxxx/ecs-params.prod.yml --project-name xxxxx service up --create-log-groups --cluster-config bbbbbbbb --target-group-arn arn:aws:elasticloadbalancing:ap-northeast-1:xxxxxxxx:targetgroup/xxxxxx/xxxxxx --container-name xxxxxx --container-port 80
INFO[0007] Using ECS task definition                     TaskDefinition="xxxxxx:67"
:
ERRO[0009] Error creating service                        error="InvalidParameterException: At least one of maximumPercent or minimumHealthyPercent must be present in DeploymentConfiguration\n\tstatus code: 400, request id: ca38061b-c435-11e8-8a57-c755ef8c4133" service=xxxxxx
INFO[0009] Created an ECS service                        service=xxxxxxx taskDefinition="xxxxxx:67"
FATA[0009] InvalidParameterException: At least one of maximumPercent or minimumHealthyPercent must be present in DeploymentConfiguration
	status code: 400, request id: ca38061b-c435-11e8-8a57-c755ef8c4133
```

```
+ ecs-cli compose --file xxxx.yml --ecs-params ./deploy/xxxx/ecs-params.prod.yml --project-name xxxxx service down --cluster-config bbbbbbbb
ERRO[0001] Error updating service                        error="InvalidParameterException: At least one of maximumPercent or minimumHealthyPercent must be present in DeploymentConfiguration\n\tstatus code: 400, request id: 31a60829-c437-11e8-ae17-a1ba3358ffc0" service=xxxxx
FATA[0001] InvalidParameterException: At least one of maximumPercent or minimumHealthyPercent must be present in DeploymentConfiguration
	status code: 400, request id: 31a60829-c437-11e8-ae17-a1ba3358ffc0
```

**Comment by logemann** [comment]
same here...

**Comment by gabro** [comment]
Same here, I've worked around this by manually specifying the values, which used to be optional and defaulted to 100 and 0 respectively:

```diff
ecs-cli compose service up \
+  --deployment-max-percent 100 \
+  --deployment-min-healthy-percent 0
```

**Comment by haruharuharuby** [comment]
@gabro Yes, if only the compose service up, that is ok. but the compose service down also has the same problem. and the down cannot specify these options. I think it is better to add options to the down command or completion of these options.

I choose the completion way because I think it is more useful.

That's why I put this PR.

**Comment by calebickler** [comment]
This just popped up for us today, it was running fine on our staging cluster yesterday, now live is not working

**Comment by sbarber51** [comment]
Same issue for us. If `ecs-cli compose down` doesn't work then we have major problems automating our workflow

**Comment by sbarber51** [comment]
Does anybody know the last version of ecs-cli to not include this change? We might be able to pull down a specific version as a temporary work around

**Comment by pr1ntr** [comment]
We are also experiencing this issue with our pipeline.  Would like to know if I can version lock to avoid this.

**Comment by sbarber51** [comment]
I'm locked to version 1.7.0 now (which is from July) and still seeing the issue. This makes me think that the issue might be caused by something other than changes to ECS-CLI

**Comment by logemann** [comment]
i have not upgraded my ECS-CLI and have the error anyway. I assume this is a backend thing.

**Comment by haruharuharuby** [comment]
In this problem, AWS Web API seems to return the error, I think the behavior of API is changed.

https://github.com/aws/amazon-ecs-cli/blob/master/ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ecs/api.go#L258

**Comment by KalvinHom** [comment]
Just ran into this issue as well, and we haven't changed any configs, etc.

**Comment by NikitaGl** [comment]
`ecs-cli compose service scale` affected as well, I'm started to receive errors just today. For some mysterious way,` service up` works normally as usual.

**Comment by haruharuharuby** [comment]
@NikitaGl What is your version of ECS-CLI ? latest?

**Comment by fogfish** [comment]
Observing same issue with `1.7.0` and `0.6.6`.

**Comment by cyrill62** [comment]
Same thing with `1.8.0`

It affects `compose service stop` which doesn't accept the `--deployment-....` options.

But a workaround is to use `scale 0 --deployment-max-percent 200` to `stop`.

**Comment by kaihendry** [comment]
This broke our "continuous deployment" (CD) today. :(
Mistakenly filed earlier as https://github.com/aws/amazon-ecs-cli/issues/624

Thank you https://github.com/aws/amazon-ecs-cli/issues/616#issuecomment-426320964 

This is how our ECS CD works via [TravisCI](https://github.com/unee-t/frontend/blob/master/.travis.yml) if anyone would like to _please_ trade notes:
https://github.com/unee-t/frontend/blob/master/deploy.sh

**Comment by haruharuharuby** [comment]
stop and scale seem to have the same problem.

- compose service stop calls UpdateService.

https://github.com/aws/amazon-ecs-cli/blob/33b5630f46b582752332d1a166ff82b9375404e5/ecs-cli/modules/cli/compose/entity/service/service.go#L317

- compose service scale also calls UpdateService.

https://github.com/aws/amazon-ecs-cli/blob/33b5630f46b582752332d1a166ff82b9375404e5/ecs-cli/modules/cli/compose/entity/service/service.go#L311

**Comment by nijine** [comment]
`service rm` appears to work in place of `service down`, which is odd considering they're both aliases for the same command.

**Comment by chrisprzybysoul** [comment]
> Same here, I've worked around this by manually specifying the values, which used to be optional and defaulted to 100 and 0 respectively:
> 
> ```diff
> ecs-cli compose service up \
> +  --deployment-max-percent 100 \
> +  --deployment-min-healthy-percent 0
> ```

It's important to note here that these defaults will cause your service to go down briefly.  The actual defaults, which prevent unexpected downtime, are these:
```
 +  --deployment-max-percent 200 \
 +  --deployment-min-healthy-percent 100
```

**Comment by allisaurus** [comment]
Hi all. We have identified an issue where calls to CreateService and UpdateService fail when passing an empty DeploymentConfig object in the API call. Calls without a DeploymentConfig parameter or with its fields filled are not impacted. We are working to resolve the issue.

**Comment by allisaurus** [comment]
Update: This issue has been resolved and the service is operating normally.

If you continue to experience issues with the ecs-cli, please let us know!

**Comment by haruharuharuby** [comment]
it looks executing command correctly.
(ecs-cii compose service up and down)

**Comment by allisaurus** [comment]
Thanks @haruharuharuby ! That's what we want to hear.
