### ISSUE TITLE
Running latest ecs-cli fails with "ERRO[0000] Error executing 'up': ParameterValue and UsePreviousValue not set for parameter key 'EcsCluster'"

### ISSUE THREAD

**Issue by ryanwalls** [aws/amazon-ecs-cli#63]
Run this:
```
ecs-cli up --keypair my-key-pair --capability-iam --size 2 --instance-type t2.medium
```
and I get this:
```
ERRO[0000] Error executing 'up': ParameterValue and UsePreviousValue not set for parameter key 'EcsCluster'
```

**Comment by uttarasridhar** [comment]
You will need to configure the cluster using the command : ecs-cli configure --cluster <name> before you execute any other commands (ecs-cli up, down, compose, ...)
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_Configuration.html

**Comment by ryanwalls** [comment]
Thanks.  Might want to add that as Step 1 in your tutorial. Or make a note of it.  http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_tutorial.html

If the docs are on github, let me know the repo and I'll create a PR for the updated documentation.

**Comment by lodotek** [comment]
I agree, this threw me off as well...

**Comment by martinrehfeld** [comment]
+1 ;-)

**Comment by jyaworski** [comment]
I just ran into this. It's been five months since this was reported.

**Comment by denis-yuen** [comment]
:+1:

**Comment by benhtn** [comment]
Also missing from http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli.html
