### ISSUE TITLE
Certain instance types not supported

### ISSUE THREAD

**Issue by dtest** [aws/amazon-ecs-cli#64]
Using ecs-cli to setup a cluster, I get an error for unsupported instance type for 'm4.xlarge' or 'm4.2xlarge':

```bash
$ ecs-cli --version
ecs-cli version 0.1.0 (*UNKNOWN)
$ ecs-cli up   --keypair *snip*   --capability-iam   --size 1   --vpc *snip*  --subnets *snip*  --azs us-east-1a   --instance-type m4.xlarge
INFO[0000] Created cluster                               cluster=opsviz-dev
ERRO[0000] Error executing 'up': ValidationError: Parameter EcsInstanceType failed to satisfy constraint: must be a valid EC2 instance type.
	status code: 400, request id: a90c31b7-badf-11e5-a984-97970441ee29
```

While I couldn't find what ImageID the cloudformation template uses, according to the documentation on setting up an ECS instance, ECS would use the following ami for us-east-1 region: ami-2b3b6041 (http://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html)

If I use that AMI to create the instance itself, it indicates support for the m4.* instance classes. 

c4.2xlarge works fine via ecs-cli

Are various instance types not supported? If so, is this documented somewhere?

Also, sidenote: Is the ECS cloudformation template available somewhere?

**Comment by dtest** [comment]
Actually, I found the cloudformation template. It's defining these supported instance types:

```bash
"EcsInstanceType": {
      "Type": "String",
      "Description": "ECS EC2 instance type",
      "Default": "t2.micro",
      "AllowedValues": [
        "t2.micro",
        "t2.small",
        "t2.medium",
        "t2.large",
        "m3.medium",
        "m3.large",
        "m3.xlarge",
        "m3.2xlarge",
        "c4.large",
        "c4.xlarge",
        "c4.2xlarge",
        "c4.4xlarge",
        "c4.8xlarge",
        "c3.large",
        "c3.xlarge",
        "c3.2xlarge",
        "c3.4xlarge",
        "c3.8xlarge",
        "r3.large",
        "r3.xlarge",
        "r3.2xlarge",
        "r3.4xlarge",
        "r3.8xlarge",
        "i2.xlarge",
        "i2.2xlarge",
        "i2.4xlarge",
        "i2.8xlarge"
      ]
```

Any particular reason m4.* is not supported?

**Comment by samuelkarp** [comment]
@dtest There is no specific reason why m4.* is not supported; I think we just missed including it in the list.

**Comment by uttarasridhar** [comment]
was merged in commit dfca89670cc1a86c8e2367fbef2c054ac2b484b5. Pending Release.

**Comment by uttarasridhar** [comment]
released in [v0.2.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v0.2.0)

**Comment by tausif-citrusPay** [comment]
t2.xlarge, t2.2xlarge are also missing from the template.

**Comment by ronaldpetty** [comment]
```
user@ubuntu:~$ aws emr create-cluster --release-label emr-5.9.0 --instance-type t2.small --instance-count 1 --use-default-roles

An error occurred (ValidationException) when calling the RunJobFlow operation: Instance type 't2.small' is not supported.
user@ubuntu:~$
```

**Comment by Martin-Vana** [comment]
The same goes for i3.* instances. Could those be added too?

**Comment by ronaldpetty** [comment]
For me, I found that the instances are in the list, but it failed due to the VPC not supporting those instance types.  If you do a list, you will see the error (in my case.)
