### ISSUE TITLE
Support pulling secrets from parameter store

### ISSUE THREAD

**Issue by mrcasablr** [aws/amazon-ecs-cli#664]
### Summary
Support parameter store secrets - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html

### Description
AWS ECS now (Nov 15, 2018) announced support for pulling secrets from parameter-store at runtime. This helps with security immensely. https://aws.amazon.com/about-aws/whats-new/2018/11/aws-launches-secrets-support-for-amazon-elastic-container-servic/

**Comment by PettitWesley** [comment]
@mrcasablr we just merged a PR for this! #663

**Comment by the0ffh** [comment]
Is CloudFormation supported?

**Comment by PettitWesley** [comment]
@the0ffh I do not think it is yet.

**Comment by the0ffh** [comment]
@PettitWesley Thanks for a quick reply. Do you happen to know when could it be expected?

**Comment by SoManyHs** [comment]
Now available in v.1.11.0! 🎉
