### ISSUE TITLE
Tagging resources

### ISSUE THREAD

**Issue by omerlh** [aws/amazon-ecs-cli#670]
### Summary
When creating resources (cluster, ec2 instances etc) I want to be able to tag them. This is not available using `ecs-cli`, only via regular AWC CLI commands. See this [documantaion](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-using-tags.html).
### Description
* Which specific command was run? `ecs-cli up --capability-iam --size 2 --launch-type EC2`
* Which version of the CLI you are using? `1.12.0 (049e13d)`
* Which version of Go are you using? `go: command not found`
* What platform are you using to run ECS CLI commands? MacOSX

**Comment by rroller** [comment]
Thanks, any update on this? Just had to implement a work around and looking forward to removing it :)

**Comment by PettitWesley** [comment]
@rroller @omerlh We're currently working on this! See pull requests #709, #710, #714, #718, and #724. I don't have an exact release date for you, but expect to see tagging available in an ECS CLI release fairly soon.

Tagging in `ecs-cli up` has been merged into our `dev` branch; so if you want to start using it now, you can build the code in that branch and use it.

**Comment by jdhom** [comment]
@PettitWesley that's great news. We use tags for billing and this will really help, especially in the case of Fargate.

**Comment by allisaurus** [comment]
Hi all, we released support for this in [1.13.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v1.13.0) !

**Comment by rroller** [comment]
I just tested the tags support. Works great. I just deleted so much code :-) you guys are the best.

**Comment by rroller** [comment]
I'm sorry to report, but my previous comment about this working seems to not be true, there appears to be a bug in this. When I use tags with the `ecs-cli up`, I never get any container instances. I see no errors. If I remove ONLY the tags option and run the command again, I get container instances. 

I'm passing the argument like this: `--tags "cost_resource_group=somevaluehere"`
