### ISSUE TITLE
[Question] Storing Secrets via ECS Fargate?

### ISSUE THREAD

**Issue by araphiel** [aws/amazon-ecs-cli#686]
### Summary

I'm looking to store secrets in:

- ecs-params.yml (subnets, security groups, etc)
- docker-compose.yml (env variables)

What is the defacto way to safely store secrets using **ECS Fargate**?

**Comment by rebyn** [comment]
The just-released, officially-endorsed way would be `AWS Systems Manager Parameter Store`. You can find the announcement and links to relevant docos here: https://aws.amazon.com/about-aws/whats-new/2018/12/aws-fargate-platform-version-1-3-adds-secrets-support/.

**Comment by allisaurus** [comment]
@rebyn that's correct! One additional note for use with the ecs-cli is that we always use the `LATEST` platform version for Fargate, and this new platform version will be rolling out as acting `LATEST` through the end of the week. You can find more detail in that article you linked :) 

@araphiel the ecs-cli currently supports use of ECS Secrets via the [ecs-params.yml](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-ecsparams.html) (see `secrets` under `services`)

**Comment by araphiel** [comment]
The timing on this news is amazing!

Thank you @allisaurus @rebyn

**Comment by kueben** [comment]
Hi, I am attempting to use ecs-params.yml secrets on for fargate via ecs-cli. I run into the error: `The specified platform does not satisfy the task definition’s required capabilities.` as people are saying here https://github.com/aws/amazon-ecs-agent/issues/1209. 

@allisaurus @rebyn @araphiel  Do you have experience with this working? 

I am running the following ecs-cli command: 
`compose --cluster $ECS_CLUSTER --file docker-compose.staging.yml service up --launch-type FARGATE --timeout 15`

Here is my ECS params for reference:
```version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 0.5GB
    cpu_limit: 256
  services:
    node:
      secrets:
        - value_from: ${SECRETS_ARN_JWT}
          name: "JWT_TOKEN"
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - ${ECS_CLUSTER_SUBNET_1}
        - ${ECS_CLUSTER_SUBNET_1}
      security_groups:
        - ${ECS_CLUSTER_SECURITY_GROUP}
      assign_public_ip: ENABLED
```
