### ISSUE TITLE
Supported Compose versions?

### ISSUE THREAD

**Issue by LordMike** [aws/amazon-ecs-cli#689]
### Summary
The Readme page says that versions 1, 2 and 3 are supported, but when trying to work with a compose file at version `3.4`, I get this: 

```
ERRO[0000] Unable to open ECS Compose Project            error="Unsupported Docker Compose version found: 3.4"
FATA[0000] Unable to create and read ECS Compose Project  error="Unsupported Docker Compose version found: 3.4"
```

Would it be possible to specify the exact versions of `3` that are supported? The range goes all the way from `3.0` through `3.8` currently.

### Description

* Which specific command was run?
```
ecs-cli compose create
```

* Which version of the CLI you are using? (Run: `ecs-cli --version`)
```
$ ecs-cli --version
ecs-cli version 1.12.1 (e70f1b1)
```

* Which version of Go are you using? `N/A`
* What platform are you using to run ECS CLI commands? `Windows w/ Linux Bash (WSL)`

### Config files

* docker-compose.yml
`N/A`

* ecs-params.yml
`N/A`

* ~/.ecs/config
`N/A`

EDIT: Through testing, I've found that `3.0` is allowed, but `3.1` isn't. I assume this is the case for everything above `3.1` as well, so the docs should say that only version `3.0` is supported.

**Comment by allisaurus** [comment]
Thanks @LordMike - we can add clarification in the docs so "version 3" support is less ambiguous. 

Re: minor versions of 3, you mention trying `3.4` - are there specific features of `3.4` that you'd like to use but currently can't?

**Comment by LordMike** [comment]
Yea, I initially wanted to use Yaml features like Anchors - but we're headed a slightly different route now, since we found that to scale individual services in a compose file, each service there would need to be a service in ECS. I could only make `ecs-cli` create a single task definition with all tasks in it - hence no individual scaling.

**Comment by allisaurus** [comment]
Link to compose version & field support info added in [1.14.0](https://github.com/aws/amazon-ecs-cli/commit/9b22001781551dc07e13c2c53e95d24221d3937c)

**Comment by blocka** [comment]
I came across this because I wanted to use multistage builds using the target option, which requires 3.4

**Comment by allisaurus** [comment]
Hi @blocka - thanks for letting us know! This issue was specifically for documentation gaps, but if support for 3.4 (and/or other minor versions of compose 3) is something you'd like to see in the ecs-cli, I encourage you to cut us a [new issue](https://github.com/aws/amazon-ecs-cli/issues/new) with some more info about your use case so we can track & address it separately.
