### ISSUE TITLE
I am trying to create logs but i get error

### ISSUE THREAD

**Issue by roysG** [aws/amazon-ecs-cli#690]
I type the command: "ecs-cli logs"

I get in response:
INFO[0002] Using ECS task definition                     TaskDefinition="some-taskk:1"
INFO[0002] Created an ECS service                        service=some-taskk taskDefinition="some-taskk:1"
INFO[0002] Updated ECS service successfully              desiredCount=1 force-deployment=false service=some-taskk
INFO[0018] (service some-taskk) has started 1 tasks: (task 2a2b287b222f4945bceca9dbf8c169bb).  timestamp="2019-01-02 15:45:15 +0000 UTC"
INFO[0050] (service some-taskk) has started 1 tasks: (task 4d44a8bebf7f42e7a539418a056de491).  timestamp="2019-01-02 15:45:55 +0000 UTC"
INFO[0086] (service some-taskk) has started 1 tasks: (task c9f0675e86c14f828c0f6092c59f55f2).  timestamp="2019-01-02 15:46:36 +0000 UT

then i stopped it and typed the command:
ecs-cli logs --task-id 2a2b287b222f4945bceca9dbf8c169bb

i get:
error executing 'logs': ResourceNotFoundException: The specified log group does not exist.
	status code: 400, request id: a36ec8ad-0ea5-11e9-a5d7-3b0b786cce71

System INFO:
ecs-cli version 1.12.1 (*UNKNOWN)
go version go1.9.3 darwin/amd64
macOSX

**Comment by PettitWesley** [comment]
@roysG I'm not certain, but I believe the cause of your issue is that the CloudWatch Log Groups for your ECS Service have not been created.

When you launch a service with ecs-cli, you can use `--create-log-groups`:

`ecs-cli compose service up --create-log-groups`

If that doesn't fix it, let me know.

**Comment by roysG** [comment]
It is working :)
And it should be documented, thanks.

**Comment by roysG** [comment]
May i transfer dynamic parameters to ecs-cli command?

**Comment by PettitWesley** [comment]
@roysG you might be able to use environment variables in your shell for that.

For example, in your compose file, as shown [here](https://docs.docker.com/compose/environment-variables/), you can have:

```
web:
  image: "webapp:${TAG}"
```

And then you could run the ecs-cli and specify an env var in the shell:

```
TAG="latest" ecs-cli compose service up
```

**Comment by roysG** [comment]
Thanks.
