### ISSUE TITLE
Builds are always marked as 'dirty' in version output

### ISSUE THREAD

**Issue by euank** [aws/amazon-ecs-cli#7]
A dirty build is denoted by a `*` by the hash in the `--version` output. The version generation code has the assumption that `ECS_RELEASE` will be set to create a clean build, but the build code doesn't fulfill that assumption.
A new release target could/should be added that does a fresh clone in a container and sets that flag, or the version-gen logic should be revisited.

This issue is cosmetic only; it affects version `v0.1.0`.

**Comment by samuelkarp** [comment]
Fixed a very long time ago, in https://github.com/aws/amazon-ecs-cli/pull/39.
