### ISSUE TITLE
Support tty in docker compose (pseudoTerminal)

### ISSUE THREAD

**Issue by SoManyHs** [aws/amazon-ecs-cli#705]
### Summary
ECS supports a field called `pseudo_terminal` on a container definition that maps to the `tty` field in docker compose:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_pseudoterminal

This is a field supported in docker-compose v 1, 2 and 3, and is included in both libcompose and docker/cli.

**Comment by allisaurus** [comment]
We released support for this in [1.13.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v1.13.0) !
