### ISSUE TITLE
Support passing all config parameters at run time

### ISSUE THREAD

**Issue by christianblunden** [aws/amazon-ecs-cli#71]
For shared build environments such as jenkins/bamboo, the ecs-cli config file should be optional, and all configuration parameters should be able to be passed at run time.  This could be via arguments or environment variables

examples:

```
ecs-cli --cluster my-cluster --region eu-west-1 compose up
```

or

```
CLUSTER=my-cluster REGION=eu-west-1 ecs-cli compose up
```

**Comment by supertong** [comment]
+1

**Comment by eudaimos** [comment]
+1

**Comment by yinshiua** [comment]
Related to https://github.com/aws/amazon-ecs-cli/issues/174

**Comment by yinshiua** [comment]
Added proposals to support multiple clusters configuration. Please give us some feedback. Thanks! https://github.com/aws/amazon-ecs-cli/issues/253

**Comment by yinshiua** [comment]
You can now pass `--region` and `--cluster` flags at run time. Other configuration related issues will be tracked in #253.
