### ISSUE TITLE
Is it possible to use initProcessEnabled option with ecs-params.yml or docker-compose.yml?

### ISSUE THREAD

**Issue by odyss009** [aws/amazon-ecs-cli#716]
### Summary
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_security
As above document, there is Init flags in Container Task Definitions.
But, I can't use init flag option with docker-compose.yml(for v3.7 schema) or ecs-params.yml.
Is it possible to use it? Or is there any plan to support it?
(https://aws.amazon.com/about-aws/whats-new/2017/11/amazon-ecs-adds-support-for-docker-device-and-init-flags-in-container-task-definitions/)

**Comment by allisaurus** [comment]
Hi @odyss009 - This option isn't currently supported by the ecs-cli, but we can take it as a feature request. No current word on when support would be added but we will update this issue when we have news. Can you give us a brief description of your use case? Thanks for letting us know!

**Comment by odyss009** [comment]
This is for supporting graceful shutdown of docker container.
Thanks.

**Comment by mhumeSF** [comment]
I worked this out in #741 if someone could review

**Comment by SoManyHs** [comment]
This was released today in v1.14.0! :rocket:
