### ISSUE TITLE
Support for services which use GPU

### ISSUE THREAD

**Issue by samjgalbraith** [aws/amazon-ecs-cli#729]
### Summary
Support for services which use GPU

### Description
Our team has been using a wrapper script around the ECS CLI compose up command to build, push and deploy changes to our services. We have almost finished building a service which uses GPU at request time to provide machine learning predictions. The new ECS GPU optimized AMI requires that the GPU field in the ECS task definition is provided with a required GPU count. Currently, the ECS cli provides no way to provide this value to be used in the creation of the task definition, and so our GPU based service will not work without circumventing the ECS CLI.

**Comment by SantiMunoz** [comment]
Same problem here, we can't deploy a service that uses GPU. Willing to see this deployed :top:

**Comment by SoManyHs** [comment]
This was released in 1.14.0!
