### ISSUE TITLE
InvalidParameterException: Long arn format must be enabled for ECS managed tags

### ISSUE THREAD

**Issue by gauravve** [aws/amazon-ecs-cli#735]
### Summary
```ecs-cli compose up``` not working with ```InvalidParameterException: Long arn format must be enabled for ECS managed tags``` Error

### Description

* Which specific command was run? (Example: `ecs-cli up --capability-iam --size 2 --launch-type EC2`)
```ecs-cli compose up --cluster grv-cluster-1 --disable-ecs-managed-tags --tags "ApplicationID=0070,StackOwner=Gaurav"```

* Which version of the CLI you are using? (Run: `ecs-cli --version`)
1.12
* Which version of Go are you using? (Run: `go version`)
1.11
* What platform are you using to run ECS CLI commands? (E.g. Linux, MacOSX, Windows)
MacOSX

### Config files

* docker-compose.yml
```
version: "3.0"
services:
  web:
    image: 648515672437.dkr.ecr.ap-southeast-2.amazonaws.com/metalinter
    ports:
      - "3000:3000"
```

* ecs-params.yml
Not using it

* ~/.ecs/config
```
version: v1
default: grv_config
clusters:
  default:
    cluster: grv-cluster-1
    region: ap-southeast-2
    default_launch_type: ""
```

### Expected Behavior
Command runs successfully

### Observed Behavior
```
INFO[0001] Using ECS task definition                     TaskDefinition="emailService:2"
ERRO[0001] Error running tasks                           error="InvalidParameterException: Long arn format must be enabled for tagging.\n\tstatus code: 400, request id: 53cb26de-3dad-11e9-9752-5b75ee9e05b4" task definition=0xc0005e7130
FATA[0001] InvalidParameterException: Long arn format must be enabled for tagging.
	status code: 400, request id: 53cb26de-3dad-11e9-9752-5b75ee9e05b4
```

**Comment by PettitWesley** [comment]
@gauravve I'm aware of this bug in the unreleased `tagging` branch. It should be fixed in #731, which I just merged.

If you pull the `tagging` branch, build it, and test again, it should work now.

Also, while I can't give a specific date, I can say that we plan on releasing this functionality fairly soon.

Let us know if you find any more bugs or usability issues with tagging!
