### ISSUE TITLE
EC2 instance not getting created, through the CLI

### ISSUE THREAD

**Issue by mayordwells** [aws/amazon-ecs-cli#742]
### Summary

I'm trying to create an EC2 through the CLI but it is not working. 
AWS and ECS credentials and config are both the default with the correct credentials. Cloudformation successfully created but EC2 is not created, any idea why?
<img width="1104" alt="screen shot 2019-03-08 at 7 46 48 pm" src="https://user-images.githubusercontent.com/1370340/54043532-e65dde00-41dd-11e9-89d5-40b17891f865.png">

### Description

* Which specific command was run? `ecs-cli up --keypair conectar-cluster-pem --capability-iam --size 2 --instance-type t2.medium --region=eu-central-1 --force`

* Which version of the CLI you are using? `ecs-cli version 1.13.0 (2d98b5e)`
* Which version of Go are you using? `go version go1.11.5 darwin/amd64`
* What platform are you using to run ECS CLI commands? MacOSX

### Config files

* ~/.ecs/config
```
version: v1
default: default
clusters:
  default:
    cluster: conectar-cluster
    region: eu-central-1
    default_launch_type: EC2
```

### Expected Behavior
Why exactly are the EC2 instances not getting created? Just 2 weeks ago I ran the same command with another aws profile on my Mac and it worked. I expect to be able to run `aws ecs list-container-instances --cluster conectar-cluster` and then retrieve my EC2 instance details.

### Observed Behavior

Attached in the screenshot above.

**Comment by allisaurus** [comment]
Hi @mayordwells - from your screenshot, it looks like you're not calling `aws ecs describe-clusters` with the name of the cluster you just created ("conectar-cluster"). `describe-clusters` will default to describing the cluster "default" if not provided a list of cluster names. 

Try executing: `aws ecs describe-cluster --clusters conectar-cluster --region eu-central-1`

Or, if you want to list all the clusters in your account, try executing `aws ecs list-clusters --region eu-central-1`

Let us know if the above commands solve your problem. Thanks!

**Comment by mayordwells** [comment]
Thank you very much for your fast reply @allisaurus that worked.
But I had to add to pluralizer cluster `aws ecs describe-cluster --clusters conectar-cluster --region eu-central-1`
Thank you so much!

**Comment by allisaurus** [comment]
Great, glad to hear it!

**Comment by mayordwells** [comment]
Hi, again @allisaurus this is still quite confusing. Why are the EC2 instances not getting created?

<img width="1280" alt="Screen Shot 2019-03-08 at 10 43 36 PM" src="https://user-images.githubusercontent.com/1370340/54051825-c9340a00-41f3-11e9-835f-f73762accfea.png">

**Comment by allisaurus** [comment]
Hi @mayordwells , EC2 instances can take a few minutes to provision depending on what kind of instance you selected. I created a cluster of t2.medium's in eu-central-1 earlier today, and my instances were available in 2-3 minutes. Can you check to see if they're available now, or try again and see if they show up within 5 minutes of CloudFormation succeeding?

You can also check the EC2 console in that region to see whether or not they're there but still in the process of provisioning. Let me know if they still fail to appear.

**Comment by mayordwells** [comment]
@allisaurus - `EC2 instances can take a few minutes to provision`, that's the funny thing, I've waited a few hours for this on multiple occasions, I ran this command `ecs-cli up --keypair conectar-cluster-pem --capability-iam --size 2 --instance-type t2.medium --region eu-central-1 --cluster conectar-cluster --force` it ran successfully but no EC2 instance is created, that's why I'm using the `--force` that's to show that I've been running this command multiple times.

I also checked the EC2 console for the region, nothing is there.

I just woke up now after 7 hours of running the up command successfully, instance still not created.

**Comment by mayordwells** [comment]
Not only that, the UI of ECS is broken, not listing any cluster and loading forever. 

<img width="1146" alt="Screen Shot 2019-03-09 at 9 06 54 AM" src="https://user-images.githubusercontent.com/1370340/54067000-cfa1a080-424a-11e9-9941-41168a38120e.png">

**Comment by SoManyHs** [comment]
Hi @mayordwells,

Sorry to hear you're still having trouble. What happens if you run `ecs-cli down` on that cluster and re-run `ecs-cli up` without the force flag? Also, are you able to check in the AWS console to see if a CloudFormation stack associated with this cluster was created or is in a ROLLBACK state? The stack should be called `amazon-ecs-cli-setup-conectar-cluster`.

**Comment by mayordwells** [comment]
Hi @SoManyHs Cloudformation Stack is successfully created, my only issue is that the ec2 instances are not getting created. 

Here's the screenshot when i run `ecs-cli down`
<img width="774" alt="Screen Shot 2019-03-09 at 10 58 50 AM" src="https://user-images.githubusercontent.com/1370340/54068148-60cc4380-425a-11e9-951e-3e49ff24f3b9.png">

And here's my Cloudformation Console. 
<img width="1156" alt="Screen Shot 2019-03-09 at 10 57 38 AM" src="https://user-images.githubusercontent.com/1370340/54068149-6aee4200-425a-11e9-9633-53224a7d9ae5.png">

Why is the EC2 instance not getting created? Also, I know that I can do this all from the Dashboard, but I've never used it as I find the CLI to do most of the manual job for me much faster.

**Comment by SoManyHs** [comment]
Hm. And you were running the `down` command in the correct region? Also, could you include a copy of your `~/.ecs/config`?

**Comment by mayordwells** [comment]
ECS Config:
<img width="359" alt="Screen Shot 2019-03-09 at 11 22 38 AM" src="https://user-images.githubusercontent.com/1370340/54068422-b0f8d500-425d-11e9-8f67-d34d82352926.png">

**Comment by SoManyHs** [comment]
I'm not sure what the issue is. It appears that your cluster doesn't exist in whatever region you ran the `ecs-cli down` command from. If you look in your cloudformation stack, does it list the resources that were created?

**Comment by mayordwells** [comment]
Hi @SoManyHs 
Thanks for your time and patience, but then again, check this out. 

If it doesn't exist, then why do I get this?

<img width="1279" alt="Screen Shot 2019-03-09 at 11 43 07 AM" src="https://user-images.githubusercontent.com/1370340/54068691-8d835980-4260-11e9-9ae1-494e321ac04f.png">

**Comment by SoManyHs** [comment]
Just to be sure, could you try `ecs-cli down --cluster conectar-cluster --region eu-central-1`?

**Comment by mayordwells** [comment]
@SoManyHs just tried that out now, 
<img width="758" alt="Screen Shot 2019-03-09 at 11 51 14 AM" src="https://user-images.githubusercontent.com/1370340/54068820-beb05980-4261-11e9-985e-af298a46236f.png">

I went to the aws console dashboard to delete the cloudformation stack manually, and only after that was I able to run the creation command without force. Check screenshots below. 

<img width="1255" alt="Screen Shot 2019-03-09 at 11 57 58 AM" src="https://user-images.githubusercontent.com/1370340/54068918-cb817d00-4262-11e9-992f-be125377a936.png">

<img width="1089" alt="Screen Shot 2019-03-09 at 11 58 18 AM" src="https://user-images.githubusercontent.com/1370340/54068927-d805d580-4262-11e9-8aa1-6de34b992bcd.png">

EC2 instance is still not getting created. It's the first time I'm experiencing this.

**Comment by SoManyHs** [comment]
If you click into the CFN stack in your console, can you see if there are EC2 Instances created?

**Comment by mayordwells** [comment]
Looks like it was created, not sure. Can you please take a look at the following screenshots:

![Uploading Screen Shot 2019-03-09 at 12.09.34 PM.png…]()

<img width="1068" alt="Screen Shot 2019-03-09 at 12 10 29 PM" src="https://user-images.githubusercontent.com/1370340/54069108-2ddb7d00-4265-11e9-8c85-e02dcf75a6a7.png">

<img width="1021" alt="Screen Shot 2019-03-09 at 12 12 55 PM" src="https://user-images.githubusercontent.com/1370340/54069111-32a03100-4265-11e9-97a6-78e9823b3a9a.png">

<img width="1022" alt="Screen Shot 2019-03-09 at 12 13 12 PM" src="https://user-images.githubusercontent.com/1370340/54069112-37fd7b80-4265-11e9-82d2-447b6f3d9086.png">

I'm just stuck on this step, I wish I can find a solution ASAP.

**Comment by mayordwells** [comment]
This was due to a limit on my account. I sent a mail to the customer service and finally got my account verified. Thanks.

**Comment by SoManyHs** [comment]
Great, glad to hear it!
