### ISSUE TITLE
Unable to pull docker images using ecs-cli compose

### ISSUE THREAD

**Issue by pved2016** [aws/amazon-ecs-cli#755]
### Summary
Unable to pull docker images using ecs-cli compose

### Description
This is the docker-compose. Trying to pull solr image from Docker-hub and a webapp image from ECR. 

------

version: "3"

services:

 solr:
  image: solr:7.7.1
  ports:
   - "8983:8983"
  volumes:
   - data:/opt/solr/server/solr/mycores
  entrypoint:
   - solr-precreate
   - mycore

 webapp:
  image: xxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/verizontest:latest
  ports:
   - "80:80"
   
volumes:
 data:
------

The xxxxx is the id of the ECR.

ecs-cli version - ecs-cli version 1.13.1 (78c4de9)
platfrom - Linux

### Observed Behavior

When i run ecs-cli compose on my ECS cluster:
ecs-cli compose --verbose --file docker-compose.yml --region us-east-1 --cluster clusterLXM up

- this is what I get -----

DEBU[0000] Parsing the compose yaml...                  
DEBU[0000] Docker Compose version found: 3              
DEBU[0000] Parsing v3 project...                        
DEBU[0000] Parsing the ecs-params yaml...               
DEBU[0000] Parsing the ecs-registry-creds yaml...       
DEBU[0000] Transforming yaml to task definition...      
ERRO[0000] Error listing tasks                           error="AccessDeniedException: User: arn:aws:sts::xxxxxxxxx:assumed-role/ecsInstanceRole/i-0530d1375c75651a3 is not authorized to perform: ecs:ListTasks on resource: *\n\tstatus code: 400, request id: 80bcc076-5183-11e9-9c21-319822da1ddd" request="{\n  Cluster: \"VerizonLXM\",\n  DesiredStatus: \"RUNNING\",\n  Family: \"ec2-user\"\n}"
FATA[0000] AccessDeniedException: User: arn:aws:sts::xxxxxxxxxx:assumed-role/ecsInstanceRole/i-0530d1375c75651a3 is not authorized to perform: ecs:ListTasks on resource: *
	status code: 400, request id: 80bcc076-5183-11e9-9c21-319822da1ddd 

Please let me know if i am missing some IAM settings/ECR settings

**Comment by allisaurus** [comment]
Hi @pved2016 - according to the provided output, it looks like the user executing this command (arn:aws:sts::xxxxxxxxx:assumed-role/ecsInstanceRole/i-0530d1375c75651a3) does not have permission to use the `ecs:ListTasks` API. If possible, can you add this permission to the role's policy and see if it then succeeds?
