### ISSUE TITLE
RequestError: send request failed

### ISSUE THREAD

**Issue by dirn** [aws/amazon-ecs-cli#76]
I'm trying to use `ecs-cli` to manage an ECS cluster and all commands (exception for `configure`) result in errors like

    $ ecs-cli ps
    ERRO[0000] Error executing 'ps RequestError: send request failed
    caused by: Post https://ecs.us-east-1.amazonaws.com/: dial tcp: lookup ecs.us-east-1.amazonaws.com on [::1]:53: read udp [::1]:52017->[::1]:53: read: connection refused

and

    $ ecs-cli compose --project-name [project name here] service up
    ERRO[0000] Error describing service                      error=RequestError: send request failed
    caused by: Post https://ecs.us-east-1.amazonaws.com/: dial tcp: lookup ecs.us-east-1.amazonaws.com on [::1]:53: read udp [::1]:54972->[::1]:53: read: connection refused     service=ecscompose-service-[project name here]
    FATA[0000] RequestError: send request failed
    caused by: Post https://ecs.us-east-1.amazonaws.com/: dial tcp: lookup ecs.us-east-1.amazonaws.com on [::1]:53: read udp [::1]:54972->[::1]:53: read: connection refused

After installing, both through`brew install amazon-ecs-cli` and by downloading the binary from S3, I ran

    $ ecs-cli configure --cluster [cluster name here] --region us-east-1

This worked as expected and everything looks correct in `~/.ecs/config`.

I've tried to use `ecs-cli` on three different machines (all using the same AWS credentials) on two different networks. Everything works as expected on one of the machines but fails on the other two. I tried one of the failing machines on the same network as the successful machine -- the error hints at a networking-related problem -- but still received the errors. I can (usually) ping `ecs.us-east-1.amazonaws.com` from any of the machines.

The successful machine is running version 0.1. The failing machines both started with 0.1, although I upgraded them to 0.2 in the hope that the new version would either resolve my problem or give me better insight.

I'm happy to provide whatever information I can.

Thanks.

**Comment by dirn** [comment]
I'm closing the issue because the problem seemed to go away on its own. I'll happily open it back up if anyone experiences the same thing.

**Comment by Supagoat** [comment]
This problem is happening to me, but not to my coworker (both of us on the same version of MacOS)

**Comment by wicros** [comment]
This problem is happening to me now. Does anyone know the reason?
