### ISSUE TITLE
New task definition created each time

### ISSUE THREAD

**Issue by elhachmi** [aws/amazon-ecs-cli#764]
### Summary
Hi, there is any way to avoid creating new task definition with each esc-cli compose service start/up? If no, why?

**Comment by efekarakus** [comment]
Hi @elhachmi! 

1. `ecs-cli compose service start/up` should only create a new task definition if your compose file changed. Do you observe a different behavior?
2. Why do you not want it to create a new task definition? What would be the ideal behavior for you instead?

**Comment by efekarakus** [comment]
Closing the issue due to lack of response, please feel free to re-open it!
