### ISSUE TITLE
Integration tests for ecs-cli local

### ISSUE THREAD

**Issue by efekarakus** [aws/amazon-ecs-cli#772]
### Summary
Add integration tests for `ecs-cli local`. These tests should follow the steps defined in the Local Container Endpoints blog post: https://aws.amazon.com/blogs/compute/a-guide-to-locally-testing-containers-with-amazon-ecs-local-endpoints-and-docker-compose/

**Comment by bvtujo** [comment]
Closing this after merging in #903 and #914. 
903: Addition of integration tests which actually launch and tear down local containers
914: Expansion of scope of integration tests, validation of docker-compose contents, validation of running containers using Docker SDK.
