### ISSUE TITLE
Service deployment configuration parameters

### ISSUE THREAD

**Issue by skion** [aws/amazon-ecs-cli#80]
Similar to #21, it currently isn't possible to tune the [deployment configuration](http://docs.aws.amazon.com/cli/latest/reference/ecs/create-service.html) via the `maximumPercent` and `minimumHealthyPercent` parameters using `ecs-cli`.

**Comment by uttarasridhar** [comment]
This was added in the commit 5afbc46 and released in [v0.3.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v0.3.0).

You can read the docs [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-service.html) for more information.
