### ISSUE TITLE
Convert top-level Task Def fields into Docker Compose

### ISSUE THREAD

**Issue by SoManyHs** [aws/amazon-ecs-cli#810]
- [x] NetworkMode
- [x] Pid
- [x] Ipc
- [x] TaskRoleArn
- [x] Volumes

**Comment by efekarakus** [comment]
@SoManyHs Are we planning to convert the`TaskRoleArn` field as the [AWS_CONTAINER_CREDENTIALS_RELATIVE_URI](https://github.com/awslabs/amazon-ecs-local-container-endpoints/blob/master/docs/features.md#vend-credentials-to-containers) environment variable?

My concern is this note in the Local Endpoints README: 
> Note: We do not recommend using production credentials or production roles when testing locally.

So I wonder if we should be adding a comment in the Compose file asking them to change the ARN and then uncomment the line.

**Comment by efekarakus** [comment]
Similarly to above, we should set the `ECS_CONTAINER_METADATA_URI` to `http://169.254.170.2/v3`

**Comment by SoManyHs** [comment]
Noting here that for TaskRoleArn, we won't convert this to anything for now but we may handle this when we implement overrides: https://github.com/aws/amazon-ecs-cli/issues/831
