### ISSUE TITLE
Expose docker-compose up errors through ecs-local up

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli#817]
When I run ecs-cli local up, it doesn't expose the error (Just Failed to run docker-compose up due to exit status 1)

Here are the two commands outputs:

➜  ECSLocalBugBash ecs-cli-exp local up
Successfully wrote docker-compose.local.yml
INFO[0001] The network ecs-local-network already exists
INFO[0001] The amazon-ecs-local-container-endpoints container already exists with ID d3ee0c0d652b6c54ff3130fb322e31032666dc5d69fa5a69fb5c40d02d9d49f0
INFO[0001] Started container with ID d3ee0c0d652b6c54ff3130fb322e31032666dc5d69fa5a69fb5c40d02d9d49f0
FATA[0002] Failed to run docker-compose up due to exit status 1

➜  ECSLocalBugBash docker-compose up
Recreating dd5028ee042f_ecslocalbugbash_BadLambdaWorker_1 ... error

ERROR: for dd5028ee042f_ecslocalbugbash_BadLambdaWorker_1  Cannot create container for service BadLambdaWorker: unknown log opt 'awslogs-stream-prefix' for awslogs log driver

ERROR: for BadLambdaWorker  Cannot create container for service BadLambdaWorker: unknown log opt 'awslogs-stream-prefix' for awslogs log driver
ERROR: Encountered errors while bringing up the project.

**Comment by iamhopaul123** [comment]
Related to [#816](https://github.com/aws/amazon-ecs-cli/issues/816)

**Comment by iamhopaul123** [comment]
@kohidave nice catch David! Sorry for wrongly closing the issue and thanks for correcting me. Please help me to review this pr.
