### ISSUE TITLE
ecs-cli allow family name to be passed from the command line

### ISSUE THREAD

**Issue by aventurella** [aws/amazon-ecs-cli#82]
I appreciate the autogenerated name, but I would like to be able to explicitly tell it what the family name should be instead of `ecscompose-{{project name}}`

**Comment by uttarasridhar** [comment]
With the [v0.3.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v0.3.0) release, we have made the prefix used by task definitions configurable by supplying **`--compose-project-name-prefix`** to `ecs-cli configure` command. You can find more information in the [docs](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-configure.html).

**Before:**
Format : `ecscompose-{{project name}}`

**v0.3.0+ :**
Format : `{{compose-project-name-prefix}}{{project-name}}`
If you set `--compose-project-name-prefix` to empty, the family name will default to project-name.

Hope that helps your use case.
