### ISSUE TITLE
ecs-cli local: missing region for secret

### ISSUE THREAD

**Issue by clareliguori** [aws/amazon-ecs-cli#822]
Did:
```
$ ~/Downloads/ecs-cli local up -t clare-bot
```
My default region in ~/.aws/config is us-west-2 (where the clare-bot task def resides)

Got:
```
docker-compose.local.yml file already exists. Do you want to write over this file? [y/N]
y
Successfully wrote docker-compose.local.yml
INFO[0001] The network ecs-local-network already exists 
INFO[0001] The amazon-ecs-local-container-endpoints container already exists with ID d73f93bc0571cca362b9566c49b357479ff635bbccff7f7977f8a2b417409f72 
INFO[0001] Started container with ID d73f93bc0571cca362b9566c49b357479ff635bbccff7f7977f8a2b417409f72 
FATA[0001] Failed to decrypt secret due to Failed to retrieve decrypted secret from clare-bot-github-token due to MissingRegion: could not find region configuration: MissingRegion: could not find region configuration 
```

Task def was retrieved, and docker-compose.local.yml file was created, but secret could not be retrieved.

**Comment by clareliguori** [comment]
My task def was using valueFrom with the name of a Parameter Store parameter.  I switched to using an ARN to workaround this issue.

**Comment by efekarakus** [comment]
okay, I can reproduce the issue by setting `$AWS_REGION=""` (mine was set to `us-east-1`):

```shell
$ ecs-cli local up -t EcsLocalBugBash
docker-compose.local.yml file already exists. Do you want to write over this file? [y/N]
y
Successfully wrote docker-compose.local.yml
INFO[0001] The network ecs-local-network already exists 
INFO[0001] The amazon-ecs-local-container-endpoints container already exists with ID 1e2aa4637e072ce27c6bae4d97b0205e0cda4656699a33de9d7ece8e296d5561 
INFO[0001] Started container with ID 1e2aa4637e072ce27c6bae4d97b0205e0cda4656699a33de9d7ece8e296d5561 
Region is: 
FATA[0001] Failed to decrypt secret due to Failed to retrieve decrypted secret from TEST_PDX_DB_PASSWORD due to MissingRegion: could not find region configuration: MissingRegion: could not find region configuration 
```

**Comment by efekarakus** [comment]
From the docs:

>  By default the SDK will only load the shared credentials file's (~/.aws/credentials) credentials values, and all other config is provided by the environment variables, SDK defaults, and user provided aws.Config values.
>
> If the AWS_SDK_LOAD_CONFIG environment variable is set, or SharedConfigEnable option is used to create the Session the full shared config values will be loaded. This includes credentials, region, and support for assume role. In addition the Session will load its configuration from both the shared config file (~/.aws/config) and shared credentials file (~/.aws/credentials). Both files have the same format. 

https://docs.aws.amazon.com/sdk-for-go/api/aws/session/#hdr-Create_Session_With_Option_Overrides

I fixed the issue in https://github.com/aws/amazon-ecs-cli/pull/836, instead of using `session.NewSession()` which doesn't look at `~/.aws/config` we are now using our internal region resolution function.

**Comment by clareliguori** [comment]
Confirmed fixed during bug bash
