### ISSUE TITLE
ecs-cli local create --task-def does not work with aws-cn partition

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli#826]
When I try to convert a task def in aws-cn, I get an UnrecognizedClientException

➜  ECSLocalBugBash ecs-cli local create --task-def arn:aws-cn:ecs:cn-northwest-1:661064361884:task-definition/DavidsRadTask:1
FATA[0000] Error with local create: UnrecognizedClientException: The security token included in the request is invalid.
        status code: 400, request id: 4e67beb5-557e-4ce8-bc8b-ecfd905da8b3

**Comment by SoManyHs** [comment]
@kohidave Were you using this with your AWS creds for the cn partition?

**Comment by kohidave** [comment]
@SoManyHs I was using my AWS CN account. (I went through aws configure wizard and put in my access and secret key for cn-northwest-1).

**Comment by kohidave** [comment]
Ah, looks like it's reading after reading the code a bit more closely, it's looking at the default cluster config and grabbing the region out of that, rather than the AWS config or from the ARN.

**Comment by kohidave** [comment]
This should be fixed by [this merge](https://github.com/aws/amazon-ecs-cli/pull/844). WOot!
