### ISSUE TITLE
Cannot start container: failed to create endpoint on network bridge

### ISSUE THREAD

**Issue by aaronfranco** [aws/amazon-ecs-cli#83]
I'm getting this weird error... Does anyone know what this is related to? I opened ports on my security group, but that didn't help.

```
Cannot start container XXXXXXXXX: failed to create endpoint XXXXXXXXXXX on network bridge: Bind for 0.0.0.0:30 
```

Any help or guidance would be greatly appreciated.

Best,
Aaron

**Comment by yinshiua** [comment]
@aaronfranco Did you get this on the local host or on a container instance in the ECS cluster? If you still have the logs, please provide complete logs so we can debug this.

Thanks,
Jessica

**Comment by aaronfranco** [comment]
I can't remember it's been so long. I gave up on ECS because I couldn't get my containers working. I went with straight EC2 instead. Honestly, I cannot recall this error at all. It is probably irrelevant at this point. Thanks for the reply, but I'll close this for now :)
