### ISSUE TITLE
Compose Version 2 File Format Support

### ISSUE THREAD

**Issue by davemkirk** [aws/amazon-ecs-cli#86]
Compose 1.6 introduces a new format for `docker-compose.yml`. Are there plans to support the new format changes?

More Info: 
https://github.com/docker/compose/releases
https://github.com/docker/compose/blob/release/docs/compose-file.md

**Comment by shezadkhan137** [comment]
+1

**Comment by joshbalfour** [comment]
+1

**Comment by jzimmek** [comment]
+1

**Comment by kangaroozal** [comment]
+1

**Comment by gomex** [comment]
+1

**Comment by breezykermo** [comment]
+1

**Comment by xbtsw** [comment]
+1

**Comment by bertonjulian** [comment]
+1

**Comment by uzquiano** [comment]
+1

**Comment by andresanies** [comment]
+1

**Comment by sporokh** [comment]
+1

**Comment by Y4Rv1K** [comment]
+1

**Comment by bmontalvo** [comment]
+1

**Comment by bjinwright** [comment]
+1

**Comment by oscardiedrichs** [comment]
+1

**Comment by NickStefan** [comment]
+1

**Comment by seefeld** [comment]
+1

**Comment by yetanotherchris** [comment]
+20

**Comment by uttarasridhar** [comment]
With the release of [v0.4.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v0.4.0), we now support `services` option of the compose file format v2.
