### ISSUE TITLE
ecs-cli local: Update "awslogs will not be supported" warning message

### ISSUE THREAD

**Issue by clareliguori** [aws/amazon-ecs-cli#862]
I get this warning when running a task definition using awslogs logging:
```
WARN[0000] awslogs will not be supported
```

"will not be supported" is not a very friendly error message and does not describe what will happen locally instead.  Compare to the network mode info-level message:
```
INFO[0000] Task Definition network mode is ignored when running containers locally. Tasks will be run in the ecs-local-network.  networkMode=awsvpc
```

**Comment by SoManyHs** [comment]
Should this be an INFO level message? @clareliguori

**Comment by SoManyHs** [comment]
Also are we only supporting json-file as a log driver? @efekarakus

**Comment by efekarakus** [comment]
@SoManyHs for now we override every log driver to `json-file`, it looks like for this issue we should be outputting a more user friendly message something like:
```
INFO[0000] Log driver awslogs is ignored locally, overwrite to json-file.
```

**Comment by kohidave** [comment]
I was thinking of copying the networking mode line almost verbatim, with a hint about the override file:

> awslogs log driver is ignored when running locally. Tasks will default to json-file instead. This can be changed in your compose override file.

How does that sound?

**Comment by clareliguori** [comment]
LGTM!

**Comment by kohidave** [comment]
Sweet, all merged in. Thanks for the suggestion 😁
