### ISSUE TITLE
ecs-cli local: never overwrite docker-compose.ecs-local.override.yml

### ISSUE THREAD

**Issue by clareliguori** [aws/amazon-ecs-cli#863]
We expect that docker-compose.ecs-local.override.yml is the file for users to override various settings and save to their version-controlled repo, instead of attempting to make inline changes to the main docker-compose.ecs-local.yml file.  But every time I run `ecs-cli local up`, I get the following prompt:
```
docker-compose.ecs-local.override.yml file already exists. Do you want to write over this file? [y/N]
```

I think we should never overwrite this file, and only create it the first time.

**Comment by clareliguori** [comment]
In fact, if I do make changes to the override file, then I can't run ecs-cli local up anymore:
```
docker-compose.ecs-local.override.yml file already exists. Do you want to write over this file? [y/N]
n
FATA[0087] Failed to create Compose files due to:
aborted writing compose file. To retry, rename or move docker-compose.ecs-local.override.yml 
```

**Comment by efekarakus** [comment]
Do we not expect users to use `ecs-local up` in the same dir with different task definitions? That's the reason why we prompt for the override file

**Comment by clareliguori** [comment]
I think for the override file, we should expect that task defs are in different directories.  The overwrite behavior makes the override file useless for users if they can't actually edit it without copying it to a custom-named file.

**Comment by efekarakus** [comment]
OK sounds good. My only concern then is if the same remote task definition is updated with a new container then the override file will not have the new service.

If we are okay with that, then I'll make the change so that we create the override file only if it's not there already.

**Comment by efekarakus** [comment]
Fixed in https://github.com/aws/amazon-ecs-cli/pull/867
