### ISSUE TITLE
ecs-cli local: Compose build output only output at the end of the build

### ISSUE THREAD

**Issue by clareliguori** [aws/amazon-ecs-cli#864]
If I have the following override:
```
version: "3.2"
services:
  bot:
    build: .
```

When the build occurs during ecs-cli local up, I don't get the build output until the build is completed.  The command appears to hang here until the build is completed:
```
INFO[0002] Using docker-compose.ecs-local.yml, docker-compose.ecs-local.override.yml, docker-compose.custom.override.yml files to start containers 
```

Then when the build is done, I get all the build output at once and the container starts.

This is a very confusing experience to the user, especially if I have a long multi-minute build, but have no idea how the build is progressing.

**Comment by efekarakus** [comment]
Looks like we can achieve this with [exec's StderrPipe](https://golang.org/pkg/os/exec/#Cmd.StderrPipe) and [exec's StdoutPipe](https://golang.org/pkg/os/exec/#Cmd.StdoutPipe).

**Comment by clareliguori** [comment]
Fixed
