### ISSUE TITLE
EC2 Disk Size

### ISSUE THREAD

**Issue by stevesloka** [aws/amazon-ecs-cli#88]
Is there a way to specify the disk size when I create the cluster (e.g. ecs-cli up). Right now they are 8gb which is too small for my app.

**Comment by uttarasridhar** [comment]
Today, `ecs-cli up` supports **`--instance-type`** option that lets you specify the EC2 instance type for your container instances. You can look for more information on the instance types [here](http://aws.amazon.com/ec2/instance-types/) and pick the desired type.

Does that help? Or were you looking to specify the block-level storage volume size (EBS volume size)?

**Comment by stevesloka** [comment]
No I'm looking for the EBS volume size. I think this is the answer: http://stackoverflow.com/questions/19146271/increase-the-root-device-size-in-cloudformation-autoscaling-group

**Comment by mandeepm91** [comment]
Is there any way to change the size of the instance store volume attached to the ECS instance ? And how do we do this from ecs-cli?
