### ISSUE TITLE
Frequent "no such host" errors

### ISSUE THREAD

**Issue by lukeasrodgers** [aws/amazon-ecs-cli#89]
I may have something misconfigured, but `ecs-cli` periodically and randomly (afaict) fails with a "no such host found" error. Retrying sometimes succeeds, usually continues to fail. For example:

```
luke@Lukes-MBP ~/mypath $ ecs-cli down --force
ERRO[0000] Error executing 'down': RequestError: send request failed
caused by: Post https://ecs.us-east-1.amazonaws.com/: dial tcp: lookup ecs.us-east-1.amazonaws.com: no such host
luke@Lukes-MBP ~/mypath $ ecs-cli down --force
ERRO[0000] Error executing 'down': RequestError: send request failed
caused by: Post https://ecs.us-east-1.amazonaws.com/: dial tcp: lookup ecs.us-east-1.amazonaws.com: no such host
luke@Lukes-MBP ~/mypath $ ecs-cli down --force
ERRO[0000] Error executing 'down': RequestError: send request failed
caused by: Post https://ecs.us-east-1.amazonaws.com/: dial tcp: lookup ecs.us-east-1.amazonaws.com: no such host
luke@Lukes-MBP ~/mypath $ ecs-cli down --force
INFO[0000] Waiting for your cluster resources to be deleted
INFO[0001] Cloudformation stack status                   stackStatus=DELETE_IN_PROGRESS
INFO[0031] Deleted cluster                               cluster=foocluster
```

In between the several failed requests and the successful one I changed nothing. I am not behind a firewall or proxy. I am able to ping `ecs.us-east-1.amazonaws.com` just fine. 

Similarly: 

```
luke@Lukes-MBP ~/somepath$ ecs-cli ps
ERRO[0000] Error executing 'ps RequestError: send request failed
caused by: Post https://ecs.us-east-1.amazonaws.com/: dial tcp: lookup ecs.us-east-1.amazonaws.com: no such host
luke@Lukes-MBP ~/somepath$ ecs-cli ps
ERRO[0000] Error executing 'ps RequestError: send request failed
caused by: Post https://ecs.us-east-1.amazonaws.com/: dial tcp: lookup ecs.us-east-1.amazonaws.com: no such host
luke@Lukes-MBP ~/somepath$ ecs-cli ps
ERRO[0000] Error executing 'ps Cluster 'foocluster' is not active. Ensure that it exists
```

Running similar commands with `aws ecs` (e.g. `aws ecs describe-clusters --cluster foocluster --profile fooprofile`) works fine.

Is this typical?

Platform/version info:
osx 10.10.5

```
luke@Lukes-MBP ~$ uname -a
Darwin Lukes-MBP.fios-router.home 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
luke@Lukes-MBP ~$ ecs-cli --version
ecs-cli version 0.2.1 (e7b6965)
luke@Lukes-MBP ~$ aws --version
aws-cli/1.10.10 Python/2.7.10 Darwin/14.5.0 botocore/1.4.1
```

**Comment by bryceray1121** [comment]
I am seeing this issue as well, it appears quite random and disruptive to deployments.

**Comment by lukeasrodgers** [comment]
@bryceray1121 are you on OSX? This issue may have been related to the one discussed in https://github.com/flynn/flynn/issues/2535 and https://github.com/flynn/flynn/issues/2508 -- I believe ECS CLI and Flynn CLI both use Go.

**Comment by uttarasridhar** [comment]
@lukeasrodgers @bryceray1121 : Are you still seeing this issue?
Looking at the related issues, an update to go1.6 seems to have fixed similar issues in flynn. ecs-cli was updated to go1.6 in v0.4.0 release

**Comment by lukeasrodgers** [comment]
@uttarasridhar I haven't seen those errors in a long time, but I am no longer frequently using ECS CLI. Feel free to close this issue if you want.
cheers
