### ISSUE TITLE
'Cloudformation failure waiting for CREATE_COMPLETE' attempting to ecs-cli up

### ISSUE THREAD

**Issue by nathanleclaire** [aws/amazon-ecs-cli#9]
Trying to `ecs-cli up` I encountered an issue:

```console
$ ecs-cli up --keypair my-key --capability-iam --size 2
INFO[0000] Created cluster                               cluster=nates-cluster
INFO[0000] Waiting for your cluster resources to be created
INFO[0001] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
ERRO[0031] Failure event                                 reason= resourceType=AWS::CloudFormation::Stack
ERRO[0031] Error executing 'up': Cloudformation failure waiting for 'CREATE_COMPLETE'. State is 'ROLLBACK_COMPLETE'
```

I have no idea what this CloudFormation error means.  I think this is related to not specifying a valid key pair (I accidentally used `my-key` like the tutorial instead of the one I'd created for the service), but some more helpful messages would be nice.

**Comment by warseph** [comment]
I'm having the same issue, were you able to find the cause, or a workaround, @nathanleclaire ? Thanks!

**Comment by nathanleclaire** [comment]
@warseph In my case it seemed to succeed after I created and used a valid SSH keypair, YMMV.

**Comment by warseph** [comment]
The problem was the keypair was in a different zone. It would be awesome if the cli provided an error message that actually explains what the problem is in this situation.

**Comment by bhanushrestha** [comment]
I saw the comments above and even though I have used the keypair of the same zone as i was trying to create the cluster of , I got the same error. Could there be any other cause for this? Is there any other solution or any other process I may have missed?

**Comment by dzlab** [comment]
I have the same error message: I'm using ecs-cli version 0.1.0 (*cbdc2d5) on OSX El Capitan, my cluster and key pair are in the same zone.

**Comment by uttarasridhar** [comment]
Sorry that you are unable to view the error messages for the failures. We have made the code change to report the error message. It would be a part of the next release of the CLI.

For now, you can go to the CloudFormation console and look for the error message in the events tab.

**Comment by dzlab** [comment]
thanks for the hint, it's actually what I've end up doing and realized I was using a wrong key pair.

**Comment by dengemann** [comment]
I think the documentation could also be improved by stating more clearly that the key parameter here refers to the key name of an existing .pem keypair that is commonly used to launch an EC2 instance. It took me a good while to figure out how to use this.

**Comment by littlexiaoxiao** [comment]
I am running into this issue even though I used the RSA PRIVATE KEY in .pem file.

The first time I use the entire RSA PRIVATE KEY in the .pem file, it failed with "Parameter validation failed ... Error executing 'up': Cloudformation failure waiting for 'CREATE_COMPLETE'. State is 'ROLLBACK_COMPLETE' "

The second time when I try the CLI again, it failed with " Error executing 'up': A CloudFormation stack already exists for the cluster 'mycluster"

How to fix it?

**Comment by krebstar01** [comment]
#1
aws cloudformation list-stacks 
### find your_stack_name from the output

#2
aws cloudformation  delete-stack --stack-name your_stack_name

**Comment by helloravi** [comment]
I have the keypair in us-west-2. I am still getting the same issue.
ERRO[0072] Failure event                                 reason="Parameter validation failed: parameter value transin-ravi-ecsdemo.pem for parameter name KeyName does not exist. Rollback requested by user." resourceType="AWS::CloudFormation::Stack"
