### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by lox** [aws/amazon-ecs-cli#90]
Is this project still alive? Commits seem few and far between and there is close to no response to lots of issues.

**Comment by lox** [comment]
*crickets*

**Comment by rjocoleman** [comment]
https://github.com/aws/amazon-ecs-cli/pull/104

v0.3.0 just came out the other day  `\_(ツ)_/¯`

**Comment by willejs** [comment]
Its barely still alive, theres no new features, and very little bug fixes. id jump ship to something else if i were you.

**Comment by ambrons** [comment]
@willejs any sugguestions?  We've been looking at jumping almost entirely off AWS from a standpoint of allowing AWS to be our hardware and then use mesosphere with either marathon or docker swarm as a framework.  

We've also looked at ION Roller, but it seems to be in nearly the same boat as ECS-CLI.

Do people just create these for the purpose of conferences? =)

**Comment by lox** [comment]
We built https://github.com/99designs/ecs-cli as a replacement.

**Comment by uttarasridhar** [comment]
Hi @lox @ambrons, thanks for the question. Yes, we do intend to continue to prioritize issues and add features that are important to the community. We recently launched [v0.4.1](https://github.com/aws/amazon-ecs-cli/releases/tag/v0.4.1) with support for Compose v2 format among other enhancements. If there is a particular issue that you would like us to consider prioritizing, please let us know.
Thank you.

**Comment by ambrons** [comment]
@uttarasridhar for starts PR #62 and PR #21 would be a great addition.

Also allowing you to specify the instance role would be ideal as we have several policies that have to be attached after the fact, aka we've already created the role we need.

**Comment by lox** [comment]
I can't believe this issue is still open :)

**Comment by yinshiua** [comment]
We are actively looking into the issues and developing new features. We recently launched v0.6.0 with several bug fixes and features, and we are working on leveraging ECS CLI as our main source for developer tooling. Closing this issue, but please feel free to submit new issues if you have any requests or hit “like” on older issues so we can better prioritize our road map.
