### ISSUE TITLE
Is there any way to create a new version of an existing Task Definition with different image path/url through CLI?

### ISSUE THREAD

**Issue by XiSmartElf** [aws/amazon-ecs-cli#91]
Is there any way to create a new version of an existing Task Definition with different image path/url through CLI?

**Comment by uttarasridhar** [comment]
ecs-cli helps you create new task definition revisions through **docker compose file format**.

`ecs-cli compose` command creates task definitions, that are named after the compose project-name. Once you update the docker-compose.yml file with a new image path/url, you can run `ecs-cli compose create` to create a new ECS Task Definition revision for that project.

TaskDefinition name format : "{{compose-project--name-prefix}}{{project-name}}"
* compose-project-name-prefix : can be configured using `ecs-cli configure` (defaults to 'ecscompose-')
* project-name : can be configured using `ecs-cli compose` command (defaults to {{directory-name}})

You can see more information in our [docs](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html).

Hope that helps. Feel free to reopen the issue if you have more questions.
