### ISSUE TITLE
MFA support in credentials

### ISSUE THREAD

**Issue by atorstling** [aws/amazon-ecs-cli#92]
Hello! I have profiles in `~/.aws/credentials` which require MFA, like this:

```
[base]
aws_access_key_id = LKSDLFKJSDFLKSJDFLKSJF
aws_secret_access_key = sOmEthinG
region = eu-west-1

[derived]
source_profile = base
role_arn = arn:aws:iam:9287239874987293847:role/SomeRole
mfa_serial = arn:aws:iam:2349874239857439587:mfa/my.name@my.domain
```

If I configure ecs-cli with `ecs-cli configure --cluster some -p derived` and run a command, ecs-cli answers with 

```
ERRO[0000] Error executing 'ps NoCredentialProviders: no valid providers in chain
```

If I instead try `ecs-cli configure --cluster some -p base`, i get something like 

```
ERRO[0000] Error executing 'ps AccessDeniedException: User: arn:aws:iam::9349857349857:user/my.name@my.domain is not authorized to perform: ecs:DescribeClusters on resource: arn:aws:ecs:eu-west-1:20394820984:cluster/some
    status code: 400, request id: 96eb9570-d8383-11e5-ae03-cd02e128993d
```

So it's as if ecs-cli skips reading the derived profile for some reason.

**Comment by bastianb** [comment]
Strange the title says, `MFA support` but none of the merged commits include anything for it.....
please assist on https://github.com/aws/amazon-ecs-cli/issues/284
