### ISSUE TITLE
ecs-cli logs --follow double newlines

### ISSUE THREAD

**Issue by bliles** [aws/amazon-ecs-cli#934]
#### Summary
When tailing the log for a task running in ECS I'm getting double newlines in the ouput for each CloudWatch log entry.

#### Description

* Which specific command was run? `ecs-cli logs --task-id 1234... --cluster CLUSTER --follow
* Which version of the CLI you are using? 1.16.0 (5c02c34)
* Which version of Go are you using? go version go1.12.9 linux/amd64
* What platform are you using to run ECS CLI commands? Linux

#### Config files
n/a

#### Expected Behavior
For each record in CloudWatch for the task's log there should be one newline in the output

#### Observed Behavior
```
ecs-cli logs --task-id=1234... --cluster ECIAJobs --follow
Starting Job.

Creating CSV file...

Adding to CSV...

Adding to CSV...

Adding to CSV...

Adding to CSV...
...
```
The job in question is a .NET Core cli app running on ECS Fargate. It is writing logs with Console.WriteLine.

**Comment by hencrice** [comment]
Hey @bliles thanks for reporting this. We actually did it intentionally to make the logs more readable: https://github.com/hencrice/amazon-ecs-cli/blame/master/ecs-cli/modules/cli/logs/logs_app.go#L160.

Closing it for now. Feel free to reopen if you would like to discuss it further.

**Comment by bliles** [comment]
I don't think this makes the logs more readable, it actually made me think the ecs logs feature was broken and decide not to use it, maybe it's just me, but every logging system I can think of displays logs with one newline following each log line by default at least.

**Comment by dead10ck** [comment]
I have to agree; in my opinion, this does not improve readability, but hampers it. No other system I know of inserts extra new lines when showing you logs.

**Comment by tomglynch** [comment]
I agree. Let the developer decide whether to add extra returns.

**Comment by juskrey** [comment]
If I wanted to alter output in any weird way, I would pipe it to awk or sed. Here I should do the opposite to just make it look normal. Why?

**Comment by ghost** [comment]
Please could I request this is reopened and a CLI flag added to disable/enable this?

**Comment by ghost** [comment]
If it helps anyone, here's our workaround:

`ecs-cli logs --task-id ... --cluster ... --timestamps --follow | awk NF`
