### ISSUE TITLE
ecs-cli compose service - multiple compose files - too many containers

### ISSUE THREAD

**Issue by ict-singapore** [aws/amazon-ecs-cli#951]
#### Summary
ecs-cli compose service not reading multiple docker-compose.yml files 

#### Description
Trying to use ecs-cli compose service command for building [Alfresco](https://github.com/Alfresco/acs-deployment/blob/master/docker-compose/docker-compose.yml) and deploying it on Fargate services. 

Used the default command to build services. First command error : Too many containers. Broke the compose to smaller parts, however, command doesn't read the compose files properly and build is only partial

* Which specific command was run? 
**Command 1:**  Default docker-compose.yml (with all 16 images)
ecs-cli compose --project-name acs-fargate service up \
--cluster-config acs-fargate \
--ecs-profile acs-fargate  \
--target-group-arn arn:address \
--container-name alfresco \
--container-port 8080

This failed with 
`ERRO[0000] Error registering task definition    error="ClientException: Too many containers.\n\tstatus code: 400, request id: 9a29d4e8-9170-4ff1-ae95-242f97c2ec2d" family=acs-fargate`

**Command 2:** 
As per the earlier error , broke the compose file into separate files (with a min of 3 to max of 6 per file) and tried the following command

ecs-cli compose --file docker-compose.yml --file docker-compose.services.yml --file docker-compose.search.yml --file docker-compose.db.yml \
--project-name acs-fargate service up \
--cluster-config acs-fargate \
--ecs-profile acs-fargate \
--target-group-arn arn:address \
--container-name alfresco \
--container-port 8080

`ERRO[0000] Error registering task definition             error="ClientException: Too many containers.\n\tstatus code: 400, request id: 17c90219-b6e2-44a8-93f6-0d4e6b43748c" family=acs-fargate`

* Which version of the CLI you are using?
ecs-cli version 1.17.0 (0301ac8)

* Which version of Go are you using? 
go version go1.12.8 linux/amd64

* What platform are you using to run ECS CLI commands? 
Amazon Linux / Cloud9

#### Config files
**docker-compose.yml** is [here](https://github.com/Alfresco/acs-deployment/blob/master/docker-compose/docker-compose.yml)

**ecs-params.yml** 

version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 16384
    cpu_limit: 2048
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-xxxxxxx"
        - "subnet-xxxxxxx"
      security_groups:
        - "sg-xxxxxxxxxxxxxx"
      assign_public_ip: DISABLED

** ~/.ecs/config**

version: v1
default: tutorial
clusters:
  acs-fargate:
    cluster: acs-fargate
    region: ap-southeast-1
    default_launch_type: FARGATE

Is there a limit to the containers that can be built in Fargate. Any help / pointers would be appreciated

**Comment by hencrice** [comment]
Hey @ict-singapore thanks for reaching out.

The current behavior of ecs-cli is to generate only 1 task definition regardless of how many `--file` flags are used. And the service has a limit of 10 containers per task definition. This [link](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/application_architecture.html) contains guidance on when & when not to put containers in the same task definition. In short, You should put multiple containers in the same task definition if:

1. Containers share a common lifecycle (that is, they should be launched and terminated together).

2. Containers are required to be run on the same underlying host (that is, one container references the other on a localhost port).

3. You want your containers to share resources.

4. Your containers share data volumes.

Let us know if you have more questions :)

**Comment by hencrice** [comment]
Closed due to lack of activities
