### ISSUE TITLE
Add run Command

### ISSUE THREAD

**Issue by deuscapturus** [aws/amazon-ecs-cli#960]
#### Context

I would like a convenient `run` command that would allow me to do the following:

1.  Start task from task definition (in ECS, not local file)
2.  Optionally stream log output
3.  Optionally wait until task has completed and output status code
4.  Optionally use task run status code as  ecs-cli exit code

```
$ ecs-cli run --help
NAME:
   ecs-cli run - Run ECS task from a task definition

USAGE:
   ecs-cli run [command options] TASK_DEFINITION[:VERSION]

OPTIONS:
   --wait                     [Optional] Specifies if command should wait for task to stop before returning.  Task status code will become the cli exit code.
   --logs                     [Optional] Specifies if the logs should be streamed.
   --region value, -r value   [Optional] Specifies the AWS region to use. Defaults to the region configured using the configure command
   --ecs-profile value        [Optional] Specifies the name of the ECS profile configuration to use. Defaults to the default profile configuration. [$ECS_PROFILE]
   --aws-profile value        [Optional] Use the AWS credentials from an existing named profile in ~/.aws/credentials. [$AWS_PROFILE]
   --cluster-config value     [Optional] Specifies the name of the ECS cluster configuration to use. Defaults to the default cluster configuration.
   --cluster value, -c value  [Optional] Specifies the ECS cluster name to use. Defaults to the cluster configured using the configure command
```

#### Alternatives

Bash together ecs-cli with awscli or write your own client using an SDK.

#### Has the feature been requested before?

I don't think so.

#### Additional context

I'll contribute this command myself if the community is open to merging it.

**Comment by pkandasamy91** [comment]
@deuscapturus feel free to submit a PR, we'd be more than happy to review it!

**Comment by pkandasamy91** [comment]
@deuscapturus would you be able to provide more context as to what your use case is?

**Comment by SoManyHs** [comment]
Hi @deuscapturus!

Have you checked out the new [copilot cli](https://github.com/aws/copilot-cli)? We recently added a [task run](https://github.com/aws/copilot-cli#running-a-one-off-task-%EF%B8%8F) workflow there, which includes streaming log output and more! Let us know if that answers your use case!
