### ISSUE TITLE
Local Endpoints container can only run with AWS_PROFILE=default

### ISSUE THREAD

**Issue by ndavies-om1** [aws/amazon-ecs-cli#962]
#### Context

When running locally, ecs-cli local endpoints container always using AWS_PROFILE=default. Problematic as default credentials may not have the permissions to do what is needed, for example list roles. Especially problematic in cross account scenarios.

#### Alternatives

Do terrible things with IAM to enable users to do things cross account

#### Has the feature been requested before?

Couldn't find anything

#### Additional context

I have a fix!

**Comment by pkandasamy91** [comment]
@ndavies-om1 Thanks for taking the time to create the issue and for providing a fix!
