### ISSUE TITLE
undisclosed go dep version being used to generate `Gopkg.lock`

### ISSUE THREAD

**Issue by diablodale** [aws/amazon-ecs-cli#977]
Starting at commit https://github.com/aws/amazon-ecs-cli/commit/2c9a2571099457fc6cdb2b26fa786acf6f8350f5#diff-197c39a114959e8b2f4be817bc6f000f
an undisclosed version of go `dep` started being used. This is seen by the mass inclusion of additional fields in `Gopkg.lock`. Those additional fields are `digest` and `pruneopts`.

### Setup

dep v0.4.1 is the stated version for building `ecs-cli` as per the contributing docs https://github.com/aws/amazon-ecs-cli/blob/master/CONTRIBUTING.md#environment
and Makefile

https://github.com/aws/amazon-ecs-cli/blob/d1685dd9bbd4e3d9375a7e076f69cc20ec64c13b/Makefile#L25

### Actual Result

As I understand, it is not possible for `dep` 0.4.1 to have made the `Gopkg.lock` starting at that commit. For example

https://github.com/aws/amazon-ecs-cli/blob/2c9a2571099457fc6cdb2b26fa786acf6f8350f5/ecs-cli/Gopkg.lock#L4-L21

According to https://golang.github.io/dep/blog/2018/07/25/announce-v0.5.0.html#performance-improvements those two fields `digest` and `pruneopts` were only available starting with dep v0.5.0.

### Fix needed

What dep version is being used to generate `Gopkg.lock`?

If it is not 0.4.1, then such needs to be updated in at least the Contributing and Makefile refererenced above.

**Comment by diablodale** [comment]
I used dep v0.5.4 to updated one dependency. I reviewed then my `Gopkg.lock` file.
The lock file is very much like what is currently on master. This suggests that someone is using dep in the v0.5.x generation 🤔 rather than 0.4.1 as per documentation and Makefile.

**Comment by PettitWesley** [comment]
@diablodale I think we should update the docs and Makefile to use v0.5.4 (the latest version).

**Comment by diablodale** [comment]
Ok. Will submit a PR with slight updates for that.
