### ISSUE TITLE
port of variable subsitution in compose files

### ISSUE THREAD

**Issue by aespinosa** [aws/amazon-ecs-cli#98]
Hi,

We continuously deploy our Docker images as tasks in our Jenkins pipeline.  Right now, I have to use adhoc string replacement with sed to put the custom image tags in our compose files. We would like to have string interpolation like in the upstream docker-compose [1] to remove this ad-hoc-ery.

[1] https://docs.docker.com/compose/compose-file/#variable-substitution

**Comment by uttarasridhar** [comment]
Duplicate of #28 . Tracking it there.
