### ISSUE TITLE
"ecs-cli up --spot-price" does not create EC2 Spot Instances

### ISSUE THREAD

**Issue by kororo** [aws/amazon-ecs-cli#997]
#### Summary
Following on the documentation here
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-cli-tutorial-ec2.html

Using "ecs-cli up" to create a new ECS cluster with EC2 launch type with Spot Instance options. After command executed correctly, it doesn't create EC2 spot instances. 

When creating task it shows error as:
FATA[0005] InvalidParameterException: No Container Instances were found in your cluster.

#### Description

* AWS_PROFILE and ECS_PROFILE are configured correctly
* AWS_PROFILE has IAM with ec2:* and ecs:* for debugging the issue
* IAM roles are configured correctly
* ecs-cli version is ecs-cli version 1.18.1 (*UNKNOWN)
* go version is go version go1.13 darwin/amd64
* Running on macOS

#### Expected Behavior
ECS cluster created with EC2 with spot instances.

#### Observed Behavior
INFO[0000] Using Arm ecs-optimized AMI because instance type was a1.medium
INFO[0000] Using recommended Amazon Linux 2 AMI with ECS Agent 1.37.0 and Docker version 18.09.9-ce
INFO[0000] Created cluster                               cluster=xxx region=ap-southeast-2
DEBU[0001] Cloudformation create stack call succeeded    stackId=xxx
INFO[0001] Waiting for your cluster resources to be created...
DEBU[0001] parsing event                                 eventStatus=CREATE_IN_PROGRESS resource="arn:aws:cloudformation:ap-southeast-2:xxx"
INFO[0001] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
DEBU[0031] parsing event                                 eventStatus=CREATE_COMPLETE resource=xxx
DEBU[0031] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
DEBU[0061] parsing event                                 eventStatus=CREATE_COMPLETE resource=xxx
INFO[0061] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
DEBU[0091] parsing event                                 eventStatus=CREATE_COMPLETE resource=xxx
DEBU[0091] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
DEBU[0121] parsing event                                 eventStatus=CREATE_COMPLETE resource=xxx
INFO[0121] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
DEBU[0151] parsing event                                 eventStatus=CREATE_IN_PROGRESS resource=
DEBU[0152] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
DEBU[0182] parsing event                                 eventStatus=CREATE_COMPLETE resource="arn:aws:cloudformation:ap-southeast-2:xxx"
VPC created: xxx
Security Group created: xxx
Subnet created: xxx
Subnet created: xxx
Cluster creation succeeded.

**Comment by kororo** [comment]
Hi there,

I may found the issue of this. Upon trying to debug and understand the problem.

First thing that I did, is find all the "spot" references in the code:
https://github.com/aws/amazon-ecs-cli/search?q=spot&unscoped_q=spot

Found the code that injecting the spot into CF:
https://github.com/aws/amazon-ecs-cli/blob/3d012a830435a1f3fcc4701c295a2bb106d38022/ecs-cli/modules/cli/cluster/cluster_app.go

Checking the CF template, actually it is using standard Auto Scaling Group (ASG):
Silly enough I didnt check this, I found event logs:
Launching a new EC2 instance. Status Reason: Your requested instance type (a1.medium) is not supported in your requested Availability Zone (ap-southeast-2a). Please retry your request by not specifying an Availability Zone or choosing ap-southeast-2b, ap-southeast-2c. Launching EC2 instance failed.

Checkin the CLI doco, https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-up.html, I can do:

`
ecs-cli up --capability-iam --instance-type a1.medium --spot-price 0.03 --azs ap-southeast-2b,ap-southeast-2c
`

Thanks once again. If I may recommend, probs, some checking on the instances availability to  alert that cluster is created but instances are not up and running.

**Comment by unfor19** [comment]
I have no idea where you found `--spot-price` in the docs, but luckily you mentioned it here, so I used it
