### ISSUE TITLE
the files I upload to my volume are not reflected in my ecs task aws

### ISSUE THREAD

**Issue by eedm268** [aws/amazon-ecs-cli#999]
I am writing to you because I have problems with ECS (AWS).

I show you my task definition part:

  "mountPoints": [

    {

      "readOnly": false,

      "containerPath": "/opt/app/main/",

      "sourceVolume": "volumen-vol"

    }
"volumes": [

{

  "efsVolumeConfiguration": null,

  "name": "volumen-vol",

  "host": {

    "sourcePath": "/usr/src/files/"

  }
doing a docker inspect, after the task is running: "Mounts": [ { "Type": "bind", "Source": "/usr/src/files", "Destination": "/opt/app/main", "Mode": "", "RW": true, "Propagation": "rprivate" } with this shown, I explain the problem

1.- I upload files to the volume with path /usr/src/files (volumen)

2.- when you start the task, the files are reflected in /opt/app/main (mountPoints)

3.- I make a request to my application to verify that the file is in the mount point and it works well, the file exists and contains the correct data

4.- then I delete or modify files in /usr/src/files (volumen)

5.- the changes are reflected in me /opt/app/main (mountPoints), without restarting the task

6.- when I request my application, I DON'T SEE THE CHANGES. I

**Comment by PettitWesley** [comment]
@eedm268 I'm not sure what's going wrong here. As you explained/saw in 1-5 the bind-mount essentially makes it so that the `/opt/app/main` directory in your container and the `/usr/src/files/` directory on the host *are the same directory*. So any changes in one will be reflected in the other since they are the same thing.

> when I request my application, I DON'T SEE THE CHANGES

Can you explain more what you mean by "request your application". Is your app doing some sort of caching of these files such that the deletion is not immediately reflected in the app?

**Comment by eedm268** [comment]
@PettitWesley when i say that "request my application", is to request by postman to an endpoint of the application. With this I verify if the volume changes are or not in the application.

The application does not handle any type of cache.

**Comment by hencrice** [comment]
@eedm268 could you elaborate a little bit on what your application does? Is it a web server of some sort? What kind of web server framework are you using?

Many operating system actually caches information in memory once a process starts (for example, it's entirely possible to launch an executable as a process, and it deletes its own binary on disk. The process will run fine), so unless your application explicitly monitors disk writes, it might not notice there's a change on the artifacts on the disk.

**Comment by SoManyHs** [comment]
Closing for staleness.
